package com.vone.medisafe.mapping.pojo.diagnose;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsIcd9cm generated by MyEclipse - Hibernate Tools
 */

public class MsIcd9cm  implements java.io.Serializable {


    // Fields    

     private Integer NIcd9cmId;
     private String VIcd9cmCode;
     private String VIcd9cmName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbDiagnoses = new HashSet(0);
     private Set tbOperations = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsIcd9cm() {
    }

	/** minimal constructor */
    public MsIcd9cm(Integer NIcd9cmId, String VIcd9cmCode, String VIcd9cmName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NIcd9cmId = NIcd9cmId;
        this.VIcd9cmCode = VIcd9cmCode;
        this.VIcd9cmName = VIcd9cmName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }
    
    /** full constructor */
    public MsIcd9cm(Integer NIcd9cmId, String VIcd9cmCode, String VIcd9cmName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbDiagnoses, Set tbOperations) {
        this.NIcd9cmId = NIcd9cmId;
        this.VIcd9cmCode = VIcd9cmCode;
        this.VIcd9cmName = VIcd9cmName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbDiagnoses = tbDiagnoses;
        this.tbOperations = tbOperations;
    }

   
    // Property accessors

    public Integer getNIcd9cmId() {
        return this.NIcd9cmId;
    }
    
    public void setNIcd9cmId(Integer NIcd9cmId) {
        this.NIcd9cmId = NIcd9cmId;
    }

    public String getVIcd9cmCode() {
        return this.VIcd9cmCode;
    }
    
    public void setVIcd9cmCode(String VIcd9cmCode) {
        this.VIcd9cmCode = VIcd9cmCode;
    }

    public String getVIcd9cmName() {
        return this.VIcd9cmName;
    }
    
    public void setVIcd9cmName(String VIcd9cmName) {
        this.VIcd9cmName = VIcd9cmName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbDiagnoses() {
        return this.tbDiagnoses;
    }
    
    public void setTbDiagnoses(Set tbDiagnoses) {
        this.tbDiagnoses = tbDiagnoses;
    }

    public Set getTbOperations() {
        return this.tbOperations;
    }
    
    public void setTbOperations(Set tbOperations) {
        this.tbOperations = tbOperations;
    }
   








}