package com.vone.medisafe.mapping.pojo.diagnose;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsIcd generated by MyEclipse - Hibernate Tools
 */

public class MsIcd  implements java.io.Serializable {


    // Fields    

     private Integer NIcdId;
     private String VIcdCode;
     private String VIcdName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbIllnesses = new HashSet(0);
     private Set tbDiagnoses = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsIcd() {
    }

	/** minimal constructor */
    public MsIcd(Integer NIcdId, String VIcdCode, String VIcdName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NIcdId = NIcdId;
        this.VIcdCode = VIcdCode;
        this.VIcdName = VIcdName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }
    
    /** full constructor */
    public MsIcd(Integer NIcdId, String VIcdCode, String VIcdName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbIllnesses, Set tbDiagnoses) {
        this.NIcdId = NIcdId;
        this.VIcdCode = VIcdCode;
        this.VIcdName = VIcdName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbIllnesses = tbIllnesses;
        this.tbDiagnoses = tbDiagnoses;
    }

   
    // Property accessors

    public Integer getNIcdId() {
        return this.NIcdId;
    }
    
    public void setNIcdId(Integer NIcdId) {
        this.NIcdId = NIcdId;
    }

    public String getVIcdCode() {
        return this.VIcdCode;
    }
    
    public void setVIcdCode(String VIcdCode) {
        this.VIcdCode = VIcdCode;
    }

    public String getVIcdName() {
        return this.VIcdName;
    }
    
    public void setVIcdName(String VIcdName) {
        this.VIcdName = VIcdName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbIllnesses() {
        return this.tbIllnesses;
    }
    
    public void setTbIllnesses(Set tbIllnesses) {
        this.tbIllnesses = tbIllnesses;
    }

    public Set getTbDiagnoses() {
        return this.tbDiagnoses;
    }
    
    public void setTbDiagnoses(Set tbDiagnoses) {
        this.tbDiagnoses = tbDiagnoses;
    }
   








}