package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;

import com.vone.medisafe.mapping.MsTreatmentClass;


/**
 * MsItemSellingPrice generated by MyEclipse - Hibernate Tools
 */

public class MsItemSellingPrice  implements java.io.Serializable {


    // Fields    

     private Integer NItemSellingPriceId;
     private MsItem msItem;
     private MsTreatmentClass msTreatmentClass;
     private double NSellingPrice;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public MsItemSellingPrice() {
    }

	/** minimal constructor */
    public MsItemSellingPrice(Integer NItemSellingPriceId, MsItem msItem, MsTreatmentClass msTreatmentClass, double NSellingPrice) {
        this.NItemSellingPriceId = NItemSellingPriceId;
        this.msItem = msItem;
        this.msTreatmentClass = msTreatmentClass;
        this.NSellingPrice = NSellingPrice;
    }
    
    /** full constructor */
    public MsItemSellingPrice(Integer NItemSellingPriceId, MsItem msItem, MsTreatmentClass msTreatmentClass, double NSellingPrice, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NItemSellingPriceId = NItemSellingPriceId;
        this.msItem = msItem;
        this.msTreatmentClass = msTreatmentClass;
        this.NSellingPrice = NSellingPrice;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNItemSellingPriceId() {
        return this.NItemSellingPriceId;
    }
    
    public void setNItemSellingPriceId(Integer NItemSellingPriceId) {
        this.NItemSellingPriceId = NItemSellingPriceId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

    public double getNSellingPrice() {
        return this.NSellingPrice;
    }
    
    public void setNSellingPrice(double NSellingPrice) {
        this.NSellingPrice = NSellingPrice;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}