package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsItemMeasurement generated by MyEclipse - Hibernate Tools
 */

public class MsItemMeasurement  implements java.io.Serializable {


    // Fields    

     private Integer NMitemId;
     private String VMitemEarlyQuantify;
     private String VMitemEndQuantify;
     private short NMitemEndQty;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsItemMeasurement() {
    }

	/** minimal constructor */
    public MsItemMeasurement(Integer NMitemId, String VMitemEarlyQuantify, String VMitemEndQuantify, short NMitemEndQty, String VWhoCreate, Date DWhnCreate) {
        this.NMitemId = NMitemId;
        this.VMitemEarlyQuantify = VMitemEarlyQuantify;
        this.VMitemEndQuantify = VMitemEndQuantify;
        this.NMitemEndQty = NMitemEndQty;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public MsItemMeasurement(Integer NMitemId, String VMitemEarlyQuantify, String VMitemEndQuantify, short NMitemEndQty, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msItems) {
        this.NMitemId = NMitemId;
        this.VMitemEarlyQuantify = VMitemEarlyQuantify;
        this.VMitemEndQuantify = VMitemEndQuantify;
        this.NMitemEndQty = NMitemEndQty;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msItems = msItems;
    }

   
    // Property accessors

    public Integer getNMitemId() {
        return this.NMitemId;
    }
    
    public void setNMitemId(Integer NMitemId) {
        this.NMitemId = NMitemId;
    }

    public String getVMitemEarlyQuantify() {
        return this.VMitemEarlyQuantify;
    }
    
    public void setVMitemEarlyQuantify(String VMitemEarlyQuantify) {
        this.VMitemEarlyQuantify = VMitemEarlyQuantify;
    }

    public String getVMitemEndQuantify() {
        return this.VMitemEndQuantify;
    }
    
    public void setVMitemEndQuantify(String VMitemEndQuantify) {
        this.VMitemEndQuantify = VMitemEndQuantify;
    }

    public short getNMitemEndQty() {
        return this.NMitemEndQty;
    }
    
    public void setNMitemEndQty(short NMitemEndQty) {
        this.NMitemEndQty = NMitemEndQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsItems() {
        return this.msItems;
    }
    
    public void setMsItems(Set msItems) {
        this.msItems = msItems;
    }
   








}