package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.MsCoa;


/**
 * MsItem generated by MyEclipse - Hibernate Tools
 */

public class MsItem  implements java.io.Serializable {


    // Fields    

     private Integer NItemId;
     private MsItemGroup msItemGroup;
     private MsItemMeasurement msItemMeasurement;
     private MsCoa itemSellAcctNo;
     private MsCoa itemCogsNo;
     private String VItemCode;
     private String VBarcodeNo;
     private String VItemName;
     private String VItemReturnable;
     private Short NItemBufferLimit;
     private Short NItemPlafon;
     private Short NItemType;
     private Short NR;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msItemSupplied = new HashSet(0);
     private Set tbBatchItem = new HashSet(0);

     private Integer nMaxOrder;
    // Constructors

    public Integer getnMaxOrder() {
		return nMaxOrder;
	}

	public void setnMaxOrder(Integer nMaxOrder) {
		this.nMaxOrder = nMaxOrder;
	}

	public Short getNR() {
		return NR;
	}

	public void setNR(Short nr) {
		NR = nr;
	}

	public Set getTbBatchItem() {
		return tbBatchItem;
	}

	public void setTbBatchItem(Set tbBatchItem) {
		this.tbBatchItem = tbBatchItem;
	}

	public Set getMsItemSupplied() {
		return msItemSupplied;
	}

	public void setMsItemSupplied(Set msItemSupplied) {
		this.msItemSupplied = msItemSupplied;
	}

	/** default constructor */
    public MsItem() {
    }

	/** minimal constructor */
    public MsItem(Integer NItemId, MsItemGroup msItemGroup, MsItemMeasurement msItemMeasurement, String VItemCode, String VItemName, String VItemReturnable, MsCoa itemSellAcctNo, MsCoa itemCogsNo, MsCoa itemInvAccNo, String VWhoCreate, Date DWhnCreate) {
        this.NItemId = NItemId;
        this.msItemGroup = msItemGroup;
        this.msItemMeasurement = msItemMeasurement;
        this.VItemCode = VItemCode;
        this.VItemName = VItemName;
        this.VItemReturnable = VItemReturnable;
        this.itemSellAcctNo = itemSellAcctNo;
        this.itemCogsNo = itemCogsNo;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
   
   
    // Property accessors

    public Integer getNItemId() {
        return this.NItemId;
    }
    
    public void setNItemId(Integer NItemId) {
        this.NItemId = NItemId;
    }

    public MsItemGroup getMsItemGroup() {
        return this.msItemGroup;
    }
    
    public void setMsItemGroup(MsItemGroup msItemGroup) {
        this.msItemGroup = msItemGroup;
    }

    public MsItemMeasurement getMsItemMeasurement() {
        return this.msItemMeasurement;
    }
    
    public void setMsItemMeasurement(MsItemMeasurement msItemMeasurement) {
        this.msItemMeasurement = msItemMeasurement;
    }

    public String getVItemCode() {
        return this.VItemCode;
    }
    
    public void setVItemCode(String VItemCode) {
        this.VItemCode = VItemCode;
    }

    public String getVBarcodeNo() {
        return this.VBarcodeNo;
    }
    
    public void setVBarcodeNo(String VBarcodeNo) {
        this.VBarcodeNo = VBarcodeNo;
    }

    public String getVItemName() {
        return this.VItemName;
    }
    
    public void setVItemName(String VItemName) {
        this.VItemName = VItemName;
    }

    public String getVItemReturnable() {
        return this.VItemReturnable;
    }
    
    public void setVItemReturnable(String VItemReturnable) {
        this.VItemReturnable = VItemReturnable;
    }

    public Short getNItemBufferLimit() {
        return this.NItemBufferLimit;
    }
    
    public void setNItemBufferLimit(Short NItemBufferLimit) {
        this.NItemBufferLimit = NItemBufferLimit;
    }

    public Short getNItemPlafon() {
        return this.NItemPlafon;
    }
    
    public void setNItemPlafon(Short NItemPlafon) {
        this.NItemPlafon = NItemPlafon;
    }

    public MsCoa getItemCogsNo() {
		return itemCogsNo;
	}

	public void setItemCogsNo(MsCoa itemCogsNo) {
		this.itemCogsNo = itemCogsNo;
	}
	
	public MsCoa getItemSellAcctNo() {
		return itemSellAcctNo;
	}

	public void setItemSellAcctNo(MsCoa itemSellAcctNo) {
		this.itemSellAcctNo = itemSellAcctNo;
	}

	public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public Short getNItemType() {
		return NItemType;
	}

	public void setNItemType(Short itemType) {
		NItemType = itemType;
	}

	
}