package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsItemGroup generated by MyEclipse - Hibernate Tools
 */

public class MsItemGroup  implements java.io.Serializable {


    // Fields    

     private Integer NItemGroupId;
     private String VItemGroupCode;
     private String VItemGroupName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsItemGroup() {
    }

	/** minimal constructor */
    public MsItemGroup(Integer NItemGroupId, String VItemGroupCode, String VItemGroupName, String VWhoCreate, Date DWhnCreate) {
        this.NItemGroupId = NItemGroupId;
        this.VItemGroupCode = VItemGroupCode;
        this.VItemGroupName = VItemGroupName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public MsItemGroup(Integer NItemGroupId, String VItemGroupCode, String VItemGroupName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msItems) {
        this.NItemGroupId = NItemGroupId;
        this.VItemGroupCode = VItemGroupCode;
        this.VItemGroupName = VItemGroupName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msItems = msItems;
    }

   
    // Property accessors

    public Integer getNItemGroupId() {
        return this.NItemGroupId;
    }
    
    public void setNItemGroupId(Integer NItemGroupId) {
        this.NItemGroupId = NItemGroupId;
    }

    public String getVItemGroupCode() {
        return this.VItemGroupCode;
    }
    
    public void setVItemGroupCode(String VItemGroupCode) {
        this.VItemGroupCode = VItemGroupCode;
    }

    public String getVItemGroupName() {
        return this.VItemGroupName;
    }
    
    public void setVItemGroupName(String VItemGroupName) {
        this.VItemGroupName = VItemGroupName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsItems() {
        return this.msItems;
    }
    
    public void setMsItems(Set msItems) {
        this.msItems = msItems;
    }
   








}