package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.MsCoa;


/**
 * MsVendor generated by MyEclipse - Hibernate Tools
 */

public class MsVendor  implements java.io.Serializable {


    // Fields    

     private Integer NVendorId;
     private String VVendorCode;
     private String VVendorName;
     private String VVendorAddress;
     private String VVendorContactPerson;
     private String VVendorContactNo;
     private String VVendorAltContactNo;
     private String VVendorFaxNo;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private MsCoa msCoa;
     private Date DWhnChange;
     private Set tbPurchaseOrders = new HashSet(0);
     private Set msItemSupplieds = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsVendor() {
    }

	/** minimal constructor */
    public MsVendor(Integer NVendorId, String VVendorCode, String VVendorName, String VVendorAddress, String VVendorContactPerson, String VVendorContactNo, String VVendorAltContactNo, String VVendorFaxNo, String VWhoCreate, Date DWhnCreate) {
        this.NVendorId = NVendorId;
        this.VVendorCode = VVendorCode;
        this.VVendorName = VVendorName;
        this.VVendorAddress = VVendorAddress;
        this.VVendorContactPerson = VVendorContactPerson;
        this.VVendorContactNo = VVendorContactNo;
        this.VVendorAltContactNo = VVendorAltContactNo;
        this.VVendorFaxNo = VVendorFaxNo;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public MsVendor(Integer NVendorId, String VVendorCode, String VVendorName, String VVendorAddress, String VVendorContactPerson, String VVendorContactNo, String VVendorAltContactNo, String VVendorFaxNo, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPurchaseOrders, Set msItemSupplieds) {
        this.NVendorId = NVendorId;
        this.VVendorCode = VVendorCode;
        this.VVendorName = VVendorName;
        this.VVendorAddress = VVendorAddress;
        this.VVendorContactPerson = VVendorContactPerson;
        this.VVendorContactNo = VVendorContactNo;
        this.VVendorAltContactNo = VVendorAltContactNo;
        this.VVendorFaxNo = VVendorFaxNo;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbPurchaseOrders = tbPurchaseOrders;
        this.msItemSupplieds = msItemSupplieds;
    }

   
    // Property accessors

    public Integer getNVendorId() {
        return this.NVendorId;
    }
    
    public void setNVendorId(Integer NVendorId) {
        this.NVendorId = NVendorId;
    }

    public String getVVendorCode() {
        return this.VVendorCode;
    }
    
    public void setVVendorCode(String VVendorCode) {
        this.VVendorCode = VVendorCode;
    }

    public String getVVendorName() {
        return this.VVendorName;
    }
    
    public void setVVendorName(String VVendorName) {
        this.VVendorName = VVendorName;
    }

    public String getVVendorAddress() {
        return this.VVendorAddress;
    }
    
    public void setVVendorAddress(String VVendorAddress) {
        this.VVendorAddress = VVendorAddress;
    }

    public String getVVendorContactPerson() {
        return this.VVendorContactPerson;
    }
    
    public void setVVendorContactPerson(String VVendorContactPerson) {
        this.VVendorContactPerson = VVendorContactPerson;
    }

    public String getVVendorContactNo() {
        return this.VVendorContactNo;
    }
    
    public void setVVendorContactNo(String VVendorContactNo) {
        this.VVendorContactNo = VVendorContactNo;
    }

    public String getVVendorAltContactNo() {
        return this.VVendorAltContactNo;
    }
    
    public void setVVendorAltContactNo(String VVendorAltContactNo) {
        this.VVendorAltContactNo = VVendorAltContactNo;
    }

    public String getVVendorFaxNo() {
        return this.VVendorFaxNo;
    }
    
    public void setVVendorFaxNo(String VVendorFaxNo) {
        this.VVendorFaxNo = VVendorFaxNo;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPurchaseOrders() {
        return this.tbPurchaseOrders;
    }
    
    public void setTbPurchaseOrders(Set tbPurchaseOrders) {
        this.tbPurchaseOrders = tbPurchaseOrders;
    }

    public Set getMsItemSupplieds() {
        return this.msItemSupplieds;
    }
    
    public void setMsItemSupplieds(Set msItemSupplieds) {
        this.msItemSupplieds = msItemSupplieds;
    }

	public MsCoa getMsCoa() {
		return msCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		this.msCoa = msCoa;
	}
   








}