package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.TbDeliveryOrderDetail;


/**
 * TbBatchItem generated by MyEclipse - Hibernate Tools
 */

public class TbBatchItem  implements java.io.Serializable {


    // Fields    

     private Integer NBatchId;
     private MsItem msItem;
     private TbDeliveryOrderDetail tbDeliveryOrderDetail;
     private String VBatchNo;
     private Date DBatchExpDate;
     private short NBatchItemQty;
     private Double NCogsPrice;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbItemInventories = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbBatchItem() {
    }

   
    // Property accessors

    public Integer getNBatchId() {
        return this.NBatchId;
    }
    
    public Double getNCogsPrice() {
		return NCogsPrice;
	}


	public void setNCogsPrice(Double cogsPrice) {
		NCogsPrice = cogsPrice;
	}


	public void setNBatchId(Integer NBatchId) {
        this.NBatchId = NBatchId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbDeliveryOrderDetail getTbDeliveryOrderDetail() {
		return tbDeliveryOrderDetail;
	}

	public void setTbDeliveryOrderDetail(TbDeliveryOrderDetail tbDeliveryOrderDetail) {
		this.tbDeliveryOrderDetail = tbDeliveryOrderDetail;
	}


	public String getVBatchNo() {
        return this.VBatchNo;
    }
    

	public void setVBatchNo(String VBatchNo) {
        this.VBatchNo = VBatchNo;
    }

    public Date getDBatchExpDate() {
        return this.DBatchExpDate;
    }
    
    public void setDBatchExpDate(Date DBatchExpDate) {
        this.DBatchExpDate = DBatchExpDate;
    }

    public short getNBatchItemQty() {
        return this.NBatchItemQty;
    }
    
    public void setNBatchItemQty(short NBatchItemQty) {
        this.NBatchItemQty = NBatchItemQty;
    }
    
    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbItemInventories() {
        return this.tbItemInventories;
    }
    
    public void setTbItemInventories(Set tbItemInventories) {
        this.tbItemInventories = tbItemInventories;
    }
   








}