package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbBloodBank generated by MyEclipse - Hibernate Tools
 */

public class TbBloodBank  implements java.io.Serializable {


    // Fields    

     private Integer NBloodBankId;
     private MsBlood msBlood;
     private String VBloodBagId;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbExamDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbBloodBank() {
    }

	/** minimal constructor */
    public TbBloodBank(Integer NBloodBankId, MsBlood msBlood, String VBloodBagId, String VWhoCreate, Date DWhnCreate) {
        this.NBloodBankId = NBloodBankId;
        this.msBlood = msBlood;
        this.VBloodBagId = VBloodBagId;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbBloodBank(Integer NBloodBankId, MsBlood msBlood, String VBloodBagId, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbExamDetails) {
        this.NBloodBankId = NBloodBankId;
        this.msBlood = msBlood;
        this.VBloodBagId = VBloodBagId;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbExamDetails = tbExamDetails;
    }

   
    // Property accessors

    public Integer getNBloodBankId() {
        return this.NBloodBankId;
    }
    
    public void setNBloodBankId(Integer NBloodBankId) {
        this.NBloodBankId = NBloodBankId;
    }

    public MsBlood getMsBlood() {
        return this.msBlood;
    }
    
    public void setMsBlood(MsBlood msBlood) {
        this.msBlood = msBlood;
    }

    public String getVBloodBagId() {
        return this.VBloodBagId;
    }
    
    public void setVBloodBagId(String VBloodBagId) {
        this.VBloodBagId = VBloodBagId;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbExamDetails() {
        return this.tbExamDetails;
    }
    
    public void setTbExamDetails(Set tbExamDetails) {
        this.tbExamDetails = tbExamDetails;
    }
   








}