package com.vone.medisafe.mapping.pojo.item;

import java.util.Date;


/**
 * TbBloodExpired generated by MyEclipse - Hibernate Tools
 */

public class TbBloodExpired  implements java.io.Serializable {


    // Fields    

     private Integer nbexpId;
     private MsBlood msBlood;
     private String VBexpDesc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbBloodExpired() {
    }

    
    /** full constructor */
    public TbBloodExpired(Integer nbexpId, MsBlood msBlood, String VBexpDesc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.nbexpId = nbexpId;
        this.msBlood = msBlood;
        this.VBexpDesc = VBexpDesc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNbexpId() {
        return this.nbexpId;
    }
    
    public void setNbexpId(Integer nbexpId) {
        this.nbexpId = nbexpId;
    }

    public MsBlood getMsBlood() {
        return this.msBlood;
    }
    
    public void setMsBlood(MsBlood msBlood) {
        this.msBlood = msBlood;
    }

    public String getVBexpDesc() {
        return this.VBexpDesc;
    }
    
    public void setVBexpDesc(String VBexpDesc) {
        this.VBexpDesc = VBexpDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}