package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsBankPaymentType generated by MyEclipse - Hibernate Tools
 */

public class MsBankPaymentType  implements java.io.Serializable {


    // Fields    

     private Integer NBankPaymentTypeId;
     private MsBank msBank;
     private String VBankPaymentTypeDesc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbPatientSettlements = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsBankPaymentType() {
    }

	/** minimal constructor */
    public MsBankPaymentType(Integer NBankPaymentTypeId, String VBankPaymentTypeDesc) {
        this.NBankPaymentTypeId = NBankPaymentTypeId;
        this.VBankPaymentTypeDesc = VBankPaymentTypeDesc;
    }
    
    /** full constructor */
    public MsBankPaymentType(Integer NBankPaymentTypeId, MsBank msBank, String VBankPaymentTypeDesc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPatientSettlements) {
        this.NBankPaymentTypeId = NBankPaymentTypeId;
        this.msBank = msBank;
        this.VBankPaymentTypeDesc = VBankPaymentTypeDesc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbPatientSettlements = tbPatientSettlements;
    }

   
    // Property accessors

    public Integer getNBankPaymentTypeId() {
        return this.NBankPaymentTypeId;
    }
    
    public void setNBankPaymentTypeId(Integer NBankPaymentTypeId) {
        this.NBankPaymentTypeId = NBankPaymentTypeId;
    }

    public MsBank getMsBank() {
        return this.msBank;
    }
    
    public void setMsBank(MsBank msBank) {
        this.msBank = msBank;
    }

    public String getVBankPaymentTypeDesc() {
        return this.VBankPaymentTypeDesc;
    }
    
    public void setVBankPaymentTypeDesc(String VBankPaymentTypeDesc) {
        this.VBankPaymentTypeDesc = VBankPaymentTypeDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPatientSettlements() {
        return this.tbPatientSettlements;
    }
    
    public void setTbPatientSettlements(Set tbPatientSettlements) {
        this.tbPatientSettlements = tbPatientSettlements;
    }
   








}