package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsBank generated by MyEclipse - Hibernate Tools
 */

public class MsBank  implements java.io.Serializable {


    // Fields    

     private Integer NBankId;
     private MsCoa MsCoa;
     private String VBankName;
     private String VBankAddr;
     private String VBankContactNo;
     private String VBank2ndCtcNo;
     private String VBankAccNo;
     private String VCoaId;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msCreditCardTypes = new HashSet(0);
     private Set msBankPaymentTypes = new HashSet(0);

    // Constructors

    /** default constructor */
    public MsBank() {
    }

	/** minimal constructor */
    public MsBank(Integer NBankId, String VBankName, String VBankAccNo) {
        this.NBankId = NBankId;
        this.VBankName = VBankName;
        this.VBankAccNo = VBankAccNo;
    }
    
    /** full constructor */
    public MsBank(Integer NBankId, String VBankName, String VBankAddr, String VBankContactNo, String VBank2ndCtcNo, String VBankAccNo, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msCreditCardTypes, Set msBankPaymentTypes) {
        this.NBankId = NBankId;
        this.VBankName = VBankName;
        this.VBankAddr = VBankAddr;
        this.VBankContactNo = VBankContactNo;
        this.VBank2ndCtcNo = VBank2ndCtcNo;
        this.VBankAccNo = VBankAccNo;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msCreditCardTypes = msCreditCardTypes;
        this.msBankPaymentTypes = msBankPaymentTypes;
        
    }

   
    // Property accessors

    public MsCoa getMsCoa() {
		return MsCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		MsCoa = msCoa;
	}

	public Integer getNBankId() {
        return this.NBankId;
    }
    
    public void setNBankId(Integer NBankId) {
        this.NBankId = NBankId;
    }

    public String getVBankName() {
        return this.VBankName;
    }
    
    public void setVBankName(String VBankName) {
        this.VBankName = VBankName;
    }

    public String getVBankAddr() {
        return this.VBankAddr;
    }
    
    public void setVBankAddr(String VBankAddr) {
        this.VBankAddr = VBankAddr;
    }

    public String getVBankContactNo() {
        return this.VBankContactNo;
    }
    
    public void setVBankContactNo(String VBankContactNo) {
        this.VBankContactNo = VBankContactNo;
    }

    public String getVBank2ndCtcNo() {
        return this.VBank2ndCtcNo;
    }
    
    public void setVBank2ndCtcNo(String VBank2ndCtcNo) {
        this.VBank2ndCtcNo = VBank2ndCtcNo;
    }

    public String getVBankAccNo() {
        return this.VBankAccNo;
    }
    
    public void setVBankAccNo(String VBankAccNo) {
        this.VBankAccNo = VBankAccNo;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsCreditCardTypes() {
        return this.msCreditCardTypes;
    }
    
    public void setMsCreditCardTypes(Set msCreditCardTypes) {
        this.msCreditCardTypes = msCreditCardTypes;
    }

    public Set getMsBankPaymentTypes() {
        return this.msBankPaymentTypes;
    }
    
    public void setMsBankPaymentTypes(Set msBankPaymentTypes) {
        this.msBankPaymentTypes = msBankPaymentTypes;
    }

	public String getVCoaId() {
		return VCoaId;
	}

	public void setVCoaId(String coaId) {
		VCoaId = coaId;
	}
   








}