package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsBed generated by MyEclipse - Hibernate Tools
 */

public class MsBed  implements java.io.Serializable {


    // Fields    

     private Integer NBedId;
     private MsTreatmentClass msTreatmentClass;
     private MsCoa msCoa;
     private MsRoom msRoom;
     private String VBedCode;
     private String VBedActiveStatus;
     private String isShown;
     private String availableStatus;
     private String VBedDesc;
     private double NBedPrice;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private String VBedStatus;
     private Set tbBedOccupancies = new HashSet(0);
     private Set tbBedOccupancies_1 = new HashSet(0);
     private Set tbBedTrxes = new HashSet(0);

     
     

    // Constructors

    public String getAvailableStatus() {
		return availableStatus;
	}

	public void setAvailableStatus(String availableStatus) {
		this.availableStatus = availableStatus;
	}

	/** default constructor */
    public MsBed() {
    }

	/** minimal constructor */
    public MsBed(Integer NBedId, MsRoom msRoom, String VBedCode, String VBedDesc, double NBedPrice) {
        this.NBedId = NBedId;
        this.msRoom = msRoom;
        this.VBedCode = VBedCode;
        this.VBedDesc = VBedDesc;
        this.NBedPrice = NBedPrice;
    }
    
    /** full constructor */
    public MsBed(Integer NBedId, MsTreatmentClass msTreatmentClass, MsCoa msCoa, MsRoom msRoom, String VBedCode, String VBedDesc, double NBedPrice, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, String VBedStatus, Set tbBedOccupancies, Set tbBedOccupancies_1, Set tbBedTrxes) {
        this.NBedId = NBedId;
        this.msTreatmentClass = msTreatmentClass;
        this.msCoa = msCoa;
        this.msRoom = msRoom;
        this.VBedCode = VBedCode;
        this.VBedDesc = VBedDesc;
        this.NBedPrice = NBedPrice;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.VBedStatus = VBedStatus;
        this.tbBedOccupancies = tbBedOccupancies;
        this.tbBedOccupancies_1 = tbBedOccupancies_1;
        this.tbBedTrxes = tbBedTrxes;
    }

   
    // Property accessors
    
    
    

    public Integer getNBedId() {
        return this.NBedId;
    }
    
    public String getIsShown() {
		return isShown;
	}

	public void setIsShown(String isShown) {
		this.isShown = isShown;
	}

	public void setNBedId(Integer NBedId) {
        this.NBedId = NBedId;
    }

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

    public MsCoa getMsCoa() {
        return this.msCoa;
    }
    
    public void setMsCoa(MsCoa msCoa) {
        this.msCoa = msCoa;
    }

    public MsRoom getMsRoom() {
        return this.msRoom;
    }
    
    public void setMsRoom(MsRoom msRoom) {
        this.msRoom = msRoom;
    }

    public String getVBedCode() {
        return this.VBedCode;
    }
    
    public void setVBedCode(String VBedCode) {
        this.VBedCode = VBedCode;
    }

    public String getVBedDesc() {
        return this.VBedDesc;
    }
    
    public void setVBedDesc(String VBedDesc) {
        this.VBedDesc = VBedDesc;
    }

    public double getNBedPrice() {
        return this.NBedPrice;
    }
    
    public void setNBedPrice(double NBedPrice) {
        this.NBedPrice = NBedPrice;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVBedStatus() {
        return this.VBedStatus;
    }
    
    public void setVBedStatus(String VBedStatus) {
        this.VBedStatus = VBedStatus;
    }

    public Set getTbBedOccupancies() {
        return this.tbBedOccupancies;
    }
    
    public void setTbBedOccupancies(Set tbBedOccupancies) {
        this.tbBedOccupancies = tbBedOccupancies;
    }

    public Set getTbBedOccupancies_1() {
        return this.tbBedOccupancies_1;
    }
    
    public void setTbBedOccupancies_1(Set tbBedOccupancies_1) {
        this.tbBedOccupancies_1 = tbBedOccupancies_1;
    }

    public Set getTbBedTrxes() {
        return this.tbBedTrxes;
    }
    
    public void setTbBedTrxes(Set tbBedTrxes) {
        this.tbBedTrxes = tbBedTrxes;
    }

	public String getVBedActiveStatus() {
		return VBedActiveStatus;
	}

	public void setVBedActiveStatus(String bedActiveStatus) {
		VBedActiveStatus = bedActiveStatus;
	}
   








}