package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsBranch generated by MyEclipse - Hibernate Tools
 */

public class MsBranch  implements java.io.Serializable {


    // Fields    

     private Integer NBranchId;
     private String VBranchName;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhoupdate;
     private Date DWhnupdate;
     private Set msUsers = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsBranch() {
    }

	/** minimal constructor */
    public MsBranch(Integer NBranchId) {
        this.NBranchId = NBranchId;
    }
    
    /** full constructor */
    public MsBranch(Integer NBranchId, String VBranchName, String VWhocreate, Date DWhncreate, String VWhoupdate, Date DWhnupdate, Set msUsers) {
        this.NBranchId = NBranchId;
        this.VBranchName = VBranchName;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhoupdate = VWhoupdate;
        this.DWhnupdate = DWhnupdate;
        this.msUsers = msUsers;
    }

   
    // Property accessors

    public Integer getNBranchId() {
        return this.NBranchId;
    }
    
    public void setNBranchId(Integer NBranchId) {
        this.NBranchId = NBranchId;
    }

    public String getVBranchName() {
        return this.VBranchName;
    }
    
    public void setVBranchName(String VBranchName) {
        this.VBranchName = VBranchName;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhoupdate() {
        return this.VWhoupdate;
    }
    
    public void setVWhoupdate(String VWhoupdate) {
        this.VWhoupdate = VWhoupdate;
    }

    public Date getDWhnupdate() {
        return this.DWhnupdate;
    }
    
    public void setDWhnupdate(Date DWhnupdate) {
        this.DWhnupdate = DWhnupdate;
    }

    public Set getMsUsers() {
        return this.msUsers;
    }
    
    public void setMsUsers(Set msUsers) {
        this.msUsers = msUsers;
    }
   








}