package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsBranchId generated by MyEclipse - Hibernate Tools
 */

public class MsBranchId  implements java.io.Serializable {


    // Fields    

     private Integer NBranchId;
     private String VBranchName;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhoupdate;
     private Date DWhnupdate;


    // Constructors

    /** default constructor */
    public MsBranchId() {
    }

	/** minimal constructor */
    public MsBranchId(Integer NBranchId) {
        this.NBranchId = NBranchId;
    }
    
    /** full constructor */
    public MsBranchId(Integer NBranchId, String VBranchName, String VWhocreate, Date DWhncreate, String VWhoupdate, Date DWhnupdate) {
        this.NBranchId = NBranchId;
        this.VBranchName = VBranchName;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhoupdate = VWhoupdate;
        this.DWhnupdate = DWhnupdate;
    }
    

   
    // Property accessors

    public Integer getNBranchId() {
        return this.NBranchId;
    }
    
    public void setNBranchId(Integer NBranchId) {
        this.NBranchId = NBranchId;
    }

    public String getVBranchName() {
        return this.VBranchName;
    }
    
    public void setVBranchName(String VBranchName) {
        this.VBranchName = VBranchName;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhoupdate() {
        return this.VWhoupdate;
    }
    
    public void setVWhoupdate(String VWhoupdate) {
        this.VWhoupdate = VWhoupdate;
    }

    public Date getDWhnupdate() {
        return this.DWhnupdate;
    }
    
    public void setDWhnupdate(Date DWhnupdate) {
        this.DWhnupdate = DWhnupdate;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsBranchId) ) return false;
		 MsBranchId castOther = ( MsBranchId ) other; 
         
		 return ( (this.getNBranchId()==castOther.getNBranchId()) || ( this.getNBranchId()!=null && castOther.getNBranchId()!=null && this.getNBranchId().equals(castOther.getNBranchId()) ) )
 && ( (this.getVBranchName()==castOther.getVBranchName()) || ( this.getVBranchName()!=null && castOther.getVBranchName()!=null && this.getVBranchName().equals(castOther.getVBranchName()) ) )
 && ( (this.getVWhocreate()==castOther.getVWhocreate()) || ( this.getVWhocreate()!=null && castOther.getVWhocreate()!=null && this.getVWhocreate().equals(castOther.getVWhocreate()) ) )
 && ( (this.getDWhncreate()==castOther.getDWhncreate()) || ( this.getDWhncreate()!=null && castOther.getDWhncreate()!=null && this.getDWhncreate().equals(castOther.getDWhncreate()) ) )
 && ( (this.getVWhoupdate()==castOther.getVWhoupdate()) || ( this.getVWhoupdate()!=null && castOther.getVWhoupdate()!=null && this.getVWhoupdate().equals(castOther.getVWhoupdate()) ) )
 && ( (this.getDWhnupdate()==castOther.getDWhnupdate()) || ( this.getDWhnupdate()!=null && castOther.getDWhnupdate()!=null && this.getDWhnupdate().equals(castOther.getDWhnupdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNBranchId() == null ? 0 : this.getNBranchId().hashCode() );
         result = 37 * result + ( getVBranchName() == null ? 0 : this.getVBranchName().hashCode() );
         result = 37 * result + ( getVWhocreate() == null ? 0 : this.getVWhocreate().hashCode() );
         result = 37 * result + ( getDWhncreate() == null ? 0 : this.getDWhncreate().hashCode() );
         result = 37 * result + ( getVWhoupdate() == null ? 0 : this.getVWhoupdate().hashCode() );
         result = 37 * result + ( getDWhnupdate() == null ? 0 : this.getDWhnupdate().hashCode() );
         return result;
   }   





}