package com.vone.medisafe.mapping;

import java.util.HashSet;
import java.util.Set;


/**
 * MsCoaType generated by MyEclipse - Hibernate Tools
 */

public class MsCoaType  implements java.io.Serializable {


    // Fields    

     private Integer NCtId;
     private String VCtName;
     private short NCtNaturalBalance;
     private Set msCoas = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsCoaType() {
    }

	/** minimal constructor */
    public MsCoaType(String VCtName, short NCtNaturalBalance) {
        this.VCtName = VCtName;
        this.NCtNaturalBalance = NCtNaturalBalance;
    }
    
    /** full constructor */
    public MsCoaType(String VCtName, short NCtNaturalBalance, Set msCoas) {
        this.VCtName = VCtName;
        this.NCtNaturalBalance = NCtNaturalBalance;
        this.msCoas = msCoas;
    }

   
    // Property accessors

    public Integer getNCtId() {
        return this.NCtId;
    }
    
    public void setNCtId(Integer NCtId) {
        this.NCtId = NCtId;
    }

    public String getVCtName() {
        return this.VCtName;
    }
    
    public void setVCtName(String VCtName) {
        this.VCtName = VCtName;
    }

    public short getNCtNaturalBalance() {
        return this.NCtNaturalBalance;
    }
    
    public void setNCtNaturalBalance(short NCtNaturalBalance) {
        this.NCtNaturalBalance = NCtNaturalBalance;
    }

    public Set getMsCoas() {
        return this.msCoas;
    }
    
    public void setMsCoas(Set msCoas) {
        this.msCoas = msCoas;
    }
   








}