package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsCoa generated by MyEclipse - Hibernate Tools
 */

public class MsCoa  implements java.io.Serializable {


    // Fields    

     private Integer NCoaId;
     private MsCoa msCoa;
     private String VAcctNo;
     private String VDesc;
     private String VAcctName;
     //private short NType;
     private MsCoaType msCoaType; 
     private Float NBalance;
     private Short NNaturalBalance;
     private Short NStatus;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;   
     private Set msCoas = new HashSet(0);
     private Set msItemsForNItemSellAccNo = new HashSet(0);
     private Set msItemsForNItemInvAccNo = new HashSet(0);
     private Set msItemsForNItemCogsNo = new HashSet(0);
     private Set msBank = new HashSet(0);
     private Set msInsurance = new HashSet(0);

    // Constructors

    /** default constructor */
    public MsCoa() {
    }

	/** minimal constructor */
    public MsCoa(Integer NCoaId) {
        this.NCoaId = NCoaId;
    }
    
    /** full constructor */
    public MsCoa(Integer NCoaId, MsCoa msCoa, String VAcctNo, String VDesc, short NType, Float NBalance, Short NNaturalBalance, Short NStatus, Set msCoas, Set msItemsForNItemSellAccNo, Set msItemsForNItemInvAccNo, Set msItemsForNItemCogsNo) {
        this.NCoaId = NCoaId;
        this.msCoa = msCoa;
        this.VAcctNo = VAcctNo;
        this.VDesc = VDesc;
        this.NBalance = NBalance;
        this.NNaturalBalance = NNaturalBalance;
        this.NStatus = NStatus;
        this.msCoas = msCoas;
        this.msItemsForNItemSellAccNo = msItemsForNItemSellAccNo;
        this.msItemsForNItemInvAccNo = msItemsForNItemInvAccNo;
        this.msItemsForNItemCogsNo = msItemsForNItemCogsNo;
    }

   
    // Property accessors

    public Integer getNCoaId() {
        return this.NCoaId;
    }
    
    public void setNCoaId(Integer NCoaId) {
        this.NCoaId = NCoaId;
    }

    public MsCoa getMsCoa() {
        return this.msCoa;
    }
    
    public void setMsCoa(MsCoa msCoa) {
        this.msCoa = msCoa;
    }

    public String getVAcctNo() {
        return this.VAcctNo;
    }
    
    public void setVAcctNo(String VAcctNo) {
        this.VAcctNo = VAcctNo;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public Float getNBalance() {
        return this.NBalance;
    }
    
    public void setNBalance(Float NBalance) {
        this.NBalance = NBalance;
    }

    public Short getNNaturalBalance() {
        return this.NNaturalBalance;
    }
    
    public void setNNaturalBalance(Short NNaturalBalance) {
        this.NNaturalBalance = NNaturalBalance;
    }

    public Short getNStatus() {
        return this.NStatus;
    }
    
    public void setNStatus(Short NStatus) {
        this.NStatus = NStatus;
    }

    public Set getMsCoas() {
        return this.msCoas;
    }
    
    public void setMsCoas(Set msCoas) {
        this.msCoas = msCoas;
    }

    public Set getMsItemsForNItemSellAccNo() {
        return this.msItemsForNItemSellAccNo;
    }
    
    public void setMsItemsForNItemSellAccNo(Set msItemsForNItemSellAccNo) {
        this.msItemsForNItemSellAccNo = msItemsForNItemSellAccNo;
    }

    public Set getMsItemsForNItemInvAccNo() {
        return this.msItemsForNItemInvAccNo;
    }
    
    public void setMsItemsForNItemInvAccNo(Set msItemsForNItemInvAccNo) {
        this.msItemsForNItemInvAccNo = msItemsForNItemInvAccNo;
    }

    public Set getMsItemsForNItemCogsNo() {
        return this.msItemsForNItemCogsNo;
    }
    
    public void setMsItemsForNItemCogsNo(Set msItemsForNItemCogsNo) {
        this.msItemsForNItemCogsNo = msItemsForNItemCogsNo;
    }

	public Set getMsBank() {
		return msBank;
	}

	public void setMsBank(Set msBank) {
		this.msBank = msBank;
	}

	public Set getMsInsurance() {
		return msInsurance;
	}

	public void setMsInsurance(Set msInsurance) {
		this.msInsurance = msInsurance;
	}

	public String getVAcctName() {
		return VAcctName;
	}

	public void setVAcctName(String acctName) {
		VAcctName = acctName;
	}

	public Date getDWhnChange() {
		return DWhnChange;
	}

	public void setDWhnChange(Date whnChange) {
		DWhnChange = whnChange;
	}

	public Date getDWhnCreate() {
		return DWhnCreate;
	}

	public void setDWhnCreate(Date whnCreate) {
		DWhnCreate = whnCreate;
	}

	public String getVWhoChange() {
		return VWhoChange;
	}

	public void setVWhoChange(String whoChange) {
		VWhoChange = whoChange;
	}

	public String getVWhoCreate() {
		return VWhoCreate;
	}

	public void setVWhoCreate(String whoCreate) {
		VWhoCreate = whoCreate;
	}

	public MsCoaType getMsCoaType() {
		return msCoaType;
	}

	public void setMsCoaType(MsCoaType msCoaType) {
		this.msCoaType = msCoaType;
	}









}