package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsCreditCardType generated by MyEclipse - Hibernate Tools
 */

public class MsCreditCardType  implements java.io.Serializable {


    // Fields    

     private Integer NCcTypeId;
     private Short NPaymentType;
     private MsBank msBank;
     private MsCoa msCoa;
     private String NCcTypeDesc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbPatientSettlements = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsCreditCardType() {
    }

	/** minimal constructor */
   

   
    // Property accessors

    public Integer getNCcTypeId() {
        return this.NCcTypeId;
    }
    
    public void setNCcTypeId(Integer NCcTypeId) {
        this.NCcTypeId = NCcTypeId;
    }

    public Short getNPaymentType() {
        return this.NPaymentType;
    }
    
    public void setNPaymentType(Short msBankPaymentType) {
        this.NPaymentType = msBankPaymentType;
    }

    public MsBank getMsBank() {
        return this.msBank;
    }
    
    public void setMsBank(MsBank msBank) {
        this.msBank = msBank;
    }

    public MsCoa getMsCoa() {
        return this.msCoa;
    }
    
    public void setMsCoa(MsCoa msCoa) {
        this.msCoa = msCoa;
    }

    public String getNCcTypeDesc() {
        return this.NCcTypeDesc;
    }
    
    public void setNCcTypeDesc(String NCcTypeDesc) {
        this.NCcTypeDesc = NCcTypeDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPatientSettlements() {
        return this.tbPatientSettlements;
    }
    
    public void setTbPatientSettlements(Set tbPatientSettlements) {
        this.tbPatientSettlements = tbPatientSettlements;
    }
   








}