package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsDivision generated by MyEclipse - Hibernate Tools
 */

public class MsDivision  implements java.io.Serializable {


    // Fields    

     private Integer NDivisionId;
     private String VDivisionCode;
     private String VDivisionName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbRegistrations = new HashSet(0);
     private Set msUnits = new HashSet(0);
     private Integer NRegistrationCharge;
     private String VRegistrationUnit;


    // Constructors

    public Integer getNRegistrationCharge() {
		return NRegistrationCharge;
	}

	public void setNRegistrationCharge(Integer nRegistrationCharge) {
		NRegistrationCharge = nRegistrationCharge;
	}

	public String getVRegistrationUnit() {
		return VRegistrationUnit;
	}

	public void setVRegistrationUnit(String vRegistrationUnit) {
		VRegistrationUnit = vRegistrationUnit;
	}

	/** default constructor */
    public MsDivision() {
    }

	/** minimal constructor */
    public MsDivision(Integer NDivisionId, String VDivisionCode, String VDivisionName) {
        this.NDivisionId = NDivisionId;
        this.VDivisionCode = VDivisionCode;
        this.VDivisionName = VDivisionName;
    }
    
    /** full constructor */
    public MsDivision(Integer NDivisionId, String VDivisionCode, String VDivisionName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbRegistrations, Set msUnits, Integer charge, String clasification) {
        this.NDivisionId = NDivisionId;
        this.VDivisionCode = VDivisionCode;
        this.VDivisionName = VDivisionName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbRegistrations = tbRegistrations;
        this.msUnits = msUnits;
        this.NRegistrationCharge = charge;
        this.VRegistrationUnit = clasification;
    }

   
    // Property accessors

    public Integer getNDivisionId() {
        return this.NDivisionId;
    }
    
    public void setNDivisionId(Integer NDivisionId) {
        this.NDivisionId = NDivisionId;
    }

    public String getVDivisionCode() {
        return this.VDivisionCode;
    }
    
    public void setVDivisionCode(String VDivisionCode) {
        this.VDivisionCode = VDivisionCode;
    }

    public String getVDivisionName() {
        return this.VDivisionName;
    }
    
    public void setVDivisionName(String VDivisionName) {
        this.VDivisionName = VDivisionName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbRegistrations() {
        return this.tbRegistrations;
    }
    
    public void setTbRegistrations(Set tbRegistrations) {
        this.tbRegistrations = tbRegistrations;
    }

    public Set getMsUnits() {
        return this.msUnits;
    }
    
    public void setMsUnits(Set msUnits) {
        this.msUnits = msUnits;
    }
   








}