package com.vone.medisafe.mapping;



/**
 * MsDoctorRule generated by MyEclipse - Hibernate Tools
 */

public class MsDoctorRule  implements java.io.Serializable {


    // Fields    

     private Integer NRuleId;
     private int NRsPersen;
     private String VRule;
     private Integer NUnitId;
     private Integer NShiftId;
     private String VDocStatus;
     private Integer NPriority;
//     private MsUnit msUnit;
//     private MsShift msShift;


    // Constructors

    /** default constructor */
    public MsDoctorRule() {
    }

    
    /** full constructor */
    public MsDoctorRule(short NRsPersen, String VRule, Integer NUnitId, Integer NShiftId, String VDocStatus, Integer NPriority) {
        this.NRsPersen = NRsPersen;
        this.VRule = VRule;
        this.VDocStatus = VDocStatus;
        this.NPriority = NPriority;
    }

   
    // Property accessors

    public Integer getNRuleId() {
        return this.NRuleId;
    }
    
    public void setNRuleId(Integer NRuleId) {
        this.NRuleId = NRuleId;
    }

    public int getNRsPersen() {
        return this.NRsPersen;
    }
    
    public void setNRsPersen(int NRsPersen) {
        this.NRsPersen = NRsPersen;
    }

    public String getVRule() {
        return this.VRule;
    }
    
    public void setVRule(String VRule) {
        this.VRule = VRule;
    }

    public Integer getNUnitId() {
        return this.NUnitId;
    }
    
    public void setNUnitId(Integer NUnitId) {
        this.NUnitId = NUnitId;
    }

    public Integer getNShiftId() {
        return this.NShiftId;
    }
    
    public void setNShiftId(Integer NShiftId) {
        this.NShiftId = NShiftId;
    }

    public String getVDocStatus() {
        return this.VDocStatus;
    }
    
    public void setVDocStatus(String VDocStatus) {
        this.VDocStatus = VDocStatus;
    }

    public Integer getNPriority() {
        return this.NPriority;
    }
    
    public void setNPriority(Integer NPriority) {
        this.NPriority = NPriority;
    }


//	public MsShift getMsShift() {
//		return msShift;
//	}
//
//
//	public void setMsShift(MsShift msShift) {
//		this.msShift = msShift;
//	}
//
//
//	public MsUnit getMsUnit() {
//		return msUnit;
//	}
//
//
//	public void setMsUnit(MsUnit msUnit) {
//		this.msUnit = msUnit;
//	}
   








}