package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsGroup generated by MyEclipse - Hibernate Tools
 */

public class MsGim  implements java.io.Serializable {


    // Fields    

     private Integer NGimId;
     private String VKey;
     private String VValue;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public MsGim() {
    }


	public Date getDWhnChange() {
		return DWhnChange;
	}


	public void setDWhnChange(Date whnChange) {
		DWhnChange = whnChange;
	}


	public Date getDWhnCreate() {
		return DWhnCreate;
	}


	public void setDWhnCreate(Date whnCreate) {
		DWhnCreate = whnCreate;
	}


	public Integer getNGimId() {
		return NGimId;
	}


	public void setNGimId(Integer gimId) {
		NGimId = gimId;
	}


	public String getVKey() {
		return VKey;
	}


	public void setVKey(String key) {
		VKey = key;
	}


	public String getVValue() {
		return VValue;
	}


	public void setVValue(String value) {
		VValue = value;
	}


	public String getVWhoChange() {
		return VWhoChange;
	}


	public void setVWhoChange(String whoChange) {
		VWhoChange = whoChange;
	}


	public String getVWhoCreate() {
		return VWhoCreate;
	}


	public void setVWhoCreate(String whoCreate) {
		VWhoCreate = whoCreate;
	}

    // Property accessors

}