package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsGroupId generated by MyEclipse - Hibernate Tools
 */

public class MsGroupId  implements java.io.Serializable {


    // Fields    

     private Integer NGroupId;
     private String VGroupName;
     private String VDesc;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchg;


    // Constructors

    /** default constructor */
    public MsGroupId() {
    }

	/** minimal constructor */
    public MsGroupId(Integer NGroupId) {
        this.NGroupId = NGroupId;
    }
    
    /** full constructor */
    public MsGroupId(Integer NGroupId, String VGroupName, String VDesc, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchg) {
        this.NGroupId = NGroupId;
        this.VGroupName = VGroupName;
        this.VDesc = VDesc;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchg = DWhnchg;
    }
    

   
    // Property accessors

    public Integer getNGroupId() {
        return this.NGroupId;
    }
    
    public void setNGroupId(Integer NGroupId) {
        this.NGroupId = NGroupId;
    }

    public String getVGroupName() {
        return this.VGroupName;
    }
    
    public void setVGroupName(String VGroupName) {
        this.VGroupName = VGroupName;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchg() {
        return this.DWhnchg;
    }
    
    public void setDWhnchg(Date DWhnchg) {
        this.DWhnchg = DWhnchg;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsGroupId) ) return false;
		 MsGroupId castOther = ( MsGroupId ) other; 
         
		 return ( (this.getNGroupId()==castOther.getNGroupId()) || ( this.getNGroupId()!=null && castOther.getNGroupId()!=null && this.getNGroupId().equals(castOther.getNGroupId()) ) )
 && ( (this.getVGroupName()==castOther.getVGroupName()) || ( this.getVGroupName()!=null && castOther.getVGroupName()!=null && this.getVGroupName().equals(castOther.getVGroupName()) ) )
 && ( (this.getVDesc()==castOther.getVDesc()) || ( this.getVDesc()!=null && castOther.getVDesc()!=null && this.getVDesc().equals(castOther.getVDesc()) ) )
 && ( (this.getVWhocreate()==castOther.getVWhocreate()) || ( this.getVWhocreate()!=null && castOther.getVWhocreate()!=null && this.getVWhocreate().equals(castOther.getVWhocreate()) ) )
 && ( (this.getDWhncreate()==castOther.getDWhncreate()) || ( this.getDWhncreate()!=null && castOther.getDWhncreate()!=null && this.getDWhncreate().equals(castOther.getDWhncreate()) ) )
 && ( (this.getVWhochange()==castOther.getVWhochange()) || ( this.getVWhochange()!=null && castOther.getVWhochange()!=null && this.getVWhochange().equals(castOther.getVWhochange()) ) )
 && ( (this.getDWhnchg()==castOther.getDWhnchg()) || ( this.getDWhnchg()!=null && castOther.getDWhnchg()!=null && this.getDWhnchg().equals(castOther.getDWhnchg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNGroupId() == null ? 0 : this.getNGroupId().hashCode() );
         result = 37 * result + ( getVGroupName() == null ? 0 : this.getVGroupName().hashCode() );
         result = 37 * result + ( getVDesc() == null ? 0 : this.getVDesc().hashCode() );
         result = 37 * result + ( getVWhocreate() == null ? 0 : this.getVWhocreate().hashCode() );
         result = 37 * result + ( getDWhncreate() == null ? 0 : this.getDWhncreate().hashCode() );
         result = 37 * result + ( getVWhochange() == null ? 0 : this.getVWhochange().hashCode() );
         result = 37 * result + ( getDWhnchg() == null ? 0 : this.getDWhnchg().hashCode() );
         return result;
   }   





}