package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsGroup generated by MyEclipse - Hibernate Tools
 */

public class MsGroup  implements java.io.Serializable {


    // Fields    

     private Integer NGroupId;
     private String VGroupName;
     private String VDesc;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchg;
     private Set msUsers = new HashSet(0);
     private Set tbGroupPrivileges = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsGroup() {
    }

	/** minimal constructor */
    public MsGroup(Integer NGroupId) {
        this.NGroupId = NGroupId;
    }
    
    /** full constructor */
    public MsGroup(Integer NGroupId, String VGroupName, String VDesc, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchg, Set msUsers, Set tbGroupPrivileges) {
        this.NGroupId = NGroupId;
        this.VGroupName = VGroupName;
        this.VDesc = VDesc;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchg = DWhnchg;
        this.msUsers = msUsers;
        this.tbGroupPrivileges = tbGroupPrivileges;
    }

   
    // Property accessors

    public Integer getNGroupId() {
        return this.NGroupId;
    }
    
    public void setNGroupId(Integer NGroupId) {
        this.NGroupId = NGroupId;
    }

    public String getVGroupName() {
        return this.VGroupName;
    }
    
    public void setVGroupName(String VGroupName) {
        this.VGroupName = VGroupName;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchg() {
        return this.DWhnchg;
    }
    
    public void setDWhnchg(Date DWhnchg) {
        this.DWhnchg = DWhnchg;
    }

    public Set getMsUsers() {
        return this.msUsers;
    }
    
    public void setMsUsers(Set msUsers) {
        this.msUsers = msUsers;
    }

    public Set getTbGroupPrivileges() {
        return this.tbGroupPrivileges;
    }
    
    public void setTbGroupPrivileges(Set tbGroupPrivileges) {
        this.tbGroupPrivileges = tbGroupPrivileges;
    }
   








}