package com.vone.medisafe.mapping;



/**
 * MsHallId generated by MyEclipse - Hibernate Tools
 */

public class MsHallId  implements java.io.Serializable {


    // Fields    

     private MsTreatmentClass msTreatmentClass;
     private MsWard msWard;


    // Constructors

    /** default constructor */
    public MsHallId() {
    }

    
    /** full constructor */
    public MsHallId(MsTreatmentClass msTreatmentClass, MsWard msWard) {
        this.msTreatmentClass = msTreatmentClass;
        this.msWard = msWard;
    }
    

   
    // Property accessors

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

    public MsWard getMsWard() {
        return this.msWard;
    }
    
    public void setMsWard(MsWard msWard) {
        this.msWard = msWard;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsHallId) ) return false;
		 MsHallId castOther = ( MsHallId ) other; 
         
		 return ( (this.getMsTreatmentClass()==castOther.getMsTreatmentClass()) || ( this.getMsTreatmentClass()!=null && castOther.getMsTreatmentClass()!=null && this.getMsTreatmentClass().equals(castOther.getMsTreatmentClass()) ) )
 && ( (this.getMsWard()==castOther.getMsWard()) || ( this.getMsWard()!=null && castOther.getMsWard()!=null && this.getMsWard().equals(castOther.getMsWard()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsTreatmentClass() == null ? 0 : this.getMsTreatmentClass().hashCode() );
         result = 37 * result + ( getMsWard() == null ? 0 : this.getMsWard().hashCode() );
         return result;
   }   





}