package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsInsurance generated by MyEclipse - Hibernate Tools
 */

public class MsInsurance  implements java.io.Serializable {


    // Fields    

     private Integer NInsuranceId;
     private MsCoa msCoa;
     private String VInsuranceName;
     private String VInsuranceAddr;
     private String VInsurancePhNo;
     private String VInsuranceDesc;
     private short NActiveStatus;
     private Date DDateEndOfPartnership;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbPatientBills = new HashSet(0);
     private Set tbPatientBillDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsInsurance() {
    }

	/** minimal constructor */
    public MsInsurance(Integer NInsuranceId) {
        this.NInsuranceId = NInsuranceId;
    }
    
    /** full constructor */
    public MsInsurance(Integer NInsuranceId, String VInsuranceName, String VInsuranceAddr, String VInsurancePhNo, String VInsuranceDesc, short NActiveStatus, Date DDateEndOfPartnership, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPatientBills, Set tbPatientBillDetails) {
        this.NInsuranceId = NInsuranceId;
        this.VInsuranceName = VInsuranceName;
        this.VInsuranceAddr = VInsuranceAddr;
        this.VInsurancePhNo = VInsurancePhNo;
        this.VInsuranceDesc = VInsuranceDesc;
        this.NActiveStatus = NActiveStatus;
        this.DDateEndOfPartnership = DDateEndOfPartnership;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbPatientBills = tbPatientBills;
        this.tbPatientBillDetails = tbPatientBillDetails;
    }

   
    // Property accessors

    public Integer getNInsuranceId() {
        return this.NInsuranceId;
    }
    
    public void setNInsuranceId(Integer NInsuranceId) {
        this.NInsuranceId = NInsuranceId;
    }

    public String getVInsuranceName() {
        return this.VInsuranceName;
    }
    
    public MsCoa getMsCoa() {
		return msCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		this.msCoa = msCoa;
	}

	public void setVInsuranceName(String VInsuranceName) {
        this.VInsuranceName = VInsuranceName;
    }

    public String getVInsuranceAddr() {
        return this.VInsuranceAddr;
    }
    
    public void setVInsuranceAddr(String VInsuranceAddr) {
        this.VInsuranceAddr = VInsuranceAddr;
    }

    public String getVInsurancePhNo() {
        return this.VInsurancePhNo;
    }
    
    public void setVInsurancePhNo(String VInsurancePhNo) {
        this.VInsurancePhNo = VInsurancePhNo;
    }

    public String getVInsuranceDesc() {
        return this.VInsuranceDesc;
    }
    
    public void setVInsuranceDesc(String VInsuranceDesc) {
        this.VInsuranceDesc = VInsuranceDesc;
    }


    public short getNActiveStatus() {
		return NActiveStatus;
	}

	public void setNActiveStatus(short activeStatus) {
		NActiveStatus = activeStatus;
	}

	public Date getDDateEndOfPartnership() {
        return this.DDateEndOfPartnership;
    }
    
    public void setDDateEndOfPartnership(Date DDateEndOfPartnership) {
        this.DDateEndOfPartnership = DDateEndOfPartnership;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPatientBills() {
        return this.tbPatientBills;
    }
    
    public void setTbPatientBills(Set tbPatientBills) {
        this.tbPatientBills = tbPatientBills;
    }

    public Set getTbPatientBillDetails() {
        return this.tbPatientBillDetails;
    }
    
    public void setTbPatientBillDetails(Set tbPatientBillDetails) {
        this.tbPatientBillDetails = tbPatientBillDetails;
    }
   








}