package com.vone.medisafe.mapping;
// default package

import java.util.Date;


/**
 * MsLabTreatmentDetil generated by MyEclipse - Hibernate Tools
 */

public class MsLabTreatmentDetil  implements java.io.Serializable {


    // Fields    

     private Integer NLabDetilId;
     //private long NTreatmentId;
     private MsTreatment MsTreatment;
     private String VDetailName;
     private String VQuantify;
     private String VNormalRange;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public MsLabTreatmentDetil() {
    }

    
    /** full constructor */
    public MsLabTreatmentDetil(long NTreatmentId, String VDetailName, String VQuantify, String VNormalRange, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange) {
        this.VDetailName = VDetailName;
        this.VQuantify = VQuantify;
        this.VNormalRange = VNormalRange;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNLabDetilId() {
        return this.NLabDetilId;
    }
    
    public void setNLabDetilId(Integer NLabDetilId) {
        this.NLabDetilId = NLabDetilId;
    }

    public String getVDetailName() {
        return this.VDetailName;
    }
    
    public void setVDetailName(String VDetailName) {
        this.VDetailName = VDetailName;
    }

    public String getVQuantify() {
        return this.VQuantify;
    }
    
    public void setVQuantify(String VQuantify) {
        this.VQuantify = VQuantify;
    }

    public String getVNormalRange() {
        return this.VNormalRange;
    }
    
    public void setVNormalRange(String VNormalRange) {
        this.VNormalRange = VNormalRange;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }


	public MsTreatment getMsTreatment() {
		return MsTreatment;
	}


	public void setMsTreatment(MsTreatment msTreatment) {
		MsTreatment = msTreatment;
	}
   








}