package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsMedicStaffGroup generated by MyEclipse - Hibernate Tools
 */

public class MsMedicStaffGroup  implements java.io.Serializable {


    // Fields    

     private Integer NMsgroupId;
     private String VMsgroupCode;
     private String VMsgroupName;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private Set msDoctors = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsMedicStaffGroup() {
    }

	/** minimal constructor */
    public MsMedicStaffGroup(Integer NMsgroupId, String VMsgroupCode, String VMsgroupName) {
        this.NMsgroupId = NMsgroupId;
        this.VMsgroupCode = VMsgroupCode;
        this.VMsgroupName = VMsgroupName;
    }
    
    /** full constructor */
    public MsMedicStaffGroup(Integer NMsgroupId, String VMsgroupCode, String VMsgroupName, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange, Set msDoctors) {
        this.NMsgroupId = NMsgroupId;
        this.VMsgroupCode = VMsgroupCode;
        this.VMsgroupName = VMsgroupName;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.msDoctors = msDoctors;
    }

   
    // Property accessors

    public Integer getNMsgroupId() {
        return this.NMsgroupId;
    }
    
    public void setNMsgroupId(Integer NMsgroupId) {
        this.NMsgroupId = NMsgroupId;
    }

    public String getVMsgroupCode() {
        return this.VMsgroupCode;
    }
    
    public void setVMsgroupCode(String VMsgroupCode) {
        this.VMsgroupCode = VMsgroupCode;
    }

    public String getVMsgroupName() {
        return this.VMsgroupName;
    }
    
    public void setVMsgroupName(String VMsgroupName) {
        this.VMsgroupName = VMsgroupName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsDoctors() {
        return this.msDoctors;
    }
    
    public void setMsDoctors(Set msDoctors) {
        this.msDoctors = msDoctors;
    }
   








}