package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsPatientEscort generated by MyEclipse - Hibernate Tools
 */

public class MsPatientEscort  implements java.io.Serializable {


    // Fields    

     private Integer NEscortPrimaryId;
     private String VEscortCode;
     private String VEscortType;
     private double NEscortCommission;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbExaminations = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsPatientEscort() {
    }

	/** minimal constructor */
    public MsPatientEscort(Integer NEscortPrimaryId, String VEscortCode, String VEscortType, double NEscortCommission) {
        this.NEscortPrimaryId = NEscortPrimaryId;
        this.VEscortCode = VEscortCode;
        this.VEscortType = VEscortType;
        this.NEscortCommission = NEscortCommission;
    }
    
    /** full constructor */
    public MsPatientEscort(Integer NEscortPrimaryId, String VEscortCode, String VEscortType, double NEscortCommission, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbExaminations) {
        this.NEscortPrimaryId = NEscortPrimaryId;
        this.VEscortCode = VEscortCode;
        this.VEscortType = VEscortType;
        this.NEscortCommission = NEscortCommission;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbExaminations = tbExaminations;
    }

   
    // Property accessors

    public Integer getNEscortPrimaryId() {
        return this.NEscortPrimaryId;
    }
    
    public void setNEscortPrimaryId(Integer NEscortPrimaryId) {
        this.NEscortPrimaryId = NEscortPrimaryId;
    }

    public String getVEscortCode() {
        return this.VEscortCode;
    }
    
    public void setVEscortCode(String VEscortCode) {
        this.VEscortCode = VEscortCode;
    }

    public String getVEscortType() {
        return this.VEscortType;
    }
    
    public void setVEscortType(String VEscortType) {
        this.VEscortType = VEscortType;
    }

    public double getNEscortCommission() {
        return this.NEscortCommission;
    }
    
    public void setNEscortCommission(double NEscortCommission) {
        this.NEscortCommission = NEscortCommission;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbExaminations() {
        return this.tbExaminations;
    }
    
    public void setTbExaminations(Set tbExaminations) {
        this.tbExaminations = tbExaminations;
    }
   








}