package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsPatient generated by MyEclipse - Hibernate Tools
 */

public class MsPatient  implements java.io.Serializable {


    // Fields    

     private Integer NPatientId;
     private MsVillage msVillage;
     private MsSubDistrict msSubDistrict;
     private MsRegency msRegency;
     private MsPatientType msPatientType;
     private MsProvince msProvince;
     private String VPatientName;
     private String VPatientMaritalStatus;
     private String VPatientGender;
     private Date DPatientDob;
     private short VPatientAge;
     private String VPatientReligion;
     private String VPatientEdu;
     private String VPatientJobType;
     private String VPatientMainAddr;
     private String VPatientMainRtRw;
     private String VPatientMainPhNo;
     private String VPatientAltAddr;
     private String VPatientAltRtRw;
     private String VPatientAltPhNo;
     private String VPatientNationality;
     private String VPatientPriority;
     private String VWhoCreate;
     private String VWhoChange;
     private String VEtnis;
     private String VLanguage;
     private Date DWhnCreate;
     private Date DWhnChange;
     private Set tbExaminations = new HashSet(0);
     private Set tbMedicalRecords = new HashSet(0);
     
//     private String VPatientMotherName;
//     private String VPatientPartnerName;


    // Constructors
/**
    public String getVPatientMotherName() {
		return this.VPatientMotherName;
	}

	public void setVPatientMotherName(String vPatientMohterName) {
		VPatientMotherName = vPatientMohterName;
	}

	public String getVPatientPartnerName() {
		return this.VPatientPartnerName;
	}

	public void setVPatientPartnerName(String vPatientPartnerName) {
		VPatientPartnerName = vPatientPartnerName;
	}
*/
	/** default constructor */
    public MsPatient() {
    }

	/** minimal constructor */
    public MsPatient(Integer NPatientId, String VPatientName, String VPatientGender, Date DPatientDob, String VPatientMainAddr) {
        this.NPatientId = NPatientId;
        this.VPatientName = VPatientName;
        this.VPatientGender = VPatientGender;
        this.DPatientDob = DPatientDob;
        this.VPatientMainAddr = VPatientMainAddr;
    }
    
    /** full constructor */
    public MsPatient(Integer NPatientId, MsVillage msVillage, MsSubDistrict msSubDistrict, MsRegency msRegency, MsPatientType msPatientType, MsProvince msProvince, String VPatientName, String VPatientMaritalStatus, String VPatientGender, Date DPatientDob, short VPatientAge, String VPatientReligion, String VPatientEdu, String VPatientJobType, String VPatientMainAddr, String VPatientMainRtRw, String VPatientMainPhNo, String VPatientAltAddr, String VPatientAltRtRw, String VPatientAltPhNo, String VPatientNationality, String VPatientPriority, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange, Set tbExaminations, Set tbMedicalRecords, String motherName, String parterName) {
        this.NPatientId = NPatientId;
        this.msVillage = msVillage;
        this.msSubDistrict = msSubDistrict;
        this.msRegency = msRegency;
        this.msPatientType = msPatientType;
        this.msProvince = msProvince;
        this.VPatientName = VPatientName;
        this.VPatientMaritalStatus = VPatientMaritalStatus;
        this.VPatientGender = VPatientGender;
        this.DPatientDob = DPatientDob;
        this.VPatientAge = VPatientAge;
        this.VPatientReligion = VPatientReligion;
        this.VPatientEdu = VPatientEdu;
        this.VPatientJobType = VPatientJobType;
        this.VPatientMainAddr = VPatientMainAddr;
        this.VPatientMainRtRw = VPatientMainRtRw;
        this.VPatientMainPhNo = VPatientMainPhNo;
        this.VPatientAltAddr = VPatientAltAddr;
        this.VPatientAltRtRw = VPatientAltRtRw;
        this.VPatientAltPhNo = VPatientAltPhNo;
        this.VPatientNationality = VPatientNationality;
        this.VPatientPriority = VPatientPriority;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.tbExaminations = tbExaminations;
        this.tbMedicalRecords = tbMedicalRecords;
//        this.VPatientMotherName = motherName;
//        this.VPatientPartnerName = parterName;
    }
    
    

   
    // Property accessors

    public String getVEtnis() {
		return VEtnis;
	}

	public void setVEtnis(String vEtnis) {
		VEtnis = vEtnis;
	}

	public String getVLanguage() {
		return VLanguage;
	}

	public void setVLanguage(String vLanguage) {
		VLanguage = vLanguage;
	}

	public Integer getNPatientId() {
        return this.NPatientId;
    }
    
    public void setNPatientId(Integer NPatientId) {
        this.NPatientId = NPatientId;
    }

    public MsVillage getMsVillage() {
        return this.msVillage;
    }
    
    public void setMsVillage(MsVillage msVillage) {
        this.msVillage = msVillage;
    }

    public MsSubDistrict getMsSubDistrict() {
        return this.msSubDistrict;
    }
    
    public void setMsSubDistrict(MsSubDistrict msSubDistrict) {
        this.msSubDistrict = msSubDistrict;
    }

    public MsRegency getMsRegency() {
        return this.msRegency;
    }
    
    public void setMsRegency(MsRegency msRegency) {
        this.msRegency = msRegency;
    }

    public MsPatientType getMsPatientType() {
        return this.msPatientType;
    }
    
    public void setMsPatientType(MsPatientType msPatientType) {
        this.msPatientType = msPatientType;
    }

    public MsProvince getMsProvince() {
        return this.msProvince;
    }
    
    public void setMsProvince(MsProvince msProvince) {
        this.msProvince = msProvince;
    }

    public String getVPatientName() {
        return this.VPatientName;
    }
    
    public void setVPatientName(String VPatientName) {
        this.VPatientName = VPatientName;
    }

    public String getVPatientMaritalStatus() {
        return this.VPatientMaritalStatus;
    }
    
    public void setVPatientMaritalStatus(String VPatientMaritalStatus) {
        this.VPatientMaritalStatus = VPatientMaritalStatus;
    }

    public String getVPatientGender() {
        return this.VPatientGender;
    }
    
    public void setVPatientGender(String VPatientGender) {
        this.VPatientGender = VPatientGender;
    }

    public Date getDPatientDob() {
        return this.DPatientDob;
    }
    
    public void setDPatientDob(Date DPatientDob) {
        this.DPatientDob = DPatientDob;
    }

    public short getVPatientAge() {
        return this.VPatientAge;
    }
    
    public void setVPatientAge(short VPatientAge) {
        this.VPatientAge = VPatientAge;
    }

    public String getVPatientReligion() {
        return this.VPatientReligion;
    }
    
    public void setVPatientReligion(String VPatientReligion) {
        this.VPatientReligion = VPatientReligion;
    }

    public String getVPatientEdu() {
        return this.VPatientEdu;
    }
    
    public void setVPatientEdu(String VPatientEdu) {
        this.VPatientEdu = VPatientEdu;
    }

    public String getVPatientJobType() {
        return this.VPatientJobType;
    }
    
    public void setVPatientJobType(String VPatientJobType) {
        this.VPatientJobType = VPatientJobType;
    }

    public String getVPatientMainAddr() {
        return this.VPatientMainAddr;
    }
    
    public void setVPatientMainAddr(String VPatientMainAddr) {
        this.VPatientMainAddr = VPatientMainAddr;
    }

    public String getVPatientMainRtRw() {
        return this.VPatientMainRtRw;
    }
    
    public void setVPatientMainRtRw(String VPatientMainRtRw) {
        this.VPatientMainRtRw = VPatientMainRtRw;
    }

    public String getVPatientMainPhNo() {
        return this.VPatientMainPhNo;
    }
    
    public void setVPatientMainPhNo(String VPatientMainPhNo) {
        this.VPatientMainPhNo = VPatientMainPhNo;
    }

    public String getVPatientAltAddr() {
        return this.VPatientAltAddr;
    }
    
    public void setVPatientAltAddr(String VPatientAltAddr) {
        this.VPatientAltAddr = VPatientAltAddr;
    }

    public String getVPatientAltRtRw() {
        return this.VPatientAltRtRw;
    }
    
    public void setVPatientAltRtRw(String VPatientAltRtRw) {
        this.VPatientAltRtRw = VPatientAltRtRw;
    }

    public String getVPatientAltPhNo() {
        return this.VPatientAltPhNo;
    }
    
    public void setVPatientAltPhNo(String VPatientAltPhNo) {
        this.VPatientAltPhNo = VPatientAltPhNo;
    }

    public String getVPatientNationality() {
        return this.VPatientNationality;
    }
    
    public void setVPatientNationality(String VPatientNationality) {
        this.VPatientNationality = VPatientNationality;
    }

    public String getVPatientPriority() {
        return this.VPatientPriority;
    }
    
    public void setVPatientPriority(String VPatientPriority) {
        this.VPatientPriority = VPatientPriority;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbExaminations() {
        return this.tbExaminations;
    }
    
    public void setTbExaminations(Set tbExaminations) {
        this.tbExaminations = tbExaminations;
    }

    public Set getTbMedicalRecords() {
        return this.tbMedicalRecords;
    }
    
    public void setTbMedicalRecords(Set tbMedicalRecords) {
        this.tbMedicalRecords = tbMedicalRecords;
    }
   








}