package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsRoom generated by MyEclipse - Hibernate Tools
 */

public class MsRoom  implements java.io.Serializable {


    // Fields    

     private Integer NRoomId;
     private MsWard msWard;
     private MsHall msHall;
     private MsTreatmentClass msTreatmentClass;
     private String VRoomCode;
     private String VRoomName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msBeds = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsRoom() {
    }

	/** minimal constructor */
    public MsRoom(Integer NRoomId, String VRoomCode) {
        this.NRoomId = NRoomId;
        this.VRoomCode = VRoomCode;
    }
    
    /** full constructor */
    public MsRoom(Integer NRoomId, MsWard msWard, MsHall msHall, MsTreatmentClass msTreatmentClass, String VRoomCode, String VRoomName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msBeds) {
        this.NRoomId = NRoomId;
        this.msWard = msWard;
        this.msHall = msHall;
        this.msTreatmentClass = msTreatmentClass;
        this.VRoomCode = VRoomCode;
        this.VRoomName = VRoomName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msBeds = msBeds;
    }

   
    // Property accessors

    public Integer getNRoomId() {
        return this.NRoomId;
    }
    
    public void setNRoomId(Integer NRoomId) {
        this.NRoomId = NRoomId;
    }

    public MsWard getMsWard() {
        return this.msWard;
    }
    
    public void setMsWard(MsWard msWard) {
        this.msWard = msWard;
    }

    public MsHall getMsHall() {
        return this.msHall;
    }
    
    public void setMsHall(MsHall msHall) {
        this.msHall = msHall;
    }

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

    public String getVRoomCode() {
        return this.VRoomCode;
    }
    
    public void setVRoomCode(String VRoomCode) {
        this.VRoomCode = VRoomCode;
    }

    public String getVRoomName() {
        return this.VRoomName;
    }
    
    public void setVRoomName(String VRoomName) {
        this.VRoomName = VRoomName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsBeds() {
        return this.msBeds;
    }
    
    public void setMsBeds(Set msBeds) {
        this.msBeds = msBeds;
    }
   








}