package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsScreen generated by MyEclipse - Hibernate Tools
 */

public class MsScreen  implements java.io.Serializable {


    // Fields    

     private Integer NScreenId;
     private MsSubsystem msSubsystem;
     private String VScreenCode;
     private String VDesc;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private Set tbGroupPrivileges = new HashSet(0);
     private Set msScreenInUnits = new HashSet(0);
     private Set tbUserPrivileges = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsScreen() {
    }

	/** minimal constructor */
    public MsScreen(Integer NScreenId, MsSubsystem msSubsystem, String VScreenCode) {
        this.NScreenId = NScreenId;
        this.msSubsystem = msSubsystem;
        this.VScreenCode = VScreenCode;
    }
    
    /** full constructor */
    public MsScreen(Integer NScreenId, MsSubsystem msSubsystem, String VScreenCode, String VDesc, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange, Set tbGroupPrivileges, Set msScreenInUnits, Set tbUserPrivileges) {
        this.NScreenId = NScreenId;
        this.msSubsystem = msSubsystem;
        this.VScreenCode = VScreenCode;
        this.VDesc = VDesc;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.tbGroupPrivileges = tbGroupPrivileges;
        this.msScreenInUnits = msScreenInUnits;
        this.tbUserPrivileges = tbUserPrivileges;
    }

   
    // Property accessors

    public Integer getNScreenId() {
        return this.NScreenId;
    }
    
    public void setNScreenId(Integer NScreenId) {
        this.NScreenId = NScreenId;
    }

    public MsSubsystem getMsSubsystem() {
        return this.msSubsystem;
    }
    
    public void setMsSubsystem(MsSubsystem msSubsystem) {
        this.msSubsystem = msSubsystem;
    }

    public String getVScreenCode() {
        return this.VScreenCode;
    }
    
    public void setVScreenCode(String VScreenCode) {
        this.VScreenCode = VScreenCode;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbGroupPrivileges() {
        return this.tbGroupPrivileges;
    }
    
    public void setTbGroupPrivileges(Set tbGroupPrivileges) {
        this.tbGroupPrivileges = tbGroupPrivileges;
    }

    public Set getMsScreenInUnits() {
        return this.msScreenInUnits;
    }
    
    public void setMsScreenInUnits(Set msScreenInUnits) {
        this.msScreenInUnits = msScreenInUnits;
    }

    public Set getTbUserPrivileges() {
        return this.tbUserPrivileges;
    }
    
    public void setTbUserPrivileges(Set tbUserPrivileges) {
        this.tbUserPrivileges = tbUserPrivileges;
    }
   








}