package com.vone.medisafe.mapping;



/**
 * MsScreenInUnitId generated by MyEclipse - Hibernate Tools
 */

public class MsScreenInUnitId  implements java.io.Serializable {


    // Fields    

     private MsScreen msScreen;
     private MsUnit msUnit;


    // Constructors

    /** default constructor */
    public MsScreenInUnitId() {
    }

    
    /** full constructor */
    public MsScreenInUnitId(MsScreen msScreen, MsUnit msUnit) {
        this.msScreen = msScreen;
        this.msUnit = msUnit;
    }

   
    // Property accessors

    public MsScreen getMsScreen() {
        return this.msScreen;
    }
    
    public void setMsScreen(MsScreen msScreen) {
        this.msScreen = msScreen;
    }

    public MsUnit getMsUnit() {
        return this.msUnit;
    }
    
    public void setMsUnit(MsUnit msUnit) {
        this.msUnit = msUnit;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsScreenInUnitId) ) return false;
		 MsScreenInUnitId castOther = ( MsScreenInUnitId ) other; 
         
		 return ( (this.getMsScreen()==castOther.getMsScreen()) || ( this.getMsScreen()!=null && castOther.getMsScreen()!=null && this.getMsScreen().equals(castOther.getMsScreen()) ) )
 && ( (this.getMsUnit()==castOther.getMsUnit()) || ( this.getMsUnit()!=null && castOther.getMsUnit()!=null && this.getMsUnit().equals(castOther.getMsUnit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsScreen() == null ? 0 : this.getMsScreen().hashCode() );
         result = 37 * result + ( getMsUnit() == null ? 0 : this.getMsUnit().hashCode() );
         return result;
   }   





}