package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsScreenInUnit generated by MyEclipse - Hibernate Tools
 */

public class MsScreenInUnit  implements java.io.Serializable {


    // Fields    

     private MsScreenInUnitId id;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public MsScreenInUnit() {
    }

	/** minimal constructor */
    public MsScreenInUnit(MsScreenInUnitId id) {
        this.id = id;
    }
    
    /** full constructor */
    public MsScreenInUnit(MsScreenInUnitId id, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.id = id;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public MsScreenInUnitId getId() {
        return this.id;
    }
    
    public void setId(MsScreenInUnitId id) {
        this.id = id;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}