package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsBank generated by MyEclipse - Hibernate Tools
 */

public class MsShift  implements java.io.Serializable {


    // Fields    

     private Integer NShiftId;
     private String VShiftCode;
     private Date DShiftFrom;
     private Date DShiftTo;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;   

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public Date getDShiftFrom() {
		return DShiftFrom;
	}

	public void setDShiftFrom(Date shiftFrom) {
		DShiftFrom = shiftFrom;
	}

	public Date getDShiftTo() {
		return DShiftTo;
	}

	public void setDShiftTo(Date shiftTo) {
		DShiftTo = shiftTo;
	}

	public Integer getNShiftId() {
		return NShiftId;
	}

	public void setNShiftId(Integer shiftId) {
		NShiftId = shiftId;
	}

	public String getVShiftCode() {
		return VShiftCode;
	}

	public void setVShiftCode(String shiftCode) {
		VShiftCode = shiftCode;
	}

	public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }




}