package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsStaffInUnit generated by MyEclipse - Hibernate Tools
 */

public class MsStaffInUnit  implements java.io.Serializable {


    // Fields    

     private MsStaffInUnitId id;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbRegistrations = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsStaffInUnit() {
    }

	/** minimal constructor */
    public MsStaffInUnit(MsStaffInUnitId id) {
        this.id = id;
    }
    
    /** full constructor */
    public MsStaffInUnit(MsStaffInUnitId id, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbRegistrations) {
        this.id = id;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbRegistrations = tbRegistrations;
    }

   
    // Property accessors

    public MsStaffInUnitId getId() {
        return this.id;
    }
    
    public void setId(MsStaffInUnitId id) {
        this.id = id;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbRegistrations() {
        return this.tbRegistrations;
    }
    
    public void setTbRegistrations(Set tbRegistrations) {
        this.tbRegistrations = tbRegistrations;
    }
   








}