package com.vone.medisafe.mapping;



/**
 * MsStaffInUnitId generated by MyEclipse - Hibernate Tools
 */

public class MsStaffInUnitId  implements java.io.Serializable {


    // Fields    

     private MsUnit msUnit;
     private MsStaff msStaff;


    // Constructors

    /** default constructor */
    public MsStaffInUnitId() {
    }

    
    /** full constructor */
    public MsStaffInUnitId(MsUnit msUnit, MsStaff msStaff) {
        this.msUnit = msUnit;
        this.msStaff = msStaff;
    }

   
    // Property accessors

    public MsUnit getMsUnit() {
        return this.msUnit;
    }
    
    public void setMsUnit(MsUnit msUnit) {
        this.msUnit = msUnit;
    }

    public MsStaff getMsStaff() {
        return this.msStaff;
    }
    
    public void setMsStaff(MsStaff msStaff) {
        this.msStaff = msStaff;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsStaffInUnitId) ) return false;
		 MsStaffInUnitId castOther = ( MsStaffInUnitId ) other; 
         
		 return ( (this.getMsUnit()==castOther.getMsUnit()) || ( this.getMsUnit()!=null && castOther.getMsUnit()!=null && this.getMsUnit().equals(castOther.getMsUnit()) ) )
 && ( (this.getMsStaff()==castOther.getMsStaff()) || ( this.getMsStaff()!=null && castOther.getMsStaff()!=null && this.getMsStaff().equals(castOther.getMsStaff()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsUnit() == null ? 0 : this.getMsUnit().hashCode() );
         result = 37 * result + ( getMsStaff() == null ? 0 : this.getMsStaff().hashCode() );
         return result;
   }   





}