package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsSubDistrict generated by MyEclipse - Hibernate Tools
 */

public class MsSubDistrict  implements java.io.Serializable {


    // Fields    

     private Integer NSubdistrictId;
     private String VSubDistrictId;
     private String VSubDistrictName;
     private MsRegency regency;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msPatients = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsSubDistrict() {
    }

	/** minimal constructor */
    public MsSubDistrict(Integer NSubdistrictId, String VSubDistrictId, String VSubDistrictName) {
        this.NSubdistrictId = NSubdistrictId;
        this.VSubDistrictId = VSubDistrictId;
        this.VSubDistrictName = VSubDistrictName;
    }
    
    /** full constructor */
    public MsSubDistrict(Integer NSubdistrictId, String VSubDistrictId, String VSubDistrictName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msPatients) {
        this.NSubdistrictId = NSubdistrictId;
        this.VSubDistrictId = VSubDistrictId;
        this.VSubDistrictName = VSubDistrictName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msPatients = msPatients;
    }

   
    
    // Property accessors

    public MsRegency getRegency() {
		return regency;
	}

	public void setRegency(MsRegency regency) {
		this.regency = regency;
	}

	public Integer getNSubdistrictId() {
        return this.NSubdistrictId;
    }
    
    public void setNSubdistrictId(Integer NSubdistrictId) {
        this.NSubdistrictId = NSubdistrictId;
    }

    public String getVSubDistrictId() {
        return this.VSubDistrictId;
    }
    
    public void setVSubDistrictId(String VSubDistrictId) {
        this.VSubDistrictId = VSubDistrictId;
    }

    public String getVSubDistrictName() {
        return this.VSubDistrictName;
    }
    
    public void setVSubDistrictName(String VSubDistrictName) {
        this.VSubDistrictName = VSubDistrictName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsPatients() {
        return this.msPatients;
    }
    
    public void setMsPatients(Set msPatients) {
        this.msPatients = msPatients;
    }
   








}