package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsSubsystemId generated by MyEclipse - Hibernate Tools
 */

public class MsSubsystemId  implements java.io.Serializable {


    // Fields    

     private Integer NSubsystemId;
     private String VSubsystemCode;
     private String VDesc;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchange;


    // Constructors

    /** default constructor */
    public MsSubsystemId() {
    }

	/** minimal constructor */
    public MsSubsystemId(Integer NSubsystemId) {
        this.NSubsystemId = NSubsystemId;
    }
    
    /** full constructor */
    public MsSubsystemId(Integer NSubsystemId, String VSubsystemCode, String VDesc, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchange) {
        this.NSubsystemId = NSubsystemId;
        this.VSubsystemCode = VSubsystemCode;
        this.VDesc = VDesc;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchange = DWhnchange;
    }
    

   
    // Property accessors

    public Integer getNSubsystemId() {
        return this.NSubsystemId;
    }
    
    public void setNSubsystemId(Integer NSubsystemId) {
        this.NSubsystemId = NSubsystemId;
    }

    public String getVSubsystemCode() {
        return this.VSubsystemCode;
    }
    
    public void setVSubsystemCode(String VSubsystemCode) {
        this.VSubsystemCode = VSubsystemCode;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchange() {
        return this.DWhnchange;
    }
    
    public void setDWhnchange(Date DWhnchange) {
        this.DWhnchange = DWhnchange;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsSubsystemId) ) return false;
		 MsSubsystemId castOther = ( MsSubsystemId ) other; 
         
		 return ( (this.getNSubsystemId()==castOther.getNSubsystemId()) || ( this.getNSubsystemId()!=null && castOther.getNSubsystemId()!=null && this.getNSubsystemId().equals(castOther.getNSubsystemId()) ) )
 && ( (this.getVSubsystemCode()==castOther.getVSubsystemCode()) || ( this.getVSubsystemCode()!=null && castOther.getVSubsystemCode()!=null && this.getVSubsystemCode().equals(castOther.getVSubsystemCode()) ) )
 && ( (this.getVDesc()==castOther.getVDesc()) || ( this.getVDesc()!=null && castOther.getVDesc()!=null && this.getVDesc().equals(castOther.getVDesc()) ) )
 && ( (this.getVWhocreate()==castOther.getVWhocreate()) || ( this.getVWhocreate()!=null && castOther.getVWhocreate()!=null && this.getVWhocreate().equals(castOther.getVWhocreate()) ) )
 && ( (this.getDWhncreate()==castOther.getDWhncreate()) || ( this.getDWhncreate()!=null && castOther.getDWhncreate()!=null && this.getDWhncreate().equals(castOther.getDWhncreate()) ) )
 && ( (this.getVWhochange()==castOther.getVWhochange()) || ( this.getVWhochange()!=null && castOther.getVWhochange()!=null && this.getVWhochange().equals(castOther.getVWhochange()) ) )
 && ( (this.getDWhnchange()==castOther.getDWhnchange()) || ( this.getDWhnchange()!=null && castOther.getDWhnchange()!=null && this.getDWhnchange().equals(castOther.getDWhnchange()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNSubsystemId() == null ? 0 : this.getNSubsystemId().hashCode() );
         result = 37 * result + ( getVSubsystemCode() == null ? 0 : this.getVSubsystemCode().hashCode() );
         result = 37 * result + ( getVDesc() == null ? 0 : this.getVDesc().hashCode() );
         result = 37 * result + ( getVWhocreate() == null ? 0 : this.getVWhocreate().hashCode() );
         result = 37 * result + ( getDWhncreate() == null ? 0 : this.getDWhncreate().hashCode() );
         result = 37 * result + ( getVWhochange() == null ? 0 : this.getVWhochange().hashCode() );
         result = 37 * result + ( getDWhnchange() == null ? 0 : this.getDWhnchange().hashCode() );
         return result;
   }   





}