package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsTreatmentClass generated by MyEclipse - Hibernate Tools
 */

public class MsTreatmentClass  implements java.io.Serializable {


    // Fields    

     private Integer NTclassId;
     private String VTclassCode;
     private String VTclassDesc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbRoomReservations = new HashSet(0);
     private Set msTreatmentRoomFees = new HashSet(0);
     private Set msHalls = new HashSet(0);
     private Set msItemSellingPrices = new HashSet(0);
     private Set msTreatmentFees = new HashSet(0);
     private Set msRooms = new HashSet(0);
     private Set msBeds = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsTreatmentClass() {
    }

	/** minimal constructor */
    public MsTreatmentClass(Integer NTclassId, String VTclassCode, String VTclassDesc) {
        this.NTclassId = NTclassId;
        this.VTclassCode = VTclassCode;
        this.VTclassDesc = VTclassDesc;
    }
    
    /** full constructor */
    public MsTreatmentClass(Integer NTclassId, String VTclassCode, String VTclassDesc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbRoomReservations, Set msTreatmentRoomFees, Set msHalls, Set msItemSellingPrices, Set msTreatmentFees, Set msRooms, Set msBeds) {
        this.NTclassId = NTclassId;
        this.VTclassCode = VTclassCode;
        this.VTclassDesc = VTclassDesc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbRoomReservations = tbRoomReservations;
        this.msTreatmentRoomFees = msTreatmentRoomFees;
        this.msHalls = msHalls;
        this.msItemSellingPrices = msItemSellingPrices;
        this.msTreatmentFees = msTreatmentFees;
        this.msRooms = msRooms;
        this.msBeds = msBeds;
    }

   
    // Property accessors

    public Integer getNTclassId() {
        return this.NTclassId;
    }
    
    public void setNTclassId(Integer NTclassId) {
        this.NTclassId = NTclassId;
    }

    public String getVTclassCode() {
        return this.VTclassCode;
    }
    
    public void setVTclassCode(String VTclassCode) {
        this.VTclassCode = VTclassCode;
    }

    public String getVTclassDesc() {
        return this.VTclassDesc;
    }
    
    public void setVTclassDesc(String VTclassDesc) {
        this.VTclassDesc = VTclassDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbRoomReservations() {
        return this.tbRoomReservations;
    }
    
    public void setTbRoomReservations(Set tbRoomReservations) {
        this.tbRoomReservations = tbRoomReservations;
    }

    public Set getMsTreatmentRoomFees() {
        return this.msTreatmentRoomFees;
    }
    
    public void setMsTreatmentRoomFees(Set msTreatmentRoomFees) {
        this.msTreatmentRoomFees = msTreatmentRoomFees;
    }

    public Set getMsHalls() {
        return this.msHalls;
    }
    
    public void setMsHalls(Set msHalls) {
        this.msHalls = msHalls;
    }

    public Set getMsItemSellingPrices() {
        return this.msItemSellingPrices;
    }
    
    public void setMsItemSellingPrices(Set msItemSellingPrices) {
        this.msItemSellingPrices = msItemSellingPrices;
    }

    public Set getMsTreatmentFees() {
        return this.msTreatmentFees;
    }
    
    public void setMsTreatmentFees(Set msTreatmentFees) {
        this.msTreatmentFees = msTreatmentFees;
    }

    public Set getMsRooms() {
        return this.msRooms;
    }
    
    public void setMsRooms(Set msRooms) {
        this.msRooms = msRooms;
    }

    public Set getMsBeds() {
        return this.msBeds;
    }
    
    public void setMsBeds(Set msBeds) {
        this.msBeds = msBeds;
    }
   








}