package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsTreatment generated by MyEclipse - Hibernate Tools
 */

public class MsTreatment  implements java.io.Serializable {


    // Fields    

     private Integer NTreatmentId;
     private MsTreatmentGroup msTreatmentGroup;
//     private MsUnit msUnit;
     private String VTreatmentCode;
     private String VTreatmentName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msTreatmentFees = new HashSet(0);
     private Set msLabTestDetails = new HashSet(0);
     private Set tbLaboratoryResultDetails = new HashSet(0);
     private Set msLabTreatmentDetil = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsTreatment() {
    }

	/** minimal constructor */
    public MsTreatment(Integer NTreatmentId, MsTreatmentGroup msTreatmentGroup, MsUnit msUnit, String VTreatmentCode, String VTreatmentName) {
        this.NTreatmentId = NTreatmentId;
        this.msTreatmentGroup = msTreatmentGroup;
//        this.msUnit = msUnit;
        this.VTreatmentCode = VTreatmentCode;
        this.VTreatmentName = VTreatmentName;
    }
    
    /** full constructor */
    public MsTreatment(Integer NTreatmentId, MsTreatmentGroup msTreatmentGroup, MsUnit msUnit, String VTreatmentCode, String VTreatmentName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msTreatmentFees, Set msLabTestDetails, Set tbLaboratoryResultDetails) {
        this.NTreatmentId = NTreatmentId;
        this.msTreatmentGroup = msTreatmentGroup;
//        this.msUnit = msUnit;
        this.VTreatmentCode = VTreatmentCode;
        this.VTreatmentName = VTreatmentName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msTreatmentFees = msTreatmentFees;
        this.msLabTestDetails = msLabTestDetails;
        this.tbLaboratoryResultDetails = tbLaboratoryResultDetails;
    }

   
    // Property accessors

    public Integer getNTreatmentId() {
        return this.NTreatmentId;
    }
    
    public void setNTreatmentId(Integer NTreatmentId) {
        this.NTreatmentId = NTreatmentId;
    }

    public MsTreatmentGroup getMsTreatmentGroup() {
        return this.msTreatmentGroup;
    }
    
    public void setMsTreatmentGroup(MsTreatmentGroup msTreatmentGroup) {
        this.msTreatmentGroup = msTreatmentGroup;
    }

//    public MsUnit getMsUnit() {
//        return this.msUnit;
//    }
    
//    public void setMsUnit(MsUnit msUnit) {
//        this.msUnit = msUnit;
//    }

    public String getVTreatmentCode() {
        return this.VTreatmentCode;
    }
    
    public void setVTreatmentCode(String VTreatmentCode) {
        this.VTreatmentCode = VTreatmentCode;
    }

    public String getVTreatmentName() {
        return this.VTreatmentName;
    }
    
    public void setVTreatmentName(String VTreatmentName) {
        this.VTreatmentName = VTreatmentName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsTreatmentFees() {
        return this.msTreatmentFees;
    }
    
    public void setMsTreatmentFees(Set msTreatmentFees) {
        this.msTreatmentFees = msTreatmentFees;
    }

    public Set getMsLabTestDetails() {
        return this.msLabTestDetails;
    }
    
    public void setMsLabTestDetails(Set msLabTestDetails) {
        this.msLabTestDetails = msLabTestDetails;
    }

    public Set getTbLaboratoryResultDetails() {
        return this.tbLaboratoryResultDetails;
    }
    
    public void setTbLaboratoryResultDetails(Set tbLaboratoryResultDetails) {
        this.tbLaboratoryResultDetails = tbLaboratoryResultDetails;
    }

	public Set getMsLabTreatmentDetil() {
		return msLabTreatmentDetil;
	}

	public void setMsLabTreatmentDetil(Set msLabTreatmentDetil) {
		this.msLabTreatmentDetil = msLabTreatmentDetil;
	}
   








}