package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsTreatmentRoom generated by MyEclipse - Hibernate Tools
 */

public class MsTreatmentRoom  implements java.io.Serializable {


    // Fields    

     private Integer NTroomId;
     private String VTroomCode;
     private String VTroomName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msTreatmentRoomFees = new HashSet(0);
     private Set tbTreatmentRoomReservations = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsTreatmentRoom() {
    }

	/** minimal constructor */
    public MsTreatmentRoom(Integer NTroomId, String VTroomCode, String VTroomName, String VWhoCreate, Date DWhnCreate) {
        this.NTroomId = NTroomId;
        this.VTroomCode = VTroomCode;
        this.VTroomName = VTroomName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public MsTreatmentRoom(Integer NTroomId, String VTroomCode, String VTroomName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msTreatmentRoomFees, Set tbTreatmentRoomReservations) {
        this.NTroomId = NTroomId;
        this.VTroomCode = VTroomCode;
        this.VTroomName = VTroomName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msTreatmentRoomFees = msTreatmentRoomFees;
        this.tbTreatmentRoomReservations = tbTreatmentRoomReservations;
    }

   
    // Property accessors

    public Integer getNTroomId() {
        return this.NTroomId;
    }
    
    public void setNTroomId(Integer NTroomId) {
        this.NTroomId = NTroomId;
    }

    public String getVTroomCode() {
        return this.VTroomCode;
    }
    
    public void setVTroomCode(String VTroomCode) {
        this.VTroomCode = VTroomCode;
    }

    public String getVTroomName() {
        return this.VTroomName;
    }
    
    public void setVTroomName(String VTroomName) {
        this.VTroomName = VTroomName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsTreatmentRoomFees() {
        return this.msTreatmentRoomFees;
    }
    
    public void setMsTreatmentRoomFees(Set msTreatmentRoomFees) {
        this.msTreatmentRoomFees = msTreatmentRoomFees;
    }

    public Set getTbTreatmentRoomReservations() {
        return this.tbTreatmentRoomReservations;
    }
    
    public void setTbTreatmentRoomReservations(Set tbTreatmentRoomReservations) {
        this.tbTreatmentRoomReservations = tbTreatmentRoomReservations;
    }
   








}