package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsTreatmentGroup generated by MyEclipse - Hibernate Tools
 */

public class MsTreatmentGroup  implements java.io.Serializable {


    // Fields    

     private Integer NTgroupId;
     private String VTgroupCode;
     private String VTgroupName;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbBundledTreatments = new HashSet(0);
     private Set msTreatments = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsTreatmentGroup() {
    }

	/** minimal constructor */
    public MsTreatmentGroup(Integer NTgroupId, String VTgroupCode, String VTgroupName) {
        this.NTgroupId = NTgroupId;
        this.VTgroupCode = VTgroupCode;
        this.VTgroupName = VTgroupName;
    }
    
    /** full constructor */
    public MsTreatmentGroup(Integer NTgroupId, String VTgroupCode, String VTgroupName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbBundledTreatments, Set msTreatments) {
        this.NTgroupId = NTgroupId;
        this.VTgroupCode = VTgroupCode;
        this.VTgroupName = VTgroupName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbBundledTreatments = tbBundledTreatments;
        this.msTreatments = msTreatments;
    }

   
    // Property accessors

    public Integer getNTgroupId() {
        return this.NTgroupId;
    }
    
    public void setNTgroupId(Integer NTgroupId) {
        this.NTgroupId = NTgroupId;
    }

    public String getVTgroupCode() {
        return this.VTgroupCode;
    }
    
    public void setVTgroupCode(String VTgroupCode) {
        this.VTgroupCode = VTgroupCode;
    }

    public String getVTgroupName() {
        return this.VTgroupName;
    }
    
    public void setVTgroupName(String VTgroupName) {
        this.VTgroupName = VTgroupName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbBundledTreatments() {
        return this.tbBundledTreatments;
    }
    
    public void setTbBundledTreatments(Set tbBundledTreatments) {
        this.tbBundledTreatments = tbBundledTreatments;
    }

    public Set getMsTreatments() {
        return this.msTreatments;
    }
    
    public void setMsTreatments(Set msTreatments) {
        this.msTreatments = msTreatments;
    }
   








}