package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsTreatmentFee generated by MyEclipse - Hibernate Tools
 */

public class MsTreatmentFee  implements java.io.Serializable {


    // Fields    

     private Integer NTreatmentFeeId;
     private MsTreatmentClass msTreatmentClass;
     private MsCoa msCoa;
     private MsTreatment msTreatment;
     private Integer NTgroupId;
     private Double NTrtfeeFee;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Double NDoctorFee;
     private Double NMedicFee;
     private Double NRsFee;
     private Set tbTreatmentTrxes = new HashSet(0);
     private Set tbItemTrxes = new HashSet(0);
     private Set tbBundledTreatments = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsTreatmentFee() {
    }

	/** minimal constructor */
    public MsTreatmentFee(Integer NTreatmentFeeId, MsTreatmentClass msTreatmentClass, MsTreatment msTreatment) {
        this.NTreatmentFeeId = NTreatmentFeeId;
        this.msTreatmentClass = msTreatmentClass;
        this.msTreatment = msTreatment;
    }
    
    /** full constructor */
    public MsTreatmentFee(Integer NTreatmentFeeId, MsTreatmentClass msTreatmentClass, MsCoa msCoa, MsTreatment msTreatment, Integer NTgroupId, double NTrtfeeFee, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, double NDoctorFee, double NMedicFee, double NRsFee, Set tbTreatmentTrxes, Set tbItemTrxes, Set tbBundledTreatments) {
        this.NTreatmentFeeId = NTreatmentFeeId;
        this.msTreatmentClass = msTreatmentClass;
        this.msCoa = msCoa;
        this.msTreatment = msTreatment;
        this.NTgroupId = NTgroupId;
        this.NTrtfeeFee = NTrtfeeFee;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.NDoctorFee = NDoctorFee;
        this.NMedicFee = NMedicFee;
        this.NRsFee = NRsFee;
        this.tbTreatmentTrxes = tbTreatmentTrxes;
        this.tbItemTrxes = tbItemTrxes;
        this.tbBundledTreatments = tbBundledTreatments;
    }

   
    // Property accessors

    public Integer getNTreatmentFeeId() {
        return this.NTreatmentFeeId;
    }
    
    public void setNTreatmentFeeId(Integer NTreatmentFeeId) {
        this.NTreatmentFeeId = NTreatmentFeeId;
    }

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

    public MsCoa getMsCoa() {
        return this.msCoa;
    }
    
    public void setMsCoa(MsCoa msCoa) {
        this.msCoa = msCoa;
    }

    public MsTreatment getMsTreatment() {
        return this.msTreatment;
    }
    
    public void setMsTreatment(MsTreatment msTreatment) {
        this.msTreatment = msTreatment;
    }

    public Integer getNTgroupId() {
        return this.NTgroupId;
    }
    
    public void setNTgroupId(Integer NTgroupId) {
        this.NTgroupId = NTgroupId;
    }

    public Double getNTrtfeeFee() {
        return this.NTrtfeeFee;
    }
    
    public void setNTrtfeeFee(Double NTrtfeeFee) {
        this.NTrtfeeFee = NTrtfeeFee;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Double getNDoctorFee() {
        return this.NDoctorFee;
    }
    
    public void setNDoctorFee(Double NDoctorFee) {
        this.NDoctorFee = NDoctorFee;
    }

    public Double getNMedicFee() {
        return this.NMedicFee;
    }
    
    public void setNMedicFee(Double NMedicFee) {
        this.NMedicFee = NMedicFee;
    }

    public Double getNRsFee() {
        return this.NRsFee;
    }
    
    public void setNRsFee(Double NRsFee) {
        this.NRsFee = NRsFee;
    }

    public Set getTbTreatmentTrxes() {
        return this.tbTreatmentTrxes;
    }
    
    public void setTbTreatmentTrxes(Set tbTreatmentTrxes) {
        this.tbTreatmentTrxes = tbTreatmentTrxes;
    }

    public Set getTbItemTrxes() {
        return this.tbItemTrxes;
    }
    
    public void setTbItemTrxes(Set tbItemTrxes) {
        this.tbItemTrxes = tbItemTrxes;
    }

    public Set getTbBundledTreatments() {
        return this.tbBundledTreatments;
    }
    
    public void setTbBundledTreatments(Set tbBundledTreatments) {
        this.tbBundledTreatments = tbBundledTreatments;
    }
   








}