package com.vone.medisafe.mapping;



/**
 * MsTypeOfViolent generated by MyEclipse - Hibernate Tools
 */

public class MsTypeOfViolent  implements java.io.Serializable {


    // Fields    

     private String VViolentTypeId;
     private String VViolentTypeDesc;


    // Constructors

    /** default constructor */
    public MsTypeOfViolent() {
    }

    
    /** full constructor */
    public MsTypeOfViolent(String VViolentTypeId, String VViolentTypeDesc) {
        this.VViolentTypeId = VViolentTypeId;
        this.VViolentTypeDesc = VViolentTypeDesc;
    }
    

   
    // Property accessors

    public String getVViolentTypeId() {
        return this.VViolentTypeId;
    }
    
    public void setVViolentTypeId(String VViolentTypeId) {
        this.VViolentTypeId = VViolentTypeId;
    }

    public String getVViolentTypeDesc() {
        return this.VViolentTypeDesc;
    }
    
    public void setVViolentTypeDesc(String VViolentTypeDesc) {
        this.VViolentTypeDesc = VViolentTypeDesc;
    }
   








}