package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsUser generated by MyEclipse - Hibernate Tools
 */

public class MsUser  implements java.io.Serializable {


    // Fields    

     private Integer NUserId;
     private MsGroup msGroup;
     private MsStaff msStaff;
     private MsBranch msBranch;
     private String VUserName;
     private String VPassword;
     private String VUserFullName;
     private String VDesc;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchange;
     private Set tbUserPrivileges = new HashSet(0);     


    // Constructors

    /** default constructor */
    public MsUser() {
    }

	/** minimal constructor */
    public MsUser(Integer NUserId, String VUserName, String VPassword) {
        this.NUserId = NUserId;
        this.VUserName = VUserName;
        this.VPassword = VPassword;
    }
    
    /** full constructor */
    public MsUser(Integer NUserId, MsGroup msGroup, MsBranch msBranch, MsStaff msStaff, String VUserName, String VPassword, String VUserFullName, String VDesc, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchange, Set tbUserPrivileges) {
        this.NUserId = NUserId;
        this.msGroup = msGroup;
        this.msBranch = msBranch;
        this.msStaff = msStaff;
        this.VUserName = VUserName;
        this.VPassword = VPassword;
        this.VUserFullName = VUserFullName;
        this.VDesc = VDesc;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchange = DWhnchange;
        this.tbUserPrivileges = tbUserPrivileges;
    }

   
    // Property accessors

    public Integer getNUserId() {
        return this.NUserId;
    }
    
    public void setNUserId(Integer NUserId) {
        this.NUserId = NUserId;
    }

    public MsGroup getMsGroup() {
        return this.msGroup;
    }
    
    public void setMsGroup(MsGroup msGroup) {
        this.msGroup = msGroup;
    }

    public MsBranch getMsBranch() {
        return this.msBranch;
    }
    
    public void setMsBranch(MsBranch msBranch) {
        this.msBranch = msBranch;
    }

    public String getVUserName() {
        return this.VUserName;
    }
    
    public void setVUserName(String VUserName) {
        this.VUserName = VUserName;
    }

    public String getVPassword() {
        return this.VPassword;
    }
    
    public void setVPassword(String VPassword) {
        this.VPassword = VPassword;
    }

    public String getVUserFullName() {
        return this.VUserFullName;
    }
    
    public void setVUserFullName(String VUserFullName) {
        this.VUserFullName = VUserFullName;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchange() {
        return this.DWhnchange;
    }
    
    public void setDWhnchange(Date DWhnchange) {
        this.DWhnchange = DWhnchange;
    }

    public Set getTbUserPrivileges() {
        return this.tbUserPrivileges;
    }
    
    public void setTbUserPrivileges(Set tbUserPrivileges) {
        this.tbUserPrivileges = tbUserPrivileges;
    }

	public MsStaff getMsStaff() {
		return msStaff;
	}

	public void setMsStaff(MsStaff msStaff) {
		this.msStaff = msStaff;
	}
   








}