package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * MsUserId generated by MyEclipse - Hibernate Tools
 */

public class MsUserId  implements java.io.Serializable {


    // Fields    

     private Integer NUserId;
     private String VUserName;
     private String VPassword;
     private String VUserFullName;
     private Integer NGroupId;
     private String VDesc;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchange;
     private Integer NBranchId;


    // Constructors

    /** default constructor */
    public MsUserId() {
    }

	/** minimal constructor */
    public MsUserId(Integer NUserId, String VUserName, String VPassword) {
        this.NUserId = NUserId;
        this.VUserName = VUserName;
        this.VPassword = VPassword;
    }
    
    /** full constructor */
    public MsUserId(Integer NUserId, String VUserName, String VPassword, String VUserFullName, Integer NGroupId, String VDesc, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchange, Integer NBranchId) {
        this.NUserId = NUserId;
        this.VUserName = VUserName;
        this.VPassword = VPassword;
        this.VUserFullName = VUserFullName;
        this.NGroupId = NGroupId;
        this.VDesc = VDesc;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchange = DWhnchange;
        this.NBranchId = NBranchId;
    }
    

   
    // Property accessors

    public Integer getNUserId() {
        return this.NUserId;
    }
    
    public void setNUserId(Integer NUserId) {
        this.NUserId = NUserId;
    }

    public String getVUserName() {
        return this.VUserName;
    }
    
    public void setVUserName(String VUserName) {
        this.VUserName = VUserName;
    }

    public String getVPassword() {
        return this.VPassword;
    }
    
    public void setVPassword(String VPassword) {
        this.VPassword = VPassword;
    }

    public String getVUserFullName() {
        return this.VUserFullName;
    }
    
    public void setVUserFullName(String VUserFullName) {
        this.VUserFullName = VUserFullName;
    }

    public Integer getNGroupId() {
        return this.NGroupId;
    }
    
    public void setNGroupId(Integer NGroupId) {
        this.NGroupId = NGroupId;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchange() {
        return this.DWhnchange;
    }
    
    public void setDWhnchange(Date DWhnchange) {
        this.DWhnchange = DWhnchange;
    }

    public Integer getNBranchId() {
        return this.NBranchId;
    }
    
    public void setNBranchId(Integer NBranchId) {
        this.NBranchId = NBranchId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsUserId) ) return false;
		 MsUserId castOther = ( MsUserId ) other; 
         
		 return ( (this.getNUserId()==castOther.getNUserId()) || ( this.getNUserId()!=null && castOther.getNUserId()!=null && this.getNUserId().equals(castOther.getNUserId()) ) )
 && ( (this.getVUserName()==castOther.getVUserName()) || ( this.getVUserName()!=null && castOther.getVUserName()!=null && this.getVUserName().equals(castOther.getVUserName()) ) )
 && ( (this.getVPassword()==castOther.getVPassword()) || ( this.getVPassword()!=null && castOther.getVPassword()!=null && this.getVPassword().equals(castOther.getVPassword()) ) )
 && ( (this.getVUserFullName()==castOther.getVUserFullName()) || ( this.getVUserFullName()!=null && castOther.getVUserFullName()!=null && this.getVUserFullName().equals(castOther.getVUserFullName()) ) )
 && ( (this.getNGroupId()==castOther.getNGroupId()) || ( this.getNGroupId()!=null && castOther.getNGroupId()!=null && this.getNGroupId().equals(castOther.getNGroupId()) ) )
 && ( (this.getVDesc()==castOther.getVDesc()) || ( this.getVDesc()!=null && castOther.getVDesc()!=null && this.getVDesc().equals(castOther.getVDesc()) ) )
 && ( (this.getVWhocreate()==castOther.getVWhocreate()) || ( this.getVWhocreate()!=null && castOther.getVWhocreate()!=null && this.getVWhocreate().equals(castOther.getVWhocreate()) ) )
 && ( (this.getDWhncreate()==castOther.getDWhncreate()) || ( this.getDWhncreate()!=null && castOther.getDWhncreate()!=null && this.getDWhncreate().equals(castOther.getDWhncreate()) ) )
 && ( (this.getVWhochange()==castOther.getVWhochange()) || ( this.getVWhochange()!=null && castOther.getVWhochange()!=null && this.getVWhochange().equals(castOther.getVWhochange()) ) )
 && ( (this.getDWhnchange()==castOther.getDWhnchange()) || ( this.getDWhnchange()!=null && castOther.getDWhnchange()!=null && this.getDWhnchange().equals(castOther.getDWhnchange()) ) )
 && ( (this.getNBranchId()==castOther.getNBranchId()) || ( this.getNBranchId()!=null && castOther.getNBranchId()!=null && this.getNBranchId().equals(castOther.getNBranchId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNUserId() == null ? 0 : this.getNUserId().hashCode() );
         result = 37 * result + ( getVUserName() == null ? 0 : this.getVUserName().hashCode() );
         result = 37 * result + ( getVPassword() == null ? 0 : this.getVPassword().hashCode() );
         result = 37 * result + ( getVUserFullName() == null ? 0 : this.getVUserFullName().hashCode() );
         result = 37 * result + ( getNGroupId() == null ? 0 : this.getNGroupId().hashCode() );
         result = 37 * result + ( getVDesc() == null ? 0 : this.getVDesc().hashCode() );
         result = 37 * result + ( getVWhocreate() == null ? 0 : this.getVWhocreate().hashCode() );
         result = 37 * result + ( getDWhncreate() == null ? 0 : this.getDWhncreate().hashCode() );
         result = 37 * result + ( getVWhochange() == null ? 0 : this.getVWhochange().hashCode() );
         result = 37 * result + ( getDWhnchange() == null ? 0 : this.getDWhnchange().hashCode() );
         result = 37 * result + ( getNBranchId() == null ? 0 : this.getNBranchId().hashCode() );
         return result;
   }   





}