package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsVillage generated by MyEclipse - Hibernate Tools
 */

public class MsVillage  implements java.io.Serializable {


    // Fields    

     private Integer NVillageId;
     private String VVillageCode;
     private String VVillageName;
     private MsSubDistrict subdistrict;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set msPatients = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsVillage() {
    }

	/** minimal constructor */
    public MsVillage(Integer NVillageId, String VVillageCode, String VVillageName) {
        this.NVillageId = NVillageId;
        this.VVillageCode = VVillageCode;
        this.VVillageName = VVillageName;
    }
    
    /** full constructor */
    public MsVillage(Integer NVillageId, String VVillageCode, String VVillageName, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set msPatients) {
        this.NVillageId = NVillageId;
        this.VVillageCode = VVillageCode;
        this.VVillageName = VVillageName;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.msPatients = msPatients;
    }

    
   
    // Property accessors

    public MsSubDistrict getSubdistrict() {
		return subdistrict;
	}

	public void setSubdistrict(MsSubDistrict subdistrict) {
		this.subdistrict = subdistrict;
	}

	public Integer getNVillageId() {
        return this.NVillageId;
    }
    
    public void setNVillageId(Integer NVillageId) {
        this.NVillageId = NVillageId;
    }

    public String getVVillageCode() {
        return this.VVillageCode;
    }
    
    public void setVVillageCode(String VVillageCode) {
        this.VVillageCode = VVillageCode;
    }

    public String getVVillageName() {
        return this.VVillageName;
    }
    
    public void setVVillageName(String VVillageName) {
        this.VVillageName = VVillageName;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getMsPatients() {
        return this.msPatients;
    }
    
    public void setMsPatients(Set msPatients) {
        this.msPatients = msPatients;
    }
   








}