package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsWarehouse generated by MyEclipse - Hibernate Tools
 */

public class MsWarehouse  implements java.io.Serializable {


    // Fields    

     private Integer NWhouseId;
     private MsWarehouse msWarehouse;
     private MsCoa msCoa;
     private String VWhouseCode;
     private String VWhouseName;
     private String VWhouseLoc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbItemInventories = new HashSet(0);
     private Set msWarehouses = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsWarehouse() {
    }

	/** minimal constructor */
    public MsWarehouse(Integer NWhouseId, String VWhouseCode, String VWhouseName, String VWhouseLoc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NWhouseId = NWhouseId;
        this.VWhouseCode = VWhouseCode;
        this.VWhouseName = VWhouseName;
        this.VWhouseLoc = VWhouseLoc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }
    
    /** full constructor */
    public MsWarehouse(Integer NWhouseId, MsWarehouse msWarehouse, String VWhouseCode, String VWhouseName, String VWhouseLoc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbItemInventories, Set msWarehouses) {
        this.NWhouseId = NWhouseId;
        this.msWarehouse = msWarehouse;
        this.VWhouseCode = VWhouseCode;
        this.VWhouseName = VWhouseName;
        this.VWhouseLoc = VWhouseLoc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbItemInventories = tbItemInventories;
        this.msWarehouses = msWarehouses;
    }

   
    // Property accessors

    public Integer getNWhouseId() {
        return this.NWhouseId;
    }
    
    public void setNWhouseId(Integer NWhouseId) {
        this.NWhouseId = NWhouseId;
    }

    public MsWarehouse getMsWarehouse() {
        return this.msWarehouse;
    }
    
    public void setMsWarehouse(MsWarehouse msWarehouse) {
        this.msWarehouse = msWarehouse;
    }

    public String getVWhouseCode() {
        return this.VWhouseCode;
    }
    
    public void setVWhouseCode(String VWhouseCode) {
        this.VWhouseCode = VWhouseCode;
    }

    public String getVWhouseName() {
        return this.VWhouseName;
    }
    
    public void setVWhouseName(String VWhouseName) {
        this.VWhouseName = VWhouseName;
    }

    public String getVWhouseLoc() {
        return this.VWhouseLoc;
    }
    
    public void setVWhouseLoc(String VWhouseLoc) {
        this.VWhouseLoc = VWhouseLoc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbItemInventories() {
        return this.tbItemInventories;
    }
    
    public void setTbItemInventories(Set tbItemInventories) {
        this.tbItemInventories = tbItemInventories;
    }

    public Set getMsWarehouses() {
        return this.msWarehouses;
    }
    
    public void setMsWarehouses(Set msWarehouses) {
        this.msWarehouses = msWarehouses;
    }

	public MsCoa getMsCoa() {
		return msCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		this.msCoa = msCoa;
	}
   








}