package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbAccountPayableDetail generated by MyEclipse - Hibernate Tools
 */

public class TbAccountPayableDetail  implements java.io.Serializable {


    // Fields    

     private Integer NApdId;
     private TbAccountPayable tbAccountPayable;
     private String VJournalBatchId;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbAccountPayableDetail() {
    }

    
    /** full constructor */
    public TbAccountPayableDetail(TbAccountPayable tbAccountPayable, String VJournalBatchId, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange) {
        this.tbAccountPayable = tbAccountPayable;
        this.VJournalBatchId = VJournalBatchId;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNApdId() {
        return this.NApdId;
    }
    
    public void setNApdId(Integer NApdId) {
        this.NApdId = NApdId;
    }

    public TbAccountPayable getTbAccountPayable() {
        return this.tbAccountPayable;
    }
    
    public void setTbAccountPayable(TbAccountPayable tbAccountPayable) {
        this.tbAccountPayable = tbAccountPayable;
    }

    public String getVJournalBatchId() {
        return this.VJournalBatchId;
    }
    
    public void setVJournalBatchId(String VJournalBatchId) {
        this.VJournalBatchId = VJournalBatchId;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}