package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbBedOccupancyId generated by MyEclipse - Hibernate Tools
 */

public class TbBedOccupancyId  implements java.io.Serializable {


    // Fields    

     private TbRegistration tbRegistration;
     private MsBed msBed;
     private Date DWhnCreate;


    // Constructors

    /** default constructor */
    public TbBedOccupancyId() {
    }

    
    /** full constructor */
    public TbBedOccupancyId(TbRegistration tbRegistration, MsBed msBed, Date DWhnCreate) {
        this.tbRegistration = tbRegistration;
        this.msBed = msBed;
        this.DWhnCreate = DWhnCreate;
    }

   
    // Property accessors

    public TbRegistration getTbRegistration() {
        return this.tbRegistration;
    }
    
    public void setTbRegistration(TbRegistration tbRegistration) {
        this.tbRegistration = tbRegistration;
    }

    public MsBed getMsBed() {
        return this.msBed;
    }
    
    public void setMsBed(MsBed msBed) {
        this.msBed = msBed;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbBedOccupancyId) ) return false;
		 TbBedOccupancyId castOther = ( TbBedOccupancyId ) other; 
         
		 return ( (this.getTbRegistration()==castOther.getTbRegistration()) || ( this.getTbRegistration()!=null && castOther.getTbRegistration()!=null && this.getTbRegistration().equals(castOther.getTbRegistration()) ) )
 && ( (this.getMsBed()==castOther.getMsBed()) || ( this.getMsBed()!=null && castOther.getMsBed()!=null && this.getMsBed().equals(castOther.getMsBed()) ) )
 && ( (this.getDWhnCreate()==castOther.getDWhnCreate()) || ( this.getDWhnCreate()!=null && castOther.getDWhnCreate()!=null && this.getDWhnCreate().equals(castOther.getDWhnCreate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTbRegistration() == null ? 0 : this.getTbRegistration().hashCode() );
         result = 37 * result + ( getMsBed() == null ? 0 : this.getMsBed().hashCode() );
         result = 37 * result + ( getDWhnCreate() == null ? 0 : this.getDWhnCreate().hashCode() );
         return result;
   }   





}