package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbBedOccupancy generated by MyEclipse - Hibernate Tools
 */

public class TbBedOccupancy  implements java.io.Serializable {


    // Fields    

     private TbBedOccupancyId id;
     private Date DCheckInTime;
     private Date DCheckOutTime;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private String VOutNote;


    // Constructors

    /** default constructor */
    public TbBedOccupancy() {
    }

	/** minimal constructor */
    public TbBedOccupancy(TbBedOccupancyId id, Date DCheckInTime) {
        this.id = id;
        this.DCheckInTime = DCheckInTime;
    }
    
    /** full constructor */
    public TbBedOccupancy(TbBedOccupancyId id, Date DCheckInTime, Date DCheckOutTime, String VWhoCreate, String VWhoChange, Date DWhnChange, String VOutNote) {
        this.id = id;
        this.DCheckInTime = DCheckInTime;
        this.DCheckOutTime = DCheckOutTime;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.VOutNote = VOutNote;
    }

   
    // Property accessors

    public TbBedOccupancyId getId() {
        return this.id;
    }
    
    public void setId(TbBedOccupancyId id) {
        this.id = id;
    }

    public Date getDCheckInTime() {
        return this.DCheckInTime;
    }
    
    public void setDCheckInTime(Date DCheckInTime) {
        this.DCheckInTime = DCheckInTime;
    }

    public Date getDCheckOutTime() {
        return this.DCheckOutTime;
    }
    
    public void setDCheckOutTime(Date DCheckOutTime) {
        this.DCheckOutTime = DCheckOutTime;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVOutNote() {
        return this.VOutNote;
    }
    
    public void setVOutNote(String VOutNote) {
        this.VOutNote = VOutNote;
    }
   








}