package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbBedTrx generated by MyEclipse - Hibernate Tools
 */

public class TbBedTrx  implements java.io.Serializable {


    // Fields    

     private Integer NBtrxId;
     private TbExamination tbExamination;
     private MsBed msBed;
     private MsPatient msPatient;
     private Date DDateFrom;
     private Date DDateTo;
     private short NTotalHour;
     private String VWhoCreate;
     private Date DWhoCreate;
     private String VWhoChange;
     private Date DWhoChange;
     private double NFee;
     private String VDiscType;
     private double NDiscAmount;
     private double NAmountAfterDisc;


    // Constructors

    /** default constructor */
    public TbBedTrx() {
    }

	/** minimal constructor */
    public TbBedTrx(Integer NBtrxId, TbExamination tbExamination, MsBed msBed) {
        this.NBtrxId = NBtrxId;
        this.tbExamination = tbExamination;
        this.msBed = msBed;
    }
    
   
    // Property accessors

    public Integer getNBtrxId() {
        return this.NBtrxId;
    }
    
    public void setNBtrxId(Integer NBtrxId) {
        this.NBtrxId = NBtrxId;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }

    public MsBed getMsBed() {
        return this.msBed;
    }
    
    public void setMsBed(MsBed msBed) {
        this.msBed = msBed;
    }


    public MsPatient getMsPatient() {
        return this.msPatient;
    }
    
    public void setMsPatient(MsPatient msPatient) {
        this.msPatient = msPatient;
    }

    public Date getDDateFrom() {
        return this.DDateFrom;
    }
    
    public void setDDateFrom(Date DDateFrom) {
        this.DDateFrom = DDateFrom;
    }

    public Date getDDateTo() {
        return this.DDateTo;
    }
    
    public void setDDateTo(Date DDateTo) {
        this.DDateTo = DDateTo;
    }

    public short getNTotalHour() {
        return this.NTotalHour;
    }
    
    public void setNTotalHour(short NTotalHour) {
        this.NTotalHour = NTotalHour;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhoCreate() {
        return this.DWhoCreate;
    }
    
    public void setDWhoCreate(Date DWhoCreate) {
        this.DWhoCreate = DWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhoChange() {
        return this.DWhoChange;
    }
    
    public void setDWhoChange(Date DWhoChange) {
        this.DWhoChange = DWhoChange;
    }

    public double getNFee() {
        return this.NFee;
    }
    
    public void setNFee(double NFee) {
        this.NFee = NFee;
    }

    public String getVDiscType() {
        return this.VDiscType;
    }
    
    public void setVDiscType(String VDiscType) {
        this.VDiscType = VDiscType;
    }

    public double getNDiscAmount() {
        return this.NDiscAmount;
    }
    
    public void setNDiscAmount(double NDiscAmount) {
        this.NDiscAmount = NDiscAmount;
    }

    public double getNAmountAfterDisc() {
        return this.NAmountAfterDisc;
    }
    
    public void setNAmountAfterDisc(double NAmountAfterDisc) {
        this.NAmountAfterDisc = NAmountAfterDisc;
    }
   








}