package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbBundledTreatUsedTrx generated by MyEclipse - Hibernate Tools
 */

public class TbBundledTreatUsedTrx  implements java.io.Serializable {


    // Fields    

     private Integer NBtreatUsed;
     private TbBundledTrx tbBundledTrx;
     private MsTreatment msTreatment;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Date DWhnCreate;
     private Double NSellingPrice;
     private MsCoa msCoa;


    // Constructors

    public Double getNSellingPrice() {
		return NSellingPrice;
	}

	public void setNSellingPrice(Double sellingPrice) {
		NSellingPrice = sellingPrice;
	}

	/** default constructor */
    public TbBundledTreatUsedTrx() {
    }

	/** minimal constructor */
    public TbBundledTreatUsedTrx(Integer NBtreatUsed) {
        this.NBtreatUsed = NBtreatUsed;
    }
    
   

   
    // Property accessors

    public Integer getNBtreatUsed() {
        return this.NBtreatUsed;
    }
    
    public void setNBtreatUsed(Integer NBtreatUsed) {
        this.NBtreatUsed = NBtreatUsed;
    }

   

    public MsTreatment getMsTreatment() {
        return this.msTreatment;
    }
    
    public void setMsTreatment(MsTreatment msTreatment) {
        this.msTreatment = msTreatment;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

	public MsCoa getMsCoa() {
		return msCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		this.msCoa = msCoa;
	}

	public TbBundledTrx getTbBundledTrx() {
		return tbBundledTrx;
	}

	public void setTbBundledTrx(TbBundledTrx tbBundledTrx) {
		this.tbBundledTrx = tbBundledTrx;
	}
   








}