package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbBundledItemUsedTrx generated by MyEclipse - Hibernate Tools
 */

public class TbBundledItemUsedTrx  implements java.io.Serializable {


    // Fields    

     private Integer NBitemUsed;
     private MsItem msItem;
     private TbBatchItem tbBatchItem;
     private TbBundledTrx tbBundledTrx;
     private short NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Date DWhnCreate;
     private Double NSellingPrice;


    // Constructors

    public Double getNSellingPrice() {
		return NSellingPrice;
	}

	public void setNSellingPrice(Double sellingPrice) {
		NSellingPrice = sellingPrice;
	}

	/** default constructor */
    public TbBundledItemUsedTrx() {
    }

	/** minimal constructor */
    public TbBundledItemUsedTrx(Integer NBitemUsed, MsItem msItem) {
        this.NBitemUsed = NBitemUsed;
        this.msItem = msItem;
    }
    
   

   
    // Property accessors

    public Integer getNBitemUsed() {
        return this.NBitemUsed;
    }
    
    public void setNBitemUsed(Integer NBitemUsed) {
        this.NBitemUsed = NBitemUsed;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbBatchItem getTbBatchItem() {
        return this.tbBatchItem;
    }
    
    public void setTbBatchItem(TbBatchItem tbBatchItem) {
        this.tbBatchItem = tbBatchItem;
    }

  

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }
   
    
    public TbBundledItemUsedTrx clone(){
    	
    	TbBundledItemUsedTrx trx = new TbBundledItemUsedTrx();
    	trx.setDWhnChange(this.DWhnChange);
    	trx.setDWhnCreate(this.DWhnCreate);
    	trx.setMsItem(this.msItem);
    	trx.setNBitemUsed(this.NBitemUsed);
    	trx.setNQty(this.NQty);
    	trx.setTbBatchItem(this.tbBatchItem);
    	trx.setTbBundledTrx(this.tbBundledTrx);
    	trx.setVWhoChange(this.VWhoChange);
    	trx.setVWhoCreate(this.VWhoCreate);
    	trx.setNSellingPrice(this.NSellingPrice);
    	
       	return trx;
    }

	public TbBundledTrx getTbBundledTrx() {
		return tbBundledTrx;
	}

	public void setTbBundledTrx(TbBundledTrx tbBundledTrx) {
		this.tbBundledTrx = tbBundledTrx;
	}

	







}