package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbBundledTrx generated by MyEclipse - Hibernate Tools
 */

public class TbBundledTrx  implements java.io.Serializable {


    // Fields    

     private Integer NBundledTrxId;
     private TbExamination tbExamination;
     private MsTreatmentFee msTreatmentFee;
     private double NAmountTrx;
     private short NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private String VDiscType;
     private double NDiscAmount;
     private double NAmountAfterDisc;
     
     
     private Set tbBundledTreatUsedTrxes = new HashSet(0);
     private Set tbBundledItemUsedTrxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbBundledTrx() {
    }

	
    

   
    // Property accessors

    public Integer getNBundledTrxId() {
        return this.NBundledTrxId;
    }
    
    public void setNBundledTrxId(Integer NBundledTrxId) {
        this.NBundledTrxId = NBundledTrxId;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }

   

    public double getNAmountTrx() {
        return this.NAmountTrx;
    }
    
    public void setNAmountTrx(double NAmountTrx) {
        this.NAmountTrx = NAmountTrx;
    }

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVDiscType() {
        return this.VDiscType;
    }
    
    public void setVDiscType(String VDiscType) {
        this.VDiscType = VDiscType;
    }

    public double getNDiscAmount() {
        return this.NDiscAmount;
    }
    
    public void setNDiscAmount(double NDiscAmount) {
        this.NDiscAmount = NDiscAmount;
    }

    public double getNAmountAfterDisc() {
        return this.NAmountAfterDisc;
    }
    
    public void setNAmountAfterDisc(double NAmountAfterDisc) {
        this.NAmountAfterDisc = NAmountAfterDisc;
    }

	public MsTreatmentFee getMsTreatmentFee() {
		return msTreatmentFee;
	}

	public void setMsTreatmentFee(MsTreatmentFee msTreatmentFee) {
		this.msTreatmentFee = msTreatmentFee;
	}





	public Set getTbBundledItemUsedTrxes() {
		return tbBundledItemUsedTrxes;
	}





	public void setTbBundledItemUsedTrxes(Set tbBundledItemUsedTrxes) {
		this.tbBundledItemUsedTrxes = tbBundledItemUsedTrxes;
	}





	public Set getTbBundledTreatUsedTrxes() {
		return tbBundledTreatUsedTrxes;
	}





	public void setTbBundledTreatUsedTrxes(Set tbBundledTreatUsedTrxes) {
		this.tbBundledTreatUsedTrxes = tbBundledTreatUsedTrxes;
	}
   








}