package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbDeliveryOrderDetail generated by MyEclipse - Hibernate Tools
 */

public class TbDeliveryOrderDetail  implements java.io.Serializable {


    // Fields    

     private Integer NDoDetId;
     private MsItem msItem;
     private TbDeliveryOrder tbDeliveryOrder;
     private TbPurchaseOrderDetail tbPurchaseOrderDetail;
     private short NDoDetQty;
     private Short NDoBonusQty;
     private Double NSubtotal;
     private Integer NMultipleM;
     private String VEndM;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbDeliveryOrderDetail() {
    }

	/** minimal constructor */
    public TbDeliveryOrderDetail(Integer NDoDetId, MsItem msItem, TbDeliveryOrder tbDeliveryOrder, short NDoDetQty,String VWhoCreate, Date DWhnCreate) {
        this.NDoDetId = NDoDetId;
        this.msItem = msItem;
        this.tbDeliveryOrder = tbDeliveryOrder;
        this.NDoDetQty = NDoDetQty;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbDeliveryOrderDetail(Integer NDoDetId, MsItem msItem, TbDeliveryOrder tbDeliveryOrder, short NDoDetQty, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NDoDetId = NDoDetId;
        this.msItem = msItem;
        this.tbDeliveryOrder = tbDeliveryOrder;
        this.NDoDetQty = NDoDetQty;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }
   
    // Property accessors

    public Double getNSubtotal() {
		return NSubtotal;
	}

	public Short getNDoBonusQty() {
		if (NDoBonusQty == null)
			return new Integer(0).shortValue();
		return NDoBonusQty;
	}

	public void setNDoBonusQty(Short doBonusQty) {
		NDoBonusQty = doBonusQty;
	}

	public void setNSubtotal(Double subtotal) {
		NSubtotal = subtotal;
	}
	
	public Integer getNDoDetId() {
        return this.NDoDetId;
    }
    
    public void setNDoDetId(Integer NDoDetId) {
        this.NDoDetId = NDoDetId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbDeliveryOrder getTbDeliveryOrder() {
        return this.tbDeliveryOrder;
    }
    
    public void setTbDeliveryOrder(TbDeliveryOrder tbDeliveryOrder) {
        this.tbDeliveryOrder = tbDeliveryOrder;
    }

    public short getNDoDetQty() {
        return this.NDoDetQty;
    }
    
    public void setNDoDetQty(short NDoDetQty) {
        this.NDoDetQty = NDoDetQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public TbPurchaseOrderDetail getTbPurchaseOrderDetail() {
		return tbPurchaseOrderDetail;
	}

	public void setTbPurchaseOrderDetail(TbPurchaseOrderDetail tbPurchaseOrderDetail) {
		this.tbPurchaseOrderDetail = tbPurchaseOrderDetail;
	}

	public Integer getNMultipleM() {
		return NMultipleM;
	}

	public void setNMultipleM(Integer multipleM) {
		NMultipleM = multipleM;
	}

	public String getVEndM() {
		return VEndM;
	}

	public void setVEndM(String endM) {
		VEndM = endM;
	}








}