package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbDiagnose generated by MyEclipse - Hibernate Tools
 */

public class TbDiagnose  implements java.io.Serializable {


    // Fields    

     public String getVSyntom() {
		return VSyntom;
	}


	public void setVSyntom(String vSyntom) {
		VSyntom = vSyntom;
	}


	 private Integer NDiagnoseId;
     private String VDoctorName;
     private String VUnitName;
     private TbMedicalRecord mr;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private short NCheckoutType;
     private short NConditionType;
     private short NDiagnoseType;
     private short NDeathType;
     private String VSyntom;
     private String VReceipt;
     
     private Set tbViolents = new HashSet(0);
     private Set tbIcdDiagnoses = new HashSet(0);
     private Set tbStillbirths = new HashSet(0);
     private Set tbIllnesses = new HashSet(0);
     private Set tbOperations = new HashSet(0);
     private Set tbPregnancies = new HashSet(0);
     private Set tbIcd9Diagnoses = new HashSet(0);
     private Integer NRegId;

     
    public String getVReceipt() {
 		return VReceipt;
 	}


 	public void setVReceipt(String vReceipt) {
 		VReceipt = vReceipt;
 	}


    // Constructors

    public Integer getNRegId() {
		return NRegId;
	}


	public void setNRegId(Integer nRegId) {
		NRegId = nRegId;
	}


	/** default constructor */
    public TbDiagnose() {
    }

    
    /** full constructor */
    public TbDiagnose(String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, short NCheckoutType, short NConditionType, short NDiagnoseType, short NDeathType, Set tbViolents, Set tbIcdDiagnoses, Set tbStillbirths, Set tbIllnesses, Set tbOperations, Set tbPregnancies, Set tbIcd9Diagnoses) {
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.NCheckoutType = NCheckoutType;
        this.NConditionType = NConditionType;
        this.NDiagnoseType = NDiagnoseType;
        this.NDeathType = NDeathType;
        this.tbViolents = tbViolents;
        this.tbIcdDiagnoses = tbIcdDiagnoses;
        this.tbStillbirths = tbStillbirths;
        this.tbIllnesses = tbIllnesses;
        this.tbOperations = tbOperations;
        this.tbPregnancies = tbPregnancies;
        this.tbIcd9Diagnoses = tbIcd9Diagnoses;
    }

   
    // Property accessors

    public Integer getNDiagnoseId() {
        return this.NDiagnoseId;
    }
    
    public void setNDiagnoseId(Integer NDiagnoseId) {
        this.NDiagnoseId = NDiagnoseId;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public short getNCheckoutType() {
        return this.NCheckoutType;
    }
    
    public void setNCheckoutType(short NCheckoutType) {
        this.NCheckoutType = NCheckoutType;
    }

    public short getNConditionType() {
        return this.NConditionType;
    }
    
    public void setNConditionType(short NConditionType) {
        this.NConditionType = NConditionType;
    }

    public short getNDiagnoseType() {
        return this.NDiagnoseType;
    }
    
    public void setNDiagnoseType(short NDiagnoseType) {
        this.NDiagnoseType = NDiagnoseType;
    }

    public short getNDeathType() {
        return this.NDeathType;
    }
    
    public void setNDeathType(short NDeathType) {
        this.NDeathType = NDeathType;
    }

    public Set getTbViolents() {
        return this.tbViolents;
    }
    
    public void setTbViolents(Set tbViolents) {
        this.tbViolents = tbViolents;
    }

    public Set getTbIcdDiagnoses() {
        return this.tbIcdDiagnoses;
    }
    
    public void setTbIcdDiagnoses(Set tbIcdDiagnoses) {
        this.tbIcdDiagnoses = tbIcdDiagnoses;
    }

    public Set getTbStillbirths() {
        return this.tbStillbirths;
    }
    
    public void setTbStillbirths(Set tbStillbirths) {
        this.tbStillbirths = tbStillbirths;
    }

    public Set getTbIllnesses() {
        return this.tbIllnesses;
    }
    
    public void setTbIllnesses(Set tbIllnesses) {
        this.tbIllnesses = tbIllnesses;
    }

    public Set getTbOperations() {
        return this.tbOperations;
    }
    
    public void setTbOperations(Set tbOperations) {
        this.tbOperations = tbOperations;
    }

    public Set getTbPregnancies() {
        return this.tbPregnancies;
    }
    
    public void setTbPregnancies(Set tbPregnancies) {
        this.tbPregnancies = tbPregnancies;
    }

    public Set getTbIcd9Diagnoses() {
        return this.tbIcd9Diagnoses;
    }
    
    public void setTbIcd9Diagnoses(Set tbIcd9Diagnoses) {
        this.tbIcd9Diagnoses = tbIcd9Diagnoses;
    }


	public String getVDoctorName() {
		return VDoctorName;
	}


	public void setVDoctorName(String doctorName) {
		VDoctorName = doctorName;
	}


	public String getVUnitName() {
		return VUnitName;
	}


	public void setVUnitName(String unitName) {
		VUnitName = unitName;
	}


	public TbMedicalRecord getMr() {
		return mr;
	}


	public void setMr(TbMedicalRecord mr) {
		this.mr = mr;
	}
   








}