package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbDrugIngredientsDetail generated by MyEclipse - Hibernate Tools
 */

public class TbDrugIngredientsDetail  implements java.io.Serializable {


    // Fields    

     private Integer NDingrDetId;
     private MsItem msItem;
     private TbBatchItem tbBatchItem;
     private TbDrugIngredients tbDrugIngredients;
     private Float NDingrDetQty;
     private String VDingrDetQuantify;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbDrugIngredientsDetail() {
    }

	/** minimal constructor */
    public TbDrugIngredientsDetail(Integer NDingrDetId, TbDrugIngredients tbDrugIngredients, Float NDingrDetQty, String VDingrDetQuantify, String VWhoCreate, Date DWhnCreate) {
        this.NDingrDetId = NDingrDetId;
        this.tbDrugIngredients = tbDrugIngredients;
        this.NDingrDetQty = NDingrDetQty;
        this.VDingrDetQuantify = VDingrDetQuantify;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbDrugIngredientsDetail(Integer NDingrDetId, MsItem msItem, TbDrugIngredients tbDrugIngredients, Float NDingrDetQty, String VDingrDetQuantify, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NDingrDetId = NDingrDetId;
        this.msItem = msItem;
        this.tbDrugIngredients = tbDrugIngredients;
        this.NDingrDetQty = NDingrDetQty;
        this.VDingrDetQuantify = VDingrDetQuantify;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNDingrDetId() {
        return this.NDingrDetId;
    }
    
    public void setNDingrDetId(Integer NDingrDetId) {
        this.NDingrDetId = NDingrDetId;
    }

   
    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbDrugIngredients getTbDrugIngredients() {
        return this.tbDrugIngredients;
    }
    
    public void setTbDrugIngredients(TbDrugIngredients tbDrugIngredients) {
        this.tbDrugIngredients = tbDrugIngredients;
    }

    public Float getNDingrDetQty() {
        return this.NDingrDetQty;
    }
    
    public void setNDingrDetQty(Float NDingrDetQty) {
        this.NDingrDetQty = NDingrDetQty;
    }

    public String getVDingrDetQuantify() {
        return this.VDingrDetQuantify;
    }
    
    public void setVDingrDetQuantify(String VDingrDetQuantify) {
        this.VDingrDetQuantify = VDingrDetQuantify;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public TbBatchItem getTbBatchItem() {
		return tbBatchItem;
	}

	public void setTbBatchItem(TbBatchItem tbBatchItem) {
		this.tbBatchItem = tbBatchItem;
	}
   

	public TbDrugIngredientsDetail clone(){
		TbDrugIngredientsDetail detil = new TbDrugIngredientsDetail();
		
		detil.setDWhnChange(this.DWhnChange);
		detil.setDWhnCreate(this.DWhnCreate);
		detil.setMsItem(this.msItem);
		detil.setNDingrDetId(this.NDingrDetId);
		detil.setNDingrDetQty(this.NDingrDetQty);
		detil.setTbBatchItem(this.tbBatchItem);
		detil.setTbDrugIngredients(this.tbDrugIngredients);
		detil.setVDingrDetQuantify(this.VDingrDetQuantify);
		detil.setVWhoChange(this.VWhoChange);
		detil.setVWhoCreate(this.VWhoCreate);
		
		return detil;
	}






}