package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbExamination generated by MyEclipse - Hibernate Tools
 */

public class TbExamination  implements java.io.Serializable {


    // Fields    

     private Integer NExamId;
     private TbRegistration tbRegistration;
     private MsPatientEscort msPatientEscort;
     private MsPatient msPatient;
     private TbPatientBill tbPatientBill;
     private String VNoteNo;
     private Short NPaymentStatus;
     private String VCancelationStatus;
     private String VCancelationNote;
     private String VRecipeNo;
     private Integer NExamStatus;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Double total;
     private MsUnit msUnit;
     private Integer antrianStatus;
     
     public Integer getAntrianStatus() {
		return antrianStatus;
	}

	public void setAntrianStatus(Integer antrianStatus) {
		this.antrianStatus = antrianStatus;
	}

	private Date DValidationDate;
     private MsShift msShift;
     private Set tbExamDetails = new HashSet(0);
     private Set tbPatientBills = new HashSet(0);
     private Set tbLaboratoryResults = new HashSet(0);
     
     private Set tbBedTrx = new HashSet(0);
     private Set tbBundledTrx = new HashSet(0);
     private Set tbItemTrx = new HashSet(0);
     private Set tbMiscTrx = new HashSet(0);
     private Set tbTreatmentTrx = new HashSet(0);
     private Set tbDrugIngredients = new HashSet(0);
     

    // Constructors

	/** default constructor */
    public TbExamination() {
    }

	/** minimal constructor */
    public TbExamination(Integer NExamId, String VNoteNo) {
        this.NExamId = NExamId;
        this.VNoteNo = VNoteNo;
    }
    
    /** full constructor */
    public TbExamination(Integer NExamId, TbRegistration tbRegistration, MsPatientEscort msPatientEscort, MsPatient msPatient, String VNoteNo, String VValidateStatus, String VCancelationStatus, String VCancelationNote, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbExamDetails, Set tbPatientBills, Set tbLaboratoryResults) {
        this.NExamId = NExamId;
        this.tbRegistration = tbRegistration;
        this.msPatientEscort = msPatientEscort;
        this.msPatient = msPatient;
        this.VNoteNo = VNoteNo;
//        this.VValidateStatus = VValidateStatus;
        this.VCancelationStatus = VCancelationStatus;
        this.VCancelationNote = VCancelationNote;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbExamDetails = tbExamDetails;
        this.tbPatientBills = tbPatientBills;
        this.tbLaboratoryResults = tbLaboratoryResults;
    }

   
    // Property accessors

    public Integer getNExamId() {
        return this.NExamId;
    }
    
    public void setNExamId(Integer NExamId) {
        this.NExamId = NExamId;
    }

    public TbRegistration getTbRegistration() {
        return this.tbRegistration;
    }
    
    public void setTbRegistration(TbRegistration tbRegistration) {
        this.tbRegistration = tbRegistration;
    }

    public MsPatientEscort getMsPatientEscort() {
        return this.msPatientEscort;
    }
    
    public void setMsPatientEscort(MsPatientEscort msPatientEscort) {
        this.msPatientEscort = msPatientEscort;
    }

    public String getVRecipeNo() {
		return VRecipeNo;
	}

	public void setVRecipeNo(String recipeNo) {
		VRecipeNo = recipeNo;
	}

	public MsPatient getMsPatient() {
        return this.msPatient;
    }
    
    public void setMsPatient(MsPatient msPatient) {
        this.msPatient = msPatient;
    }

    public String getVNoteNo() {
        return this.VNoteNo;
    }
    
    public void setVNoteNo(String VNoteNo) {
        this.VNoteNo = VNoteNo;
    }

  

    public Short getNPaymentStatus() {
		return NPaymentStatus;
	}

	public void setNPaymentStatus(Short paymentStatus) {
		NPaymentStatus = paymentStatus;
	}

	public String getVCancelationStatus() {
        return this.VCancelationStatus;
    }
    
    public void setVCancelationStatus(String VCancelationStatus) {
        this.VCancelationStatus = VCancelationStatus;
    }

    public String getVCancelationNote() {
        return this.VCancelationNote;
    }
    
    public void setVCancelationNote(String VCancelationNote) {
        this.VCancelationNote = VCancelationNote;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbExamDetails() {
        return this.tbExamDetails;
    }
    
    public void setTbExamDetails(Set tbExamDetails) {
        this.tbExamDetails = tbExamDetails;
    }

    public Set getTbPatientBills() {
        return this.tbPatientBills;
    }
    
    public void setTbPatientBills(Set tbPatientBills) {
        this.tbPatientBills = tbPatientBills;
    }

    public Set getTbLaboratoryResults() {
        return this.tbLaboratoryResults;
    }
    
    public void setTbLaboratoryResults(Set tbLaboratoryResults) {
        this.tbLaboratoryResults = tbLaboratoryResults;
    }

	public Integer getNExamStatus() {
		return NExamStatus;
	}

	public void setNExamStatus(Integer examStatus) {
		NExamStatus = examStatus;
	}

	public TbPatientBill getTbPatientBill() {
		return tbPatientBill;
	}

	public void setTbPatientBill(TbPatientBill tbPatientBill) {
		this.tbPatientBill = tbPatientBill;
	}

	public Set getTbBedTrx() {
		return tbBedTrx;
	}

	public void setTbBedTrx(Set tbBedTrx) {
		this.tbBedTrx = tbBedTrx;
	}

	public MsUnit getMsUnit() {
		return msUnit;
	}

	public void setMsUnit(MsUnit msUnit) {
		this.msUnit = msUnit;
	}

	public Double getTotal() {
		return total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Set getTbBundledTrx() {
		return tbBundledTrx;
	}

	public void setTbBundledTrx(Set tbBundledTrx) {
		this.tbBundledTrx = tbBundledTrx;
	}

	public Set getTbItemTrx() {
		return tbItemTrx;
	}

	public void setTbItemTrx(Set tbItemTrx) {
		this.tbItemTrx = tbItemTrx;
	}

	public Set getTbMiscTrx() {
		return tbMiscTrx;
	}

	public void setTbMiscTrx(Set tbMiscTrx) {
		this.tbMiscTrx = tbMiscTrx;
	}
	
    public Set getTbTreatmentTrx() {
		return tbTreatmentTrx;
	}

	public void setTbTreatmentTrx(Set tbTreatmentTrx) {
		this.tbTreatmentTrx = tbTreatmentTrx;
	}

	public Set getTbDrugIngredients() {
		return tbDrugIngredients;
	}

	public void setTbDrugIngredients(Set tbDrugIngredients) {
		this.tbDrugIngredients = tbDrugIngredients;
	}

	public Date getDValidationDate() {
		return DValidationDate;
	}

	public void setDValidationDate(Date validationDate) {
		DValidationDate = validationDate;
	}

	public MsShift getMsShift() {
		return msShift;
	}

	public void setMsShift(MsShift msShift) {
		this.msShift = msShift;
	}

}