package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbGakinNote generated by MyEclipse - Hibernate Tools
 */

public class TbGakinNote  implements java.io.Serializable {


    // Fields    

     private Integer NGakinNoteId;
     private TbPatientBill tbPatientBill;
     private String VGakinNoteCode;
     private double NAmountCovered;
     private String VDescCovered;
     private String VGakinCardNo;
     private String VTreatmentOnUnit;
     private String VNoRefLetterLurah;
     private Date DDateRefLetterLurah;
     private String VCamatApprovalNo;
     private Date DCamatApprovalDate;
     private String VNoRefLetterPanti;
     private Date DDateRefLetterPanti;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DHwnChange;


    // Constructors

    /** default constructor */
    public TbGakinNote() {
    }

	/** minimal constructor */
    public TbGakinNote(Integer NGakinNoteId, TbPatientBill tbPatientBill) {
        this.NGakinNoteId = NGakinNoteId;
        this.tbPatientBill = tbPatientBill;
    }
    
    /** full constructor */
    public TbGakinNote(Integer NGakinNoteId, TbPatientBill tbPatientBill, String VGakinNoteCode, double NAmountCovered, String VDescCovered, String VGakinCardNo, String VTreatmentOnUnit, String VNoRefLetterLurah, Date DDateRefLetterLurah, String VCamatApprovalNo, Date DCamatApprovalDate, String VNoRefLetterPanti, Date DDateRefLetterPanti, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DHwnChange) {
        this.NGakinNoteId = NGakinNoteId;
        this.tbPatientBill = tbPatientBill;
        this.VGakinNoteCode = VGakinNoteCode;
        this.NAmountCovered = NAmountCovered;
        this.VDescCovered = VDescCovered;
        this.VGakinCardNo = VGakinCardNo;
        this.VTreatmentOnUnit = VTreatmentOnUnit;
        this.VNoRefLetterLurah = VNoRefLetterLurah;
        this.DDateRefLetterLurah = DDateRefLetterLurah;
        this.VCamatApprovalNo = VCamatApprovalNo;
        this.DCamatApprovalDate = DCamatApprovalDate;
        this.VNoRefLetterPanti = VNoRefLetterPanti;
        this.DDateRefLetterPanti = DDateRefLetterPanti;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DHwnChange = DHwnChange;
    }

   
    // Property accessors

    public Integer getNGakinNoteId() {
        return this.NGakinNoteId;
    }
    
    public void setNGakinNoteId(Integer NGakinNoteId) {
        this.NGakinNoteId = NGakinNoteId;
    }

    public TbPatientBill getTbPatientBill() {
        return this.tbPatientBill;
    }
    
    public void setTbPatientBill(TbPatientBill tbPatientBill) {
        this.tbPatientBill = tbPatientBill;
    }

    public String getVGakinNoteCode() {
        return this.VGakinNoteCode;
    }
    
    public void setVGakinNoteCode(String VGakinNoteCode) {
        this.VGakinNoteCode = VGakinNoteCode;
    }

    public double getNAmountCovered() {
        return this.NAmountCovered;
    }
    
    public void setNAmountCovered(double NAmountCovered) {
        this.NAmountCovered = NAmountCovered;
    }

    public String getVDescCovered() {
        return this.VDescCovered;
    }
    
    public void setVDescCovered(String VDescCovered) {
        this.VDescCovered = VDescCovered;
    }

    public String getVGakinCardNo() {
        return this.VGakinCardNo;
    }
    
    public void setVGakinCardNo(String VGakinCardNo) {
        this.VGakinCardNo = VGakinCardNo;
    }

    public String getVTreatmentOnUnit() {
        return this.VTreatmentOnUnit;
    }
    
    public void setVTreatmentOnUnit(String VTreatmentOnUnit) {
        this.VTreatmentOnUnit = VTreatmentOnUnit;
    }

    public String getVNoRefLetterLurah() {
        return this.VNoRefLetterLurah;
    }
    
    public void setVNoRefLetterLurah(String VNoRefLetterLurah) {
        this.VNoRefLetterLurah = VNoRefLetterLurah;
    }

    public Date getDDateRefLetterLurah() {
        return this.DDateRefLetterLurah;
    }
    
    public void setDDateRefLetterLurah(Date DDateRefLetterLurah) {
        this.DDateRefLetterLurah = DDateRefLetterLurah;
    }

    public String getVCamatApprovalNo() {
        return this.VCamatApprovalNo;
    }
    
    public void setVCamatApprovalNo(String VCamatApprovalNo) {
        this.VCamatApprovalNo = VCamatApprovalNo;
    }

    public Date getDCamatApprovalDate() {
        return this.DCamatApprovalDate;
    }
    
    public void setDCamatApprovalDate(Date DCamatApprovalDate) {
        this.DCamatApprovalDate = DCamatApprovalDate;
    }

    public String getVNoRefLetterPanti() {
        return this.VNoRefLetterPanti;
    }
    
    public void setVNoRefLetterPanti(String VNoRefLetterPanti) {
        this.VNoRefLetterPanti = VNoRefLetterPanti;
    }

    public Date getDDateRefLetterPanti() {
        return this.DDateRefLetterPanti;
    }
    
    public void setDDateRefLetterPanti(Date DDateRefLetterPanti) {
        this.DDateRefLetterPanti = DDateRefLetterPanti;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDHwnChange() {
        return this.DHwnChange;
    }
    
    public void setDHwnChange(Date DHwnChange) {
        this.DHwnChange = DHwnChange;
    }
   








}