package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbGroupPrivilege generated by MyEclipse - Hibernate Tools
 */

public class TbGroupPrivilege  implements java.io.Serializable {


    // Fields    

     private TbGroupPrivilegeId id;
     private String VAccessType;
     private String VWhocreate;
     private Date DWhncreate;
     private String VWhochange;
     private Date DWhnchange;


    // Constructors

    /** default constructor */
    public TbGroupPrivilege() {
    }

	/** minimal constructor */
    public TbGroupPrivilege(TbGroupPrivilegeId id, String VAccessType) {
        this.id = id;
        this.VAccessType = VAccessType;
    }
    
    /** full constructor */
    public TbGroupPrivilege(TbGroupPrivilegeId id, String VAccessType, String VWhocreate, Date DWhncreate, String VWhochange, Date DWhnchange) {
        this.id = id;
        this.VAccessType = VAccessType;
        this.VWhocreate = VWhocreate;
        this.DWhncreate = DWhncreate;
        this.VWhochange = VWhochange;
        this.DWhnchange = DWhnchange;
    }

   
    // Property accessors

    public TbGroupPrivilegeId getId() {
        return this.id;
    }
    
    public void setId(TbGroupPrivilegeId id) {
        this.id = id;
    }

    public String getVAccessType() {
        return this.VAccessType;
    }
    
    public void setVAccessType(String VAccessType) {
        this.VAccessType = VAccessType;
    }

    public String getVWhocreate() {
        return this.VWhocreate;
    }
    
    public void setVWhocreate(String VWhocreate) {
        this.VWhocreate = VWhocreate;
    }

    public Date getDWhncreate() {
        return this.DWhncreate;
    }
    
    public void setDWhncreate(Date DWhncreate) {
        this.DWhncreate = DWhncreate;
    }

    public String getVWhochange() {
        return this.VWhochange;
    }
    
    public void setVWhochange(String VWhochange) {
        this.VWhochange = VWhochange;
    }

    public Date getDWhnchange() {
        return this.DWhnchange;
    }
    
    public void setDWhnchange(Date DWhnchange) {
        this.DWhnchange = DWhnchange;
    }
   








}