package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbHistoryPosting generated by MyEclipse - Hibernate Tools
 */

public class TbHistoryPosting  implements java.io.Serializable {


    // Fields    

     private Integer NFlag;
     private Date DMove;
     private String VDesc;
     private short NStatus;
     private String VWhoMove;
     private Date DMoveBack;
     private String VWhoMoveBack;
     private String VReportName;


    // Constructors

    /** default constructor */
    public TbHistoryPosting() {
    }

    
    /** full constructor */
    public TbHistoryPosting(Date DMove, String VDesc, short NStatus, String VWhoMove, Date DMoveBack, String VWhoMoveBack) {
        this.DMove = DMove;
        this.VDesc = VDesc;
        this.NStatus = NStatus;
        this.VWhoMove = VWhoMove;
        this.DMoveBack = DMoveBack;
        this.VWhoMoveBack = VWhoMoveBack;
    }

   
    // Property accessors

    public Integer getNFlag() {
        return this.NFlag;
    }
    
    public void setNFlag(Integer NFlag) {
        this.NFlag = NFlag;
    }

    public Date getDMove() {
        return this.DMove;
    }
    
    public void setDMove(Date DMove) {
        this.DMove = DMove;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public short getNStatus() {
        return this.NStatus;
    }
    
    public void setNStatus(short NStatus) {
        this.NStatus = NStatus;
    }

    public String getVWhoMove() {
        return this.VWhoMove;
    }
    
    public void setVWhoMove(String VWhoMove) {
        this.VWhoMove = VWhoMove;
    }

    public Date getDMoveBack() {
        return this.DMoveBack;
    }
    
    public void setDMoveBack(Date DMoveBack) {
        this.DMoveBack = DMoveBack;
    }

    public String getVWhoMoveBack() {
        return this.VWhoMoveBack;
    }
    
    public void setVWhoMoveBack(String VWhoMoveBack) {
        this.VWhoMoveBack = VWhoMoveBack;
    }


	public String getVReportName() {
		return VReportName;
	}


	public void setVReportName(String reportName) {
		VReportName = reportName;
	}
   








}