package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.diagnose.MsIcd9cm;


/**
 * TbIcd9Diagnose generated by MyEclipse - Hibernate Tools
 */

public class TbIcd9Diagnose  implements java.io.Serializable {


    // Fields    

     private Integer NIcd9DiagnoseId;
     private TbDiagnose tbDiagnose;
     private MsIcd9cm msIcd9cm;
     private Date DWhnCreate;
     private Date DWhnChange;
     private String VWhoCreate;
     private String VWhoChange;


    // Constructors

    /** default constructor */
    public TbIcd9Diagnose() {
    }

    
    /** full constructor */
    public TbIcd9Diagnose(TbDiagnose tbDiagnose, MsIcd9cm msIcd9cm, Date DWhnCreate, Date DWhnChange, String VWhoCreate, String VWhoChange) {
        this.tbDiagnose = tbDiagnose;
        this.msIcd9cm = msIcd9cm;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
    }

   
    // Property accessors

    public Integer getNIcd9DiagnoseId() {
        return this.NIcd9DiagnoseId;
    }
    
    public void setNIcd9DiagnoseId(Integer NIcd9DiagnoseId) {
        this.NIcd9DiagnoseId = NIcd9DiagnoseId;
    }

    public TbDiagnose getTbDiagnose() {
        return this.tbDiagnose;
    }
    
    public void setTbDiagnose(TbDiagnose tbDiagnose) {
        this.tbDiagnose = tbDiagnose;
    }

    public MsIcd9cm getMsIcd9cm() {
        return this.msIcd9cm;
    }
    
    public void setMsIcd9cm(MsIcd9cm msIcd9cm) {
        this.msIcd9cm = msIcd9cm;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }
   








}