package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.diagnose.MsIcd;


/**
 * TbIcdDiagnose generated by MyEclipse - Hibernate Tools
 */

public class TbIcdDiagnose  implements java.io.Serializable {


    // Fields    

     private Integer NIcdDiagnoseId;
     private TbDiagnose tbDiagnose;
     private MsIcd msIcd;
     private short NType;
     private Date DWhnCreate;
     private Date DWhnChange;
     private String VWhoCreate;
     private String VWhoChange;
//     private String VSyntom;


    // Constructors
    /* 
    public String getVSyntom() {
		return VSyntom;
	}


	public void setVSyntom(String syntom) {
		VSyntom = syntom;
	}*/


	/** default constructor */
    public TbIcdDiagnose() {
    }

    
    /** full constructor */
    public TbIcdDiagnose(TbDiagnose tbDiagnose, MsIcd msIcd, short NType, Date DWhnCreate, Date DWhnChange, String VWhoCreate, String VWhoChange) {
        this.tbDiagnose = tbDiagnose;
        this.msIcd = msIcd;
        this.NType = NType;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
    }

   
    // Property accessors

    public Integer getNIcdDiagnoseId() {
        return this.NIcdDiagnoseId;
    }
    
    public void setNIcdDiagnoseId(Integer NIcdDiagnoseId) {
        this.NIcdDiagnoseId = NIcdDiagnoseId;
    }

    public TbDiagnose getTbDiagnose() {
        return this.tbDiagnose;
    }
    
    public void setTbDiagnose(TbDiagnose tbDiagnose) {
        this.tbDiagnose = tbDiagnose;
    }

    public MsIcd getMsIcd() {
        return this.msIcd;
    }
    
    public void setMsIcd(MsIcd msIcd) {
        this.msIcd = msIcd;
    }

    public short getNType() {
        return this.NType;
    }
    
    public void setNType(short NType) {
        this.NType = NType;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }
   








}