package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.diagnose.MsIcd;


/**
 * TbIllness generated by MyEclipse - Hibernate Tools
 */

public class TbIllness  implements java.io.Serializable {


    // Fields    

     private Integer NIllnessId;
     private TbDiagnose tbDiagnose;
     private MsIcd msIcd;
     private short NIllDuration;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private short NType;


    // Constructors

    /** default constructor */
    public TbIllness() {
    }

	/** minimal constructor */
    public TbIllness(TbDiagnose tbDiagnose, MsIcd msIcd, short NIllDuration) {
        this.tbDiagnose = tbDiagnose;
        this.msIcd = msIcd;
        this.NIllDuration = NIllDuration;
    }
    
    /** full constructor */
    public TbIllness(TbDiagnose tbDiagnose, MsIcd msIcd, short NIllDuration, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, short NType) {
        this.tbDiagnose = tbDiagnose;
        this.msIcd = msIcd;
        this.NIllDuration = NIllDuration;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.NType = NType;
    }

   
    // Property accessors

    public Integer getNIllnessId() {
        return this.NIllnessId;
    }
    
    public void setNIllnessId(Integer NIllnessId) {
        this.NIllnessId = NIllnessId;
    }

    public TbDiagnose getTbDiagnose() {
        return this.tbDiagnose;
    }
    
    public void setTbDiagnose(TbDiagnose tbDiagnose) {
        this.tbDiagnose = tbDiagnose;
    }

    public MsIcd getMsIcd() {
        return this.msIcd;
    }
    
    public void setMsIcd(MsIcd msIcd) {
        this.msIcd = msIcd;
    }

    public short getNIllDuration() {
        return this.NIllDuration;
    }
    
    public void setNIllDuration(short NIllDuration) {
        this.NIllDuration = NIllDuration;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public short getNType() {
        return this.NType;
    }
    
    public void setNType(short NType) {
        this.NType = NType;
    }
   








}