package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbItemTrx generated by MyEclipse - Hibernate Tools
 */

public class TbItemTrx  implements java.io.Serializable {


    // Fields    

     private Integer NItemTrxId;
     private MsItem msItem;
     private TbBatchItem tbBatchItem;
     private TbExamination tbExamination;
     private TbDrugIngredients tbDrugIngredients;
     private MsTreatmentFee msTreatmentFee;
     private Double NAmountTrx;
     private Float NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Date DWhnCreate;
     private String VReceiptNo;
     private String VDiscType;
     private Double NDiscAmount;
     private Double NAmountAfterDisc;
     private String AturanPakai;
     private Set tbPatientInventories = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbItemTrx() {
    }

	/** minimal constructor */
    public TbItemTrx(Integer NItemTrxId, MsItem msItem, TbExamination tbExamination) {
        this.NItemTrxId = NItemTrxId;
        this.msItem = msItem;
        this.tbExamination = tbExamination;
    }

   
    // Property accessors

    public Integer getNItemTrxId() {
        return this.NItemTrxId;
    }
    
    public void setNItemTrxId(Integer NItemTrxId) {
        this.NItemTrxId = NItemTrxId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbBatchItem getTbBatchItem() {
        return this.tbBatchItem;
    }
    
    public void setTbBatchItem(TbBatchItem tbBatchItem) {
        this.tbBatchItem = tbBatchItem;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }

    public TbDrugIngredients getTbDrugIngredients() {
        return this.tbDrugIngredients;
    }
    
    public void setTbDrugIngredients(TbDrugIngredients tbDrugIngredients) {
        this.tbDrugIngredients = tbDrugIngredients;
    }

    public MsTreatmentFee getMsTreatmentFee() {
        return this.msTreatmentFee;
    }
    
    public void setMsTreatmentFee(MsTreatmentFee msTreatmentFee) {
        this.msTreatmentFee = msTreatmentFee;
    }

    public Double getNAmountTrx() {
        return this.NAmountTrx;
    }
    
    public void setNAmountTrx(Double NAmountTrx) {
        this.NAmountTrx = NAmountTrx;
    }

    public Float getNQty() {
        return this.NQty;
    }
    
    public void setNQty(Float NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVReceiptNo() {
        return this.VReceiptNo;
    }
    
    public void setVReceiptNo(String VReceiptNo) {
        this.VReceiptNo = VReceiptNo;
    }

    public String getVDiscType() {
        return this.VDiscType;
    }
    
    public void setVDiscType(String VDiscType) {
        this.VDiscType = VDiscType;
    }

    public double getNDiscAmount() {
        return this.NDiscAmount;
    }
    
    public void setNDiscAmount(Double NDiscAmount) {
        this.NDiscAmount = NDiscAmount;
    }

    public Double getNAmountAfterDisc() {
        return this.NAmountAfterDisc;
    }
    
    public void setNAmountAfterDisc(Double NAmountAfterDisc) {
        this.NAmountAfterDisc = NAmountAfterDisc;
    }

    public Set getTbPatientInventories() {
        return this.tbPatientInventories;
    }
    
    public void setTbPatientInventories(Set tbPatientInventories) {
        this.tbPatientInventories = tbPatientInventories;
    }
   
    public TbItemTrx clone(){
    	TbItemTrx trx = new TbItemTrx();
    	trx.setDWhnChange(this.DWhnChange);
    	trx.setDWhnCreate(this.DWhnCreate);
    	trx.setMsItem(this.msItem);
    	trx.setMsTreatmentFee(this.msTreatmentFee);
    	trx.setNAmountAfterDisc(this.NAmountAfterDisc);
    	trx.setNAmountTrx(this.NAmountTrx);
    	trx.setNDiscAmount(this.NDiscAmount);
    	trx.setNItemTrxId(this.NItemTrxId);
    	trx.setNQty(this.NQty);
    	trx.setTbBatchItem(this.tbBatchItem);
    	trx.setTbDrugIngredients(this.tbDrugIngredients);
    	trx.setTbExamination(this.tbExamination);
    	trx.setTbPatientInventories(this.tbPatientInventories);
    	trx.setVDiscType(this.VDiscType);
    	trx.setVReceiptNo(this.VReceiptNo);
    	trx.setVWhoChange(this.VWhoChange);
    	trx.setVWhoCreate(this.VWhoCreate);
      	return trx;
    }

	public String getAturanPakai() {
		return AturanPakai;
	}

	public void setAturanPakai(String aturanPakai) {
		AturanPakai = aturanPakai;
	}







}