package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbLaboratoryResultDetail generated by MyEclipse - Hibernate Tools
 */

public class TbLaboratoryResultDetail  implements java.io.Serializable {


    // Fields    

     private Integer NLabRsltDetId;
     private TbLaboratoryResult tbLaboratoryResult;
     private MsTreatment msTreatment;
     private String VNrmlRangeMan;
     private String VNrmlRangeWoman;
     private String VLabRsltQuantify;
     private String VLabRsltDesc;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Integer NLabDetilId;


    // Constructors

    /** default constructor */
    public TbLaboratoryResultDetail() {
    }

	/** minimal constructor */
    public TbLaboratoryResultDetail(Integer NLabRsltDetId, TbLaboratoryResult tbLaboratoryResult, MsTreatment msTreatment, String VNrmlRangeMan, String VNrmlRangeWoman, String VLabRsltQuantify, String VLabRsltDesc) {
        this.NLabRsltDetId = NLabRsltDetId;
        this.tbLaboratoryResult = tbLaboratoryResult;
        this.msTreatment = msTreatment;
        this.VNrmlRangeMan = VNrmlRangeMan;
        this.VNrmlRangeWoman = VNrmlRangeWoman;
        this.VLabRsltQuantify = VLabRsltQuantify;
        this.VLabRsltDesc = VLabRsltDesc;
    }
    
    /** full constructor */
    public TbLaboratoryResultDetail(Integer NLabRsltDetId, TbLaboratoryResult tbLaboratoryResult, MsTreatment msTreatment, String VNrmlRangeMan, String VNrmlRangeWoman, String VLabRsltQuantify, String VLabRsltDesc, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NLabRsltDetId = NLabRsltDetId;
        this.tbLaboratoryResult = tbLaboratoryResult;
        this.msTreatment = msTreatment;
        this.VNrmlRangeMan = VNrmlRangeMan;
        this.VNrmlRangeWoman = VNrmlRangeWoman;
        this.VLabRsltQuantify = VLabRsltQuantify;
        this.VLabRsltDesc = VLabRsltDesc;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNLabRsltDetId() {
        return this.NLabRsltDetId;
    }
    
    public void setNLabRsltDetId(Integer NLabRsltDetId) {
        this.NLabRsltDetId = NLabRsltDetId;
    }

    public TbLaboratoryResult getTbLaboratoryResult() {
        return this.tbLaboratoryResult;
    }
    
    public void setTbLaboratoryResult(TbLaboratoryResult tbLaboratoryResult) {
        this.tbLaboratoryResult = tbLaboratoryResult;
    }

    public MsTreatment getMsTreatment() {
        return this.msTreatment;
    }
    
    public void setMsTreatment(MsTreatment msTreatment) {
        this.msTreatment = msTreatment;
    }

    public String getVNrmlRangeMan() {
        return this.VNrmlRangeMan;
    }
    
    public void setVNrmlRangeMan(String VNrmlRangeMan) {
        this.VNrmlRangeMan = VNrmlRangeMan;
    }

    public String getVNrmlRangeWoman() {
        return this.VNrmlRangeWoman;
    }
    
    public void setVNrmlRangeWoman(String VNrmlRangeWoman) {
        this.VNrmlRangeWoman = VNrmlRangeWoman;
    }

    public String getVLabRsltQuantify() {
        return this.VLabRsltQuantify;
    }
    
    public void setVLabRsltQuantify(String VLabRsltQuantify) {
        this.VLabRsltQuantify = VLabRsltQuantify;
    }

    public String getVLabRsltDesc() {
        return this.VLabRsltDesc;
    }
    
    public void setVLabRsltDesc(String VLabRsltDesc) {
        this.VLabRsltDesc = VLabRsltDesc;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public Integer getNLabDetilId() {
		return NLabDetilId;
	}

	public void setNLabDetilId(Integer labDetilId) {
		NLabDetilId = labDetilId;
	}
   








}