package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.MsMiscFee;


/**
 * TbMiscTrx generated by MyEclipse - Hibernate Tools
 */

public class TbMiscTrx  implements java.io.Serializable {


    // Fields    

     private Integer NMiscTrxId;
     private TbExamination tbExamination;
     private double NAmountTrx;
     private short NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private double NDiscAmount;
     private String VDiscType;
     private double NAmountAfterDisc;
     private String VMiscName;
     private double NItemPrice;

    // Constructors

    /** default constructor */
    public TbMiscTrx() {
    }

	/** minimal constructor */
    public TbMiscTrx(Integer NMiscTrxId, TbExamination tbExamination) {
        this.NMiscTrxId = NMiscTrxId;
        this.tbExamination = tbExamination;
        
    }
    
    // Property accessors

    public Integer getNMiscTrxId() {
        return this.NMiscTrxId;
    }
    
    public void setNMiscTrxId(Integer NMiscTrxId) {
        this.NMiscTrxId = NMiscTrxId;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }
//    public MsMiscFee getMsMiscFee() {
//		return msMiscFee;
//	}
//
//	public void setMsMiscFee(MsMiscFee msMiscFee) {
//		this.msMiscFee = msMiscFee;
//	}

	public double getNAmountTrx() {
        return this.NAmountTrx;
    }
    
    public void setNAmountTrx(double NAmountTrx) {
        this.NAmountTrx = NAmountTrx;
    }

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public double getNDiscAmount() {
        return this.NDiscAmount;
    }
    
    public void setNDiscAmount(double NDiscAmount) {
        this.NDiscAmount = NDiscAmount;
    }

    public String getVDiscType() {
        return this.VDiscType;
    }
    
    public void setVDiscType(String VDiscType) {
        this.VDiscType = VDiscType;
    }

    public double getNAmountAfterDisc() {
        return this.NAmountAfterDisc;
    }
    
    public void setNAmountAfterDisc(double NAmountAfterDisc) {
        this.NAmountAfterDisc = NAmountAfterDisc;
    }

	public double getNItemPrice() {
		return NItemPrice;
	}

	public void setNItemPrice(double itemPrice) {
		NItemPrice = itemPrice;
	}

	public String getVMiscName() {
		return VMiscName;
	}

	public void setVMiscName(String miscName) {
		VMiscName = miscName;
	}
   








}