package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbOperationTrx generated by MyEclipse - Hibernate Tools
 */

public class TbOperationTrx  implements java.io.Serializable {


    // Fields    

     private Integer NOperationRoomIdTrx;
     private TbExamination tbExamination;
     private MsTreatmentRoomFee msTreatmentRoomFee;
     private double NAmountTrx;
     private short NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date NWhnChange;
     private String VDiscType;
     private double NDiscAmount;
     private double NAmountAfterDisc;


    // Constructors

    /** default constructor */
    public TbOperationTrx() {
    }

	/** minimal constructor */
    public TbOperationTrx(Integer NOperationRoomIdTrx, TbExamination tbExamination, MsTreatmentRoomFee msTreatmentRoomFee) {
        this.NOperationRoomIdTrx = NOperationRoomIdTrx;
        this.tbExamination = tbExamination;
        this.msTreatmentRoomFee = msTreatmentRoomFee;
    }
    // Property accessors

    public Integer getNOperationRoomIdTrx() {
        return this.NOperationRoomIdTrx;
    }
    
    public void setNOperationRoomIdTrx(Integer NOperationRoomIdTrx) {
        this.NOperationRoomIdTrx = NOperationRoomIdTrx;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }
    
    public MsTreatmentRoomFee getMsTreatmentRoomFee() {
        return this.msTreatmentRoomFee;
    }
    
    public void setMsTreatmentRoomFee(MsTreatmentRoomFee msTreatmentRoomFee) {
        this.msTreatmentRoomFee = msTreatmentRoomFee;
    }

    public double getNAmountTrx() {
        return this.NAmountTrx;
    }
    
    public void setNAmountTrx(double NAmountTrx) {
        this.NAmountTrx = NAmountTrx;
    }

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getNWhnChange() {
        return this.NWhnChange;
    }
    
    public void setNWhnChange(Date NWhnChange) {
        this.NWhnChange = NWhnChange;
    }

    public String getVDiscType() {
        return this.VDiscType;
    }
    
    public void setVDiscType(String VDiscType) {
        this.VDiscType = VDiscType;
    }

    public double getNDiscAmount() {
        return this.NDiscAmount;
    }
    
    public void setNDiscAmount(double NDiscAmount) {
        this.NDiscAmount = NDiscAmount;
    }

    public double getNAmountAfterDisc() {
        return this.NAmountAfterDisc;
    }
    
    public void setNAmountAfterDisc(double NAmountAfterDisc) {
        this.NAmountAfterDisc = NAmountAfterDisc;
    }
   








}