package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbOperation generated by MyEclipse - Hibernate Tools
 */

public class TbOperation  implements java.io.Serializable {


    // Fields    

     private Integer NOperationId;
     private TbDiagnose tbDiagnose;
     private String VTypeOfOperation;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbOperation() {
    }

	/** minimal constructor */
    public TbOperation(TbDiagnose tbDiagnose, String VTypeOfOperation) {
        this.tbDiagnose = tbDiagnose;
        this.VTypeOfOperation = VTypeOfOperation;
    }
    
    /** full constructor */
    public TbOperation(TbDiagnose tbDiagnose, String VTypeOfOperation, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.tbDiagnose = tbDiagnose;
        this.VTypeOfOperation = VTypeOfOperation;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNOperationId() {
        return this.NOperationId;
    }
    
    public void setNOperationId(Integer NOperationId) {
        this.NOperationId = NOperationId;
    }

    public TbDiagnose getTbDiagnose() {
        return this.tbDiagnose;
    }
    
    public void setTbDiagnose(TbDiagnose tbDiagnose) {
        this.tbDiagnose = tbDiagnose;
    }

    public String getVTypeOfOperation() {
        return this.VTypeOfOperation;
    }
    
    public void setVTypeOfOperation(String VTypeOfOperation) {
        this.VTypeOfOperation = VTypeOfOperation;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}