package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;


/**
 * TbPatientInventory generated by MyEclipse - Hibernate Tools
 */

public class TbPatientInventory  implements java.io.Serializable {


    // Fields    

     private Integer NPiId;
     private MsPatient msPatient;
     private TbRegistration tbRegistration;
	 private MsItem msItem;
     private TbItemTrx tbItemTrx;
     private String VWhoCreate;
     private String VWhnCreate;
     private Date DWhoCreate;
     private Date DWhnCreate;
     private short NQty;
     private short NQtyOut;


    // Constructors

    /** default constructor */
    public TbPatientInventory() {
    }

	/** minimal constructor */
    public TbPatientInventory(Integer NPiId, MsPatient msPatient, MsItem msItem) {
        this.NPiId = NPiId;
        this.msPatient = msPatient;
        this.msItem = msItem;
    }
    
    /** full constructor */
    public TbPatientInventory(Integer NPiId, MsPatient msPatient, MsItem msItem, TbItemTrx tbItemTrx, String VWhoCreate, String VWhnCreate, Date DWhoCreate, Date DWhnCreate, short NQty, short NQtyOut) {
        this.NPiId = NPiId;
        this.msPatient = msPatient;
        this.msItem = msItem;
        this.tbItemTrx = tbItemTrx;
        this.VWhoCreate = VWhoCreate;
        this.VWhnCreate = VWhnCreate;
        this.DWhoCreate = DWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.NQty = NQty;
        this.NQtyOut = NQtyOut;
    }
    

    
    public TbRegistration getTbRegistration() {
		return tbRegistration;
	}

	public void setTbRegistration(TbRegistration tbRegistration) {
		this.tbRegistration = tbRegistration;
	}

   
    // Property accessors

    public Integer getNPiId() {
        return this.NPiId;
    }
    
    public void setNPiId(Integer NPiId) {
        this.NPiId = NPiId;
    }

    public MsPatient getMsPatient() {
        return this.msPatient;
    }
    
    public void setMsPatient(MsPatient msPatient) {
        this.msPatient = msPatient;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbItemTrx getTbItemTrx() {
        return this.tbItemTrx;
    }
    
    public void setTbItemTrx(TbItemTrx tbItemTrx) {
        this.tbItemTrx = tbItemTrx;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhnCreate() {
        return this.VWhnCreate;
    }
    
    public void setVWhnCreate(String VWhnCreate) {
        this.VWhnCreate = VWhnCreate;
    }

    public Date getDWhoCreate() {
        return this.DWhoCreate;
    }
    
    public void setDWhoCreate(Date DWhoCreate) {
        this.DWhoCreate = DWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public short getNQtyOut() {
        return this.NQtyOut;
    }
    
    public void setNQtyOut(short NQtyOut) {
        this.NQtyOut = NQtyOut;
    }
   








}