package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.MsMiscFee;


/**
 * TbPatientBillDetail generated by MyEclipse - Hibernate Tools
 */

public class TbPatientBillDetail  implements java.io.Serializable {


    // Fields    

     private Integer NPbillDetId;
     private MsMiscFee msMiscFee;
     private MsInsurance msInsurance;
     private TbPatientBill tbPatientBill;
     private String VPbillDetDesc;
     private double NPbillDetFee;
     private short NPbillDetDisc;
     private double NPbillDetCovered;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private short NPbillDetQty;
     private String VPbillDetName;


    // Constructors

    /** default constructor */
    public TbPatientBillDetail() {
    }

	/** minimal constructor */
    public TbPatientBillDetail(Integer NPbillDetId, TbPatientBill tbPatientBill) {
        this.NPbillDetId = NPbillDetId;
        this.tbPatientBill = tbPatientBill;
    }
    
    /** full constructor */
    public TbPatientBillDetail(Integer NPbillDetId, MsMiscFee msMiscFee, MsInsurance msInsurance, TbPatientBill tbPatientBill, String VPbillDetDesc, double NPbillDetFee, short NPbillDetDisc, double NPbillDetCovered, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, short NPbillDetQty, String VPbillDetName) {
        this.NPbillDetId = NPbillDetId;
        this.msMiscFee = msMiscFee;
        this.msInsurance = msInsurance;
        this.tbPatientBill = tbPatientBill;
        this.VPbillDetDesc = VPbillDetDesc;
        this.NPbillDetFee = NPbillDetFee;
        this.NPbillDetDisc = NPbillDetDisc;
        this.NPbillDetCovered = NPbillDetCovered;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.NPbillDetQty = NPbillDetQty;
        this.VPbillDetName = VPbillDetName;
    }

   
    // Property accessors

    public Integer getNPbillDetId() {
        return this.NPbillDetId;
    }
    
    public void setNPbillDetId(Integer NPbillDetId) {
        this.NPbillDetId = NPbillDetId;
    }

    public MsMiscFee getMsMiscFee() {
        return this.msMiscFee;
    }
    
    public void setMsMiscFee(MsMiscFee msMiscFee) {
        this.msMiscFee = msMiscFee;
    }

    public MsInsurance getMsInsurance() {
        return this.msInsurance;
    }
    
    public void setMsInsurance(MsInsurance msInsurance) {
        this.msInsurance = msInsurance;
    }

    public TbPatientBill getTbPatientBill() {
        return this.tbPatientBill;
    }
    
    public void setTbPatientBill(TbPatientBill tbPatientBill) {
        this.tbPatientBill = tbPatientBill;
    }

    public String getVPbillDetDesc() {
        return this.VPbillDetDesc;
    }
    
    public void setVPbillDetDesc(String VPbillDetDesc) {
        this.VPbillDetDesc = VPbillDetDesc;
    }

    public double getNPbillDetFee() {
        return this.NPbillDetFee;
    }
    
    public void setNPbillDetFee(double NPbillDetFee) {
        this.NPbillDetFee = NPbillDetFee;
    }

    public short getNPbillDetDisc() {
        return this.NPbillDetDisc;
    }
    
    public void setNPbillDetDisc(short NPbillDetDisc) {
        this.NPbillDetDisc = NPbillDetDisc;
    }

    public double getNPbillDetCovered() {
        return this.NPbillDetCovered;
    }
    
    public void setNPbillDetCovered(double NPbillDetCovered) {
        this.NPbillDetCovered = NPbillDetCovered;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public short getNPbillDetQty() {
        return this.NPbillDetQty;
    }
    
    public void setNPbillDetQty(short NPbillDetQty) {
        this.NPbillDetQty = NPbillDetQty;
    }

    public String getVPbillDetName() {
        return this.VPbillDetName;
    }
    
    public void setVPbillDetName(String VPbillDetName) {
        this.VPbillDetName = VPbillDetName;
    }
   








}