package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MsBank generated by MyEclipse - Hibernate Tools
 */

public class TbPatientEscortTrx  implements java.io.Serializable {


    // Fields    

     private Integer NPeId;	
     private MsPatientEscort msPatientEscort;
     private MsCoa msCoa;
     private TbExamination tbExamination;
     private double NAmountTrx;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;     

    // Constructors

     
     // Property accessors
    /** default constructor */
    public TbPatientEscortTrx() {
    }

	public Date getDWhnCreate() {
		return DWhnCreate;
	}

	public void setDWhnCreate(Date whnCreate) {
		DWhnCreate = whnCreate;
	}

	public double getNAmountTrx() {
		return NAmountTrx;
	}

	public void setNAmountTrx(double amountTrx) {
		NAmountTrx = amountTrx;
	}

	public MsCoa getMsCoa() {
		return msCoa;
	}

	public void setMsCoa(MsCoa msCoa) {
		this.msCoa = msCoa;
	}

	public MsPatientEscort getMsPatientEscort() {
		return msPatientEscort;
	}

	public void setMsPatientEscort(MsPatientEscort msPatientEscort) {
		this.msPatientEscort = msPatientEscort;
	}


	public TbExamination getTbExamination() {
		return tbExamination;
	}

	public void setTbExamination(TbExamination tbExamination) {
		this.tbExamination = tbExamination;
	}

	public Integer getNPeId() {
		return NPeId;
	}

	public void setNPeId(Integer peId) {
		NPeId = peId;
	}

	public Date getDWhnChange() {
		return DWhnChange;
	}

	public void setDWhnChange(Date whnChange) {
		DWhnChange = whnChange;
	}

	public String getVWhoChange() {
		return VWhoChange;
	}

	public void setVWhoChange(String whoChange) {
		VWhoChange = whoChange;
	}

	public String getVWhoCreate() {
		return VWhoCreate;
	}

	public void setVWhoCreate(String whoCreate) {
		VWhoCreate = whoCreate;
	}
   









}