package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbPatientDeposit generated by MyEclipse - Hibernate Tools
 */

public class TbPatientDeposit  implements java.io.Serializable {


    // Fields    

     private Integer NPdId;
    
     private TbRegistration tbRegistration;
     private double NMutation;
     private double NBalance;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbPatientDeposit() {
    }

	/** minimal constructor */
    public TbPatientDeposit(Integer NPdId) {
        this.NPdId = NPdId;
    }
    
    

   
    // Property accessors

    public TbRegistration getTbRegistration() {
		return tbRegistration;
	}

	public void setTbRegistration(TbRegistration tbRegistration) {
		this.tbRegistration = tbRegistration;
	}

	public Integer getNPdId() {
        return this.NPdId;
    }
    
    public void setNPdId(Integer NPdId) {
        this.NPdId = NPdId;
    }

    public double getNMutation() {
        return this.NMutation;
    }
    
    public void setNMutation(double NMutation) {
        this.NMutation = NMutation;
    }

    public double getNBalance() {
        return this.NBalance;
    }
    
    public void setNBalance(double NBalance) {
        this.NBalance = NBalance;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}