package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbPersonReserved generated by MyEclipse - Hibernate Tools
 */

public class TbPersonReserved  implements java.io.Serializable {


    // Fields    

     private Integer NPersonRsvPrimaryId;
     private String VPersonRsvName;
     private String VPersonRsvContactNo;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbPersonReserved() {
    }

	/** minimal constructor */
    public TbPersonReserved(Integer NPersonRsvPrimaryId, String VPersonRsvName, String VPersonRsvContactNo) {
        this.NPersonRsvPrimaryId = NPersonRsvPrimaryId;
        this.VPersonRsvName = VPersonRsvName;
        this.VPersonRsvContactNo = VPersonRsvContactNo;
    }
    
    /** full constructor */
    public TbPersonReserved(Integer NPersonRsvPrimaryId, String VPersonRsvName, String VPersonRsvContactNo, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NPersonRsvPrimaryId = NPersonRsvPrimaryId;
        this.VPersonRsvName = VPersonRsvName;
        this.VPersonRsvContactNo = VPersonRsvContactNo;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNPersonRsvPrimaryId() {
        return this.NPersonRsvPrimaryId;
    }
    
    public void setNPersonRsvPrimaryId(Integer NPersonRsvPrimaryId) {
        this.NPersonRsvPrimaryId = NPersonRsvPrimaryId;
    }

    public String getVPersonRsvName() {
        return this.VPersonRsvName;
    }
    
    public void setVPersonRsvName(String VPersonRsvName) {
        this.VPersonRsvName = VPersonRsvName;
    }

    public String getVPersonRsvContactNo() {
        return this.VPersonRsvContactNo;
    }
    
    public void setVPersonRsvContactNo(String VPersonRsvContactNo) {
        this.VPersonRsvContactNo = VPersonRsvContactNo;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}