package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbPurchaseRequest generated by MyEclipse - Hibernate Tools
 */

public class TbPurchaseRequest  implements java.io.Serializable {


    // Fields    

     private Integer NPrId;
     private Integer supplierId;
     private MsStaff msStaffByNApproverId;
     private MsStaff msStaffByNIssuerId;
     private MsUnit msUnitId;
     private String VPrCode;
     private String VPrStatus;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbPurchaseOrders = new HashSet(0);
     private Set tbPurchaseRequestDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbPurchaseRequest() {
    }

	/** minimal constructor */
    public TbPurchaseRequest(Integer NPrId, MsStaff msStaffByNApproverId, MsStaff msStaffByNIssuerId, String VPrCode, String VWhoCreate, Date DWhnCreate) {
        this.NPrId = NPrId;
        this.msStaffByNApproverId = msStaffByNApproverId;
        this.msStaffByNIssuerId = msStaffByNIssuerId;
        this.VPrCode = VPrCode;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbPurchaseRequest(Integer NPrId, MsStaff msStaffByNApproverId, MsStaff msStaffByNIssuerId, String VPrCode, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPurchaseOrders, Set tbPurchaseRequestDetails) {
        this.NPrId = NPrId;
        this.msStaffByNApproverId = msStaffByNApproverId;
        this.msStaffByNIssuerId = msStaffByNIssuerId;
        this.VPrCode = VPrCode;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbPurchaseOrders = tbPurchaseOrders;
        this.tbPurchaseRequestDetails = tbPurchaseRequestDetails;
    }

    
   
    // Property accessors

    public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public Integer getNPrId() {
        return this.NPrId;
    }
    
    public void setNPrId(Integer NPrId) {
        this.NPrId = NPrId;
    }

    public MsStaff getMsStaffByNApproverId() {
        return this.msStaffByNApproverId;
    }
    
    public void setMsStaffByNApproverId(MsStaff msStaffByNApproverId) {
        this.msStaffByNApproverId = msStaffByNApproverId;
    }

    public MsStaff getMsStaffByNIssuerId() {
        return this.msStaffByNIssuerId;
    }
    
    public void setMsStaffByNIssuerId(MsStaff msStaffByNIssuerId) {
        this.msStaffByNIssuerId = msStaffByNIssuerId;
    }

    public String getVPrCode() {
        return this.VPrCode;
    }
    
    public void setVPrCode(String VPrCode) {
        this.VPrCode = VPrCode;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPurchaseOrders() {
        return this.tbPurchaseOrders;
    }
    
    public void setTbPurchaseOrders(Set tbPurchaseOrders) {
        this.tbPurchaseOrders = tbPurchaseOrders;
    }

    public Set getTbPurchaseRequestDetails() {
        return this.tbPurchaseRequestDetails;
    }
    
    public void setTbPurchaseRequestDetails(Set tbPurchaseRequestDetails) {
        this.tbPurchaseRequestDetails = tbPurchaseRequestDetails;
    }

	public String getVPrStatus() {
		return VPrStatus;
	}

	public void setVPrStatus(String prStatus) {
		VPrStatus = prStatus;
	}

	public MsUnit getMsUnitId() {
		return msUnitId;
	}

	public void setMsUnitId(MsUnit msUnitId) {
		this.msUnitId = msUnitId;
	}
   








}