package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.*;


/**
 * TbPurchaseOrderDetail generated by MyEclipse - Hibernate Tools
 */

public class TbPurchaseOrderDetail  implements java.io.Serializable {


    // Fields    

     private Integer NPoDetId;
     private MsItem msItem;
     private TbPurchaseOrder tbPurchaseOrder;
     private MsItemMeasurement msItemMeasurement;
     private short NPoDetQtyOrdered;
     private short NPoDetQtyRemark;
     private short NPoDetQtyReceived;
     private short NBonus;
     private Short NBonusRecieved;
     private double NPoDetCost;
     private Double NDiscount;
     private String VDiscountType;
     private double NSubtotal;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbPurchaseOrderDetail() {
    }

	/** minimal constructor */
    public TbPurchaseOrderDetail(Integer NPoDetId, MsItem msItem, TbPurchaseOrder tbPurchaseOrder, short NPoDetQtyOrdered, double NPoDetCost, String VWhoCreate, Date DWhnCreate) {
        this.NPoDetId = NPoDetId;
        this.msItem = msItem;
        this.tbPurchaseOrder = tbPurchaseOrder;
        this.NPoDetQtyOrdered = NPoDetQtyOrdered;
        this.NPoDetCost = NPoDetCost;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbPurchaseOrderDetail(Integer NPoDetId, TbPurchaseOrder tbPurchaseOrder, MsItem msItem, short NPoDetQtyOrdered, short NPoDetQtyRemark, short NPoDetQtyReceived, double NPoDetCost, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPurchaseOrders) {
        this.NPoDetId = NPoDetId;
        this.msItem = msItem;
        this.tbPurchaseOrder = tbPurchaseOrder;
        this.NPoDetQtyOrdered = NPoDetQtyOrdered;
        this.NPoDetQtyRemark = NPoDetQtyRemark;
        this.NPoDetQtyReceived = NPoDetQtyReceived;
        this.NPoDetCost = NPoDetCost;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        
    }

   
    // Property accessors

    public Short getNBonusRecieved() {
    	if (NBonusRecieved == null)
    		return new Integer(0).shortValue();
    	
		return NBonusRecieved;
	}

	public void setNBonusRecieved(Short bonusRecieved) {
		NBonusRecieved = bonusRecieved;
	}

	public Integer getNPoDetId() {
        return this.NPoDetId;
    }
    
    public MsItemMeasurement getMsItemMeasurement() {
		return msItemMeasurement;
	}

	public void setMsItemMeasurement(MsItemMeasurement msItemMeasurement) {
		this.msItemMeasurement = msItemMeasurement;
	}

	public short getNBonus() {
		return NBonus;
	}

	public void setNBonus(short bonus) {
		NBonus = bonus;
	}


	public Double getNDiscount() {
		return NDiscount;
	}

	public void setNDiscount(Double discount) {
		NDiscount = discount;
	}

	public double getNSubtotal() {
		return NSubtotal;
	}

	public void setNSubtotal(double subtotal) {
		NSubtotal = subtotal;
	}

	public String getVDiscountType() {
		return VDiscountType;
	}

	public void setVDiscountType(String discountType) {
		VDiscountType = discountType;
	}

	public void setNPoDetId(Integer NPoDetId) {
        this.NPoDetId = NPoDetId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public short getNPoDetQtyOrdered() {
        return this.NPoDetQtyOrdered;
    }
    
    public void setNPoDetQtyOrdered(short NPoDetQtyOrdered) {
        this.NPoDetQtyOrdered = NPoDetQtyOrdered;
    }

    public short getNPoDetQtyRemark() {
        return this.NPoDetQtyRemark;
    }
    
    public void setNPoDetQtyRemark(short NPoDetQtyRemark) {
        this.NPoDetQtyRemark = NPoDetQtyRemark;
    }

    public short getNPoDetQtyReceived() {
        return this.NPoDetQtyReceived;
    }
    
    public void setNPoDetQtyReceived(short NPoDetQtyReceived) {
        this.NPoDetQtyReceived = NPoDetQtyReceived;
    }

    public double getNPoDetCost() {
        return this.NPoDetCost;
    }
    
    public void setNPoDetCost(double NPoDetCost) {
        this.NPoDetCost = NPoDetCost;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public TbPurchaseOrder getTbPurchaseOrder() {
		return tbPurchaseOrder;
	}

	public void setTbPurchaseOrder(TbPurchaseOrder tbPurchaseOrder) {
		this.tbPurchaseOrder = tbPurchaseOrder;
	}









}