package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.pojo.item.MsVendor;


/**
 * TbPurchaseOrder generated by MyEclipse - Hibernate Tools
 */

public class TbPurchaseOrder  implements java.io.Serializable {


    // Fields    

     private Integer NPoId;
     private MsStaff msStaffByNApproverId;
     private MsVendor msVendor;
     private MsStaff msStaffByNIssuerId;
     private TbPurchaseRequest tbPurchaseRequest;
     private String VPoCode;
     private String VPoCanceled;
     private String VPoStatus;
     private Double NDiscount;
     private String VDiscountType;
     private Double NTotal;
     private Double NSubtotal;
     private String VWhoCreate;
     private Date DWhnCreate;     
     private String VWhoChange;
     private Date DWhnChange;
     private Date DPaymentDue;
     private Set tbDeliveryOrders = new HashSet(0);
     private Set tbPurchaseOrderDetails = new HashSet(0);

    // Constructors

    /** default constructor */
    public TbPurchaseOrder() {
    }

	/** minimal constructor */
    public TbPurchaseOrder(Integer NPoId, MsStaff msStaffByNApproverId,  MsVendor msVendor, MsStaff msStaffByNIssuerId, String VPoCode, String VWhoCreate, Date DWhnCreate) {
        this.NPoId = NPoId;
        this.msStaffByNApproverId = msStaffByNApproverId;
        this.msVendor = msVendor;
        this.msStaffByNIssuerId = msStaffByNIssuerId;
        this.VPoCode = VPoCode;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    public Date getDPaymentDue() {
		return DPaymentDue;
	}

	public void setDPaymentDue(Date paymentDue) {
		DPaymentDue = paymentDue;
	}

	/** full constructor */
    public TbPurchaseOrder(Integer NPoId, MsStaff msStaffByNApproverId, 
    		MsVendor msVendor, MsStaff msStaffByNIssuerId, TbPurchaseRequest tbPurchaseRequest, String VPoCode, String VPoCanceled, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbDeliveryOrders) {
        this.NPoId = NPoId;
        this.msStaffByNApproverId = msStaffByNApproverId;
        this.msVendor = msVendor;
        this.msStaffByNIssuerId = msStaffByNIssuerId;
        this.tbPurchaseRequest = tbPurchaseRequest;
        this.VPoCode = VPoCode;
        this.VPoCanceled = VPoCanceled;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbDeliveryOrders = tbDeliveryOrders;
    }

   
    // Property accessors


	public Integer getNPoId() {
        return this.NPoId;
    }
    
    public void setNPoId(Integer NPoId) {
        this.NPoId = NPoId;
    }

    public MsStaff getMsStaffByNApproverId() {
        return this.msStaffByNApproverId;
    }
    
    public void setMsStaffByNApproverId(MsStaff msStaffByNApproverId) {
        this.msStaffByNApproverId = msStaffByNApproverId;
    }


    public MsVendor getMsVendor() {
        return this.msVendor;
    }
    
    public void setMsVendor(MsVendor msVendor) {
        this.msVendor = msVendor;
    }

    public MsStaff getMsStaffByNIssuerId() {
        return this.msStaffByNIssuerId;
    }
    
    public void setMsStaffByNIssuerId(MsStaff msStaffByNIssuerId) {
        this.msStaffByNIssuerId = msStaffByNIssuerId;
    }

    public TbPurchaseRequest getTbPurchaseRequest() {
        return this.tbPurchaseRequest;
    }
    
    public void setTbPurchaseRequest(TbPurchaseRequest tbPurchaseRequest) {
        this.tbPurchaseRequest = tbPurchaseRequest;
    }

    public String getVPoCode() {
        return this.VPoCode;
    }
    
    public void setVPoCode(String VPoCode) {
        this.VPoCode = VPoCode;
    }

    public String getVPoCanceled() {
        return this.VPoCanceled;
    }
    
    public void setVPoCanceled(String VPoCanceled) {
        this.VPoCanceled = VPoCanceled;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbDeliveryOrders() {
        return this.tbDeliveryOrders;
    }
    
    public void setTbDeliveryOrders(Set tbDeliveryOrders) {
        this.tbDeliveryOrders = tbDeliveryOrders;
    }

	public String getVPoStatus() {
		return VPoStatus;
	}

	public void setVPoStatus(String poStatus) {
		VPoStatus = poStatus;
	}

	public Set getTbPurchaseOrderDetails() {
		return tbPurchaseOrderDetails;
	}

	public void setTbPurchaseOrderDetails(Set tbPurchaseOrderDetails) {
		this.tbPurchaseOrderDetails = tbPurchaseOrderDetails;
	}

	public Double getNDiscount() {
		return NDiscount;
	}

	public void setNDiscount(Double discount) {
		NDiscount = discount;
	}

	public String getVDiscountType() {
		return VDiscountType;
	}

	public void setVDiscountType(String discountType) {
		VDiscountType = discountType;
	}

	public Double getNSubtotal() {
		return NSubtotal;
	}

	public void setNSubtotal(Double subtotal) {
		NSubtotal = subtotal;
	}

	public Double getNTotal() {
		return NTotal;
	}

	public void setNTotal(Double total) {
		NTotal = total;
	}








}