package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.MsItemMeasurement;


/**
 * TbPurchaseRequestDetail generated by MyEclipse - Hibernate Tools
 */

public class TbPurchaseRequestDetail  implements java.io.Serializable {


    // Fields    

     private Integer NPrDetId;
     private MsItem msItem;
     private TbPurchaseRequest tbPurchaseRequest;
     private MsItemMeasurement msItemMeasurement;
     private short NPrDetQtyRequested;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbPurchaseRequestDetail() {
    }

	/** minimal constructor */
    public TbPurchaseRequestDetail(Integer NPrDetId, MsItem msItem, TbPurchaseRequest tbPurchaseRequest, short NPrDetQtyRequested, String VWhoCreate, Date DWhnCreate) {
        this.NPrDetId = NPrDetId;
        this.msItem = msItem;
        this.tbPurchaseRequest = tbPurchaseRequest;
        this.NPrDetQtyRequested = NPrDetQtyRequested;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbPurchaseRequestDetail(Integer NPrDetId, MsItem msItem, TbPurchaseRequest tbPurchaseRequest, short NPrDetQtyRequested, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NPrDetId = NPrDetId;
        this.msItem = msItem;
        this.tbPurchaseRequest = tbPurchaseRequest;
        this.NPrDetQtyRequested = NPrDetQtyRequested;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNPrDetId() {
        return this.NPrDetId;
    }
    
    public void setNPrDetId(Integer NPrDetId) {
        this.NPrDetId = NPrDetId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbPurchaseRequest getTbPurchaseRequest() {
        return this.tbPurchaseRequest;
    }
    
    public void setTbPurchaseRequest(TbPurchaseRequest tbPurchaseRequest) {
        this.tbPurchaseRequest = tbPurchaseRequest;
    }

    public short getNPrDetQtyRequested() {
        return this.NPrDetQtyRequested;
    }
    
    public void setNPrDetQtyRequested(short NPrDetQtyRequested) {
        this.NPrDetQtyRequested = NPrDetQtyRequested;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public MsItemMeasurement getMsItemMeasurement() {
		return msItemMeasurement;
	}

	public void setMsItemMeasurement(MsItemMeasurement msItemMeasurement) {
		this.msItemMeasurement = msItemMeasurement;
	}
   








}