package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbRacikanInventory generated by MyEclipse - Hibernate Tools
 */

public class TbRacikanInventory  implements java.io.Serializable {


    // Fields    

     private Integer NRiId;
     private MsItem msItem;
     private TbBatchItem tbBatchItem;
     private MsWarehouse msWarehouse;
     private String VDesc;
     private float NQty;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbRacikanInventory() {
    }

	/** minimal constructor */
    public TbRacikanInventory(Integer NRiId, MsItem msItem, MsWarehouse msWarehouse) {
        this.NRiId = NRiId;
        this.msItem = msItem;
        this.msWarehouse = msWarehouse;
    }
    
    /** full constructor */
    public TbRacikanInventory(Integer NRiId, MsItem msItem, TbBatchItem tbBatchItem, MsWarehouse msWarehouse, String VDesc, float NQty, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NRiId = NRiId;
        this.msItem = msItem;
        this.tbBatchItem = tbBatchItem;
        this.msWarehouse = msWarehouse;
        this.VDesc = VDesc;
        this.NQty = NQty;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNRiId() {
        return this.NRiId;
    }
    
    public void setNRiId(Integer NRiId) {
        this.NRiId = NRiId;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public TbBatchItem getTbBatchItem() {
        return this.tbBatchItem;
    }
    
    public void setTbBatchItem(TbBatchItem tbBatchItem) {
        this.tbBatchItem = tbBatchItem;
    }

    public MsWarehouse getMsWarehouse() {
        return this.msWarehouse;
    }
    
    public void setMsWarehouse(MsWarehouse msWarehouse) {
        this.msWarehouse = msWarehouse;
    }

    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }

    public float getNQty() {
        return this.NQty;
    }
    
    public void setNQty(float NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}