package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbRegistration generated by MyEclipse - Hibernate Tools
 */

public class TbRegistration  implements java.io.Serializable {


    // Fields    

     private Integer NRegId;
     private MsStaff msStaff;
     private MsDivision msDivision;
     private TbMedicalRecord tbMedicalRecord;
     private TbRegistration tbRegistration;
     private MsUnit msUnit;
     private Date DRegistrationDate;
     private String VRegSecondaryId;
     private long NEscortPrimaryId;
     private String VRegCancelationNote;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private String VMainDoctorStatus;
     private String VRegCancelationStatus;
     private Integer NRoomRsvId;
     private Integer regStatus;
     private Integer antrianStatus;
     private Integer mrStatus;
	 private Set tbRegistrations = new HashSet(0);
     private Set tbBedOccupancies = new HashSet(0);
     private Set tbExaminations = new HashSet(0);
     private Set tbPatientBills = new HashSet(0);
     
     

    public Integer getMrStatus() {
		return mrStatus;
	}

	public void setMrStatus(Integer mrStatus) {
		this.mrStatus = mrStatus;
	}

	public Integer getAntrianStatus() {
 		return antrianStatus;
 	}

 	public void setAntrianStatus(Integer antrianStatus) {
 		this.antrianStatus = antrianStatus;
 	}

    // Constructors

    /** default constructor */
    public TbRegistration() {
    }

	/** minimal constructor */
    public TbRegistration(Integer NRegId, MsDivision msDivision, TbMedicalRecord tbMedicalRecord, MsUnit msUnit, Date DRegistrationDate, String VRegSecondaryId) {
        this.NRegId = NRegId;
        this.msDivision = msDivision;
        this.tbMedicalRecord = tbMedicalRecord;
        this.msUnit = msUnit;
        this.DRegistrationDate = DRegistrationDate;
        this.VRegSecondaryId = VRegSecondaryId;
    }
    
    /** full constructor */
    public TbRegistration(Integer NRegId, MsStaff msStaff, MsDivision msDivision, TbMedicalRecord tbMedicalRecord, TbRegistration tbRegistration, MsUnit msUnit, Date DRegistrationDate, String VRegSecondaryId, long NEscortPrimaryId, String VRegCancelationNote, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, String VMainDoctorStatus, String VRegCancelationStatus, Integer NRoomRsvId, Integer regStatus, Set tbRegistrations, Set tbBedOccupancies, Set tbExaminations, Set tbPatientBills) {
        this.NRegId = NRegId;
        this.msStaff = msStaff;
        this.msDivision = msDivision;
        this.tbMedicalRecord = tbMedicalRecord;
        this.tbRegistration = tbRegistration;
        this.msUnit = msUnit;
        this.DRegistrationDate = DRegistrationDate;
        this.VRegSecondaryId = VRegSecondaryId;
        this.NEscortPrimaryId = NEscortPrimaryId;
        this.VRegCancelationNote = VRegCancelationNote;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.VMainDoctorStatus = VMainDoctorStatus;
        this.VRegCancelationStatus = VRegCancelationStatus;
        this.NRoomRsvId = NRoomRsvId;
        this.regStatus = regStatus;
        this.tbRegistrations = tbRegistrations;
        this.tbBedOccupancies = tbBedOccupancies;
        this.tbExaminations = tbExaminations;
        this.tbPatientBills = tbPatientBills;
    }

   
    // Property accessors

    public Integer getNRegId() {
        return this.NRegId;
    }
    
    public void setNRegId(Integer NRegId) {
        this.NRegId = NRegId;
    }

    public MsStaff getMsStaff() {
        return this.msStaff;
    }
    
    public void setMsStaff(MsStaff msStaff) {
        this.msStaff = msStaff;
    }

    public MsDivision getMsDivision() {
        return this.msDivision;
    }
    
    public void setMsDivision(MsDivision msDivision) {
        this.msDivision = msDivision;
    }

    public TbMedicalRecord getTbMedicalRecord() {
        return this.tbMedicalRecord;
    }
    
    public void setTbMedicalRecord(TbMedicalRecord tbMedicalRecord) {
        this.tbMedicalRecord = tbMedicalRecord;
    }

    public TbRegistration getTbRegistration() {
        return this.tbRegistration;
    }
    
    public void setTbRegistration(TbRegistration tbRegistration) {
        this.tbRegistration = tbRegistration;
    }

    public MsUnit getMsUnit() {
        return this.msUnit;
    }
    
    public void setMsUnit(MsUnit msUnit) {
        this.msUnit = msUnit;
    }

    public Date getDRegistrationDate() {
        return this.DRegistrationDate;
    }
    
    public void setDRegistrationDate(Date DRegistrationDate) {
        this.DRegistrationDate = DRegistrationDate;
    }

    public String getVRegSecondaryId() {
        return this.VRegSecondaryId;
    }
    
    public void setVRegSecondaryId(String VRegSecondaryId) {
        this.VRegSecondaryId = VRegSecondaryId;
    }

    public long getNEscortPrimaryId() {
        return this.NEscortPrimaryId;
    }
    
    public void setNEscortPrimaryId(long NEscortPrimaryId) {
        this.NEscortPrimaryId = NEscortPrimaryId;
    }

    public String getVRegCancelationNote() {
        return this.VRegCancelationNote;
    }
    
    public void setVRegCancelationNote(String VRegCancelationNote) {
        this.VRegCancelationNote = VRegCancelationNote;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVMainDoctorStatus() {
        return this.VMainDoctorStatus;
    }
    
    public void setVMainDoctorStatus(String VMainDoctorStatus) {
        this.VMainDoctorStatus = VMainDoctorStatus;
    }

    public String getVRegCancelationStatus() {
        return this.VRegCancelationStatus;
    }
    
    public void setVRegCancelationStatus(String VRegCancelationStatus) {
        this.VRegCancelationStatus = VRegCancelationStatus;
    }

    public Integer getNRoomRsvId() {
        return this.NRoomRsvId;
    }
    
    public void setNRoomRsvId(Integer NRoomRsvId) {
        this.NRoomRsvId = NRoomRsvId;
    }

    public Integer getRegStatus() {
        return this.regStatus;
    }
    
    public void setRegStatus(Integer regStatus) {
        this.regStatus = regStatus;
    }

    public Set getTbRegistrations() {
        return this.tbRegistrations;
    }
    
    public void setTbRegistrations(Set tbRegistrations) {
        this.tbRegistrations = tbRegistrations;
    }

    public Set getTbBedOccupancies() {
        return this.tbBedOccupancies;
    }
    
    public void setTbBedOccupancies(Set tbBedOccupancies) {
        this.tbBedOccupancies = tbBedOccupancies;
    }

    public Set getTbExaminations() {
        return this.tbExaminations;
    }
    
    public void setTbExaminations(Set tbExaminations) {
        this.tbExaminations = tbExaminations;
    }

    public Set getTbPatientBills() {
        return this.tbPatientBills;
    }
    
    public void setTbPatientBills(Set tbPatientBills) {
        this.tbPatientBills = tbPatientBills;
    }
   








}