package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.pojo.item.MsVendor;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbPurchaseOrder generated by MyEclipse - Hibernate Tools
 */

public class TbReturItem  implements java.io.Serializable {


    // Fields    

     private Integer NReturId;
     private TbBatchItem tbBatchItem;
     private Integer NQty;
     private Double NPrice;
     private String VReason;
     private String VWhoCreate;
     private Date DWhnCreate;     
     private String VWhoChange;
     private Date DWhnChange;

    // Constructors

    /** default constructor */
    public TbReturItem() {
    }

	public Date getDWhnChange() {
		return DWhnChange;
	}

	public void setDWhnChange(Date whnChange) {
		DWhnChange = whnChange;
	}

	public Date getDWhnCreate() {
		return DWhnCreate;
	}

	public void setDWhnCreate(Date whnCreate) {
		DWhnCreate = whnCreate;
	}

	public Double getNPrice() {
		return NPrice;
	}

	public void setNPrice(Double price) {
		NPrice = price;
	}

	public Integer getNQty() {
		return NQty;
	}

	public void setNQty(Integer qty) {
		NQty = qty;
	}

	public Integer getNReturId() {
		return NReturId;
	}

	public void setNReturId(Integer returId) {
		NReturId = returId;
	}

	public TbBatchItem getTbBatchItem() {
		return tbBatchItem;
	}

	public void setTbBatchItem(TbBatchItem tbBatchItem) {
		this.tbBatchItem = tbBatchItem;
	}

	public String getVWhoChange() {
		return VWhoChange;
	}

	public void setVWhoChange(String whoChange) {
		VWhoChange = whoChange;
	}

	public String getVWhoCreate() {
		return VWhoCreate;
	}

	public void setVWhoCreate(String whoCreate) {
		VWhoCreate = whoCreate;
	}

	public String getVReason() {
		return VReason;
	}

	public void setVReason(String reason) {
		VReason = reason;
	}
}