package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbReturPharmacyTrx generated by MyEclipse - Hibernate Tools
 */

public class TbReturPharmacyTrx  implements java.io.Serializable {


    // Fields    

     private Integer NReturId;
     private MsPatient msPatient;
     private TbRegistration tbRegistration;
	 private TbExamination tbExamination;
     private TbPatientBill tbPatitentBill;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private String VReturCode;
     private Short NStatus;
     private Short NPaymentStatus;
     private Double NTrxValue;
     private Set tbReturPharmacyDetailTrxes = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbReturPharmacyTrx() {
    }

	/** minimal constructor */
    public TbReturPharmacyTrx(Integer NReturId, String VReturCode) {
        this.NReturId = NReturId;
        this.VReturCode = VReturCode;
    }
    
    /** full constructor */
    public TbReturPharmacyTrx(Integer NReturId, MsPatient msPatient, TbExamination tbExamination, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange, String VReturCode, short NStatus, double NTrxValue, Set tbReturPharmacyDetailTrxes) {
        this.NReturId = NReturId;
        this.msPatient = msPatient;
        this.tbExamination = tbExamination;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.VReturCode = VReturCode;
        this.NStatus = NStatus;
        this.NTrxValue = NTrxValue;
        this.tbReturPharmacyDetailTrxes = tbReturPharmacyDetailTrxes;
    }

   
    // Property accessors
    
    public TbRegistration getTbRegistration() {
		return tbRegistration;
	}

	public void setTbRegistration(TbRegistration tbRegistration) {
		this.tbRegistration = tbRegistration;
	}

    public Integer getNReturId() {
        return this.NReturId;
    }
    
    public void setNReturId(Integer NReturId) {
        this.NReturId = NReturId;
    }

    public MsPatient getMsPatient() {
        return this.msPatient;
    }
    
    public void setMsPatient(MsPatient msPatient) {
        this.msPatient = msPatient;
    }

    public TbExamination getTbExamination() {
        return this.tbExamination;
    }
    
    public void setTbExamination(TbExamination tbExamination) {
        this.tbExamination = tbExamination;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public String getVReturCode() {
        return this.VReturCode;
    }
    
    public void setVReturCode(String VReturCode) {
        this.VReturCode = VReturCode;
    }

    public Short getNStatus() {
        return this.NStatus;
    }
    
    public void setNStatus(Short NStatus) {
        this.NStatus = NStatus;
    }

    public Double getNTrxValue() {
        return this.NTrxValue;
    }
    
    public void setNTrxValue(Double NTrxValue) {
        this.NTrxValue = NTrxValue;
    }

    public Set getTbReturPharmacyDetailTrxes() {
        return this.tbReturPharmacyDetailTrxes;
    }
    
    public void setTbReturPharmacyDetailTrxes(Set tbReturPharmacyDetailTrxes) {
        this.tbReturPharmacyDetailTrxes = tbReturPharmacyDetailTrxes;
    }

	public Short getNPaymentStatus() {
		return NPaymentStatus;
	}

	public void setNPaymentStatus(Short paymentStatus) {
		NPaymentStatus = paymentStatus;
	}

	public TbPatientBill getTbPatitentBill() {
		return tbPatitentBill;
	}

	public void setTbPatitentBill(TbPatientBill tbPatitentBill) {
		this.tbPatitentBill = tbPatitentBill;
	}


}