package com.vone.medisafe.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbReturnTrx generated by MyEclipse - Hibernate Tools
 */

public class TbReturnTrx  implements java.io.Serializable {


    // Fields    

     private Integer NReturnTrxId;
     private String VReturnTrxCode;
     private double NTtlReturnTrx;
     private String VRtrTrxStatus;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbReturnTrxDets = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbReturnTrx() {
    }
   
    // Property accessors

    public Integer getNReturnTrxId() {
        return this.NReturnTrxId;
    }
    
    public void setNReturnTrxId(Integer NReturnTrxId) {
        this.NReturnTrxId = NReturnTrxId;
    }
    
    public String getVReturnTrxCode() {
        return this.VReturnTrxCode;
    }
    
    public void setVReturnTrxCode(String VReturnTrxCode) {
        this.VReturnTrxCode = VReturnTrxCode;
    }

    public double getNTtlReturnTrx() {
        return this.NTtlReturnTrx;
    }
    
    public void setNTtlReturnTrx(double NTtlReturnTrx) {
        this.NTtlReturnTrx = NTtlReturnTrx;
    }

    public String getVRtrTrxStatus() {
        return this.VRtrTrxStatus;
    }
    
    public void setVRtrTrxStatus(String VRtrTrxStatus) {
        this.VRtrTrxStatus = VRtrTrxStatus;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbReturnTrxDets() {
        return this.tbReturnTrxDets;
    }
    
    public void setTbReturnTrxDets(Set tbReturnTrxDets) {
        this.tbReturnTrxDets = tbReturnTrxDets;
    }
   








}