package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.MsItem;
import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbReturPharmacyDetailTrx generated by MyEclipse - Hibernate Tools
 */

public class TbReturPharmacyDetailTrx  implements java.io.Serializable {


    // Fields    

     private Integer NReturDetId;
     private TbReturPharmacyTrx tbReturPharmacyTrx;
     private MsItem msItem;
     private TbBatchItem tbBatchItem;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnCreate;
     private Date DWhnChange;
     private Short NQty;
     private Double NValue;
     private Short NTotalQty;


    // Constructors

    public Short getNTotalQty() {
		return NTotalQty;
	}

	public void setNTotalQty(Short totalQty) {
		NTotalQty = totalQty;
	}

	public Double getNValue() {
		return NValue;
	}

	public void setNValue(Double value) {
		NValue = value;
	}

	/** default constructor */
    public TbReturPharmacyDetailTrx() {
    }

	/** minimal constructor */
    public TbReturPharmacyDetailTrx(Integer NReturDetId) {
        this.NReturDetId = NReturDetId;
    }
    
    /** full constructor */
    public TbReturPharmacyDetailTrx(Integer NReturDetId, TbReturPharmacyTrx tbReturPharmacyTrx, MsItem msItem, String VWhoCreate, String VWhoChange, Date DWhnCreate, Date DWhnChange, short NQty) {
        this.NReturDetId = NReturDetId;
        this.tbReturPharmacyTrx = tbReturPharmacyTrx;
        this.msItem = msItem;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnCreate = DWhnCreate;
        this.DWhnChange = DWhnChange;
        this.NQty = NQty;
    }

   
    // Property accessors

    public Integer getNReturDetId() {
        return this.NReturDetId;
    }
    
    public void setNReturDetId(Integer NReturDetId) {
        this.NReturDetId = NReturDetId;
    }

    public TbReturPharmacyTrx getTbReturPharmacyTrx() {
        return this.tbReturPharmacyTrx;
    }
    
    public void setTbReturPharmacyTrx(TbReturPharmacyTrx tbReturPharmacyTrx) {
        this.tbReturPharmacyTrx = tbReturPharmacyTrx;
    }

    public MsItem getMsItem() {
        return this.msItem;
    }
    
    public void setMsItem(MsItem msItem) {
        this.msItem = msItem;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(Short NQty) {
        this.NQty = NQty;
    }

	public TbBatchItem getTbBatchItem() {
		return tbBatchItem;
	}

	public void setTbBatchItem(TbBatchItem tbBatchItem) {
		this.tbBatchItem = tbBatchItem;
	}
   








}