package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbReturnTrxDet generated by MyEclipse - Hibernate Tools
 */

public class TbReturnTrxDet  implements java.io.Serializable {


    // Fields    

     private Integer NRtrTrxDetId;
     private TbReturnTrx tbReturnTrx;
     private String VRtrTrxDetName;
     private String VRtrTrxDetDesc;
     private short NRtrTrxDetQty;
     private double NRtrTrxDetFee;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbReturnTrxDet() {
    }

	/** minimal constructor */
    public TbReturnTrxDet(Integer NRtrTrxDetId, TbReturnTrx tbReturnTrx) {
        this.NRtrTrxDetId = NRtrTrxDetId;
        this.tbReturnTrx = tbReturnTrx;
    }
    
    /** full constructor */
    public TbReturnTrxDet(Integer NRtrTrxDetId, TbReturnTrx tbReturnTrx, String VRtrTrxDetName, String VRtrTrxDetDesc, short NRtrTrxDetQty, double NRtrTrxDetFee, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NRtrTrxDetId = NRtrTrxDetId;
        this.tbReturnTrx = tbReturnTrx;
        this.VRtrTrxDetName = VRtrTrxDetName;
        this.VRtrTrxDetDesc = VRtrTrxDetDesc;
        this.NRtrTrxDetQty = NRtrTrxDetQty;
        this.NRtrTrxDetFee = NRtrTrxDetFee;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNRtrTrxDetId() {
        return this.NRtrTrxDetId;
    }
    
    public void setNRtrTrxDetId(Integer NRtrTrxDetId) {
        this.NRtrTrxDetId = NRtrTrxDetId;
    }

    public TbReturnTrx getTbReturnTrx() {
        return this.tbReturnTrx;
    }
    
    public void setTbReturnTrx(TbReturnTrx tbReturnTrx) {
        this.tbReturnTrx = tbReturnTrx;
    }

    public String getVRtrTrxDetName() {
        return this.VRtrTrxDetName;
    }
    
    public void setVRtrTrxDetName(String VRtrTrxDetName) {
        this.VRtrTrxDetName = VRtrTrxDetName;
    }

    public String getVRtrTrxDetDesc() {
        return this.VRtrTrxDetDesc;
    }
    
    public void setVRtrTrxDetDesc(String VRtrTrxDetDesc) {
        this.VRtrTrxDetDesc = VRtrTrxDetDesc;
    }

    public short getNRtrTrxDetQty() {
        return this.NRtrTrxDetQty;
    }
    
    public void setNRtrTrxDetQty(short NRtrTrxDetQty) {
        this.NRtrTrxDetQty = NRtrTrxDetQty;
    }

    public double getNRtrTrxDetFee() {
        return this.NRtrTrxDetFee;
    }
    
    public void setNRtrTrxDetFee(double NRtrTrxDetFee) {
        this.NRtrTrxDetFee = NRtrTrxDetFee;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}