package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbRoomReservation generated by MyEclipse - Hibernate Tools
 */

public class TbRoomReservation  implements java.io.Serializable {


    // Fields    

     private Integer NRoomRsvId;
     private MsHall msHall;
     private TbRegistration tbRegistration;
     private MsTreatmentClass msTreatmentClass;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbRoomReservation() {
    }

	/** minimal constructor */
    public TbRoomReservation(Integer NRoomRsvId) {
        this.NRoomRsvId = NRoomRsvId;
    }
    
    /** full constructor */
    public TbRoomReservation(Integer NRoomRsvId, MsWard msWard, MsHall msHall, MsTreatmentClass msTreatmentClass, long NBedId, Date DRoomRsvDate, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NRoomRsvId = NRoomRsvId;
//        this.msWard = msWard;
        this.msHall = msHall;
        this.msTreatmentClass = msTreatmentClass;
//        this.NBedId = NBedId;
//        this.DRoomRsvDate = DRoomRsvDate;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNRoomRsvId() {
        return this.NRoomRsvId;
    }
    
    public void setNRoomRsvId(Integer NRoomRsvId) {
        this.NRoomRsvId = NRoomRsvId;
    }

//    public MsWard getMsWard() {
//        return this.msWard;
//    }
    
//    public void setMsWard(MsWard msWard) {
//        this.msWard = msWard;
//    }

    public MsHall getMsHall() {
        return this.msHall;
    }
    
    public void setMsHall(MsHall msHall) {
        this.msHall = msHall;
    }

    public MsTreatmentClass getMsTreatmentClass() {
        return this.msTreatmentClass;
    }
    
    public void setMsTreatmentClass(MsTreatmentClass msTreatmentClass) {
        this.msTreatmentClass = msTreatmentClass;
    }

//    public long getNBedId() {
//        return this.NBedId;
//    }
    
//    public void setNBedId(long NBedId) {
//        this.NBedId = NBedId;
//    }

//    public Date getDRoomRsvDate() {
//        return this.DRoomRsvDate;
//    }
//    
//    public void setDRoomRsvDate(Date DRoomRsvDate) {
//        this.DRoomRsvDate = DRoomRsvDate;
//    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

	public TbRegistration getTbRegistration() {
		return tbRegistration;
	}

	public void setTbRegistration(TbRegistration tbRegistration) {
		this.tbRegistration = tbRegistration;
	}
   








}