package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbStillbirth generated by MyEclipse - Hibernate Tools
 */

public class TbStillbirth  implements java.io.Serializable {


    // Fields    

     private Integer NStillbirthId;
     private TbDiagnose tbDiagnose;
     private String VStillbirthDesc;
     private String VDeathFoetus;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbStillbirth() {
    }

	/** minimal constructor */
    public TbStillbirth(TbDiagnose tbDiagnose, String VStillbirthDesc, String VDeathFoetus) {
        this.tbDiagnose = tbDiagnose;
        this.VStillbirthDesc = VStillbirthDesc;
        this.VDeathFoetus = VDeathFoetus;
    }
    
    /** full constructor */
    public TbStillbirth(TbDiagnose tbDiagnose, String VStillbirthDesc, String VDeathFoetus, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.tbDiagnose = tbDiagnose;
        this.VStillbirthDesc = VStillbirthDesc;
        this.VDeathFoetus = VDeathFoetus;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNStillbirthId() {
        return this.NStillbirthId;
    }
    
    public void setNStillbirthId(Integer NStillbirthId) {
        this.NStillbirthId = NStillbirthId;
    }

    public TbDiagnose getTbDiagnose() {
        return this.tbDiagnose;
    }
    
    public void setTbDiagnose(TbDiagnose tbDiagnose) {
        this.tbDiagnose = tbDiagnose;
    }

    public String getVStillbirthDesc() {
        return this.VStillbirthDesc;
    }
    
    public void setVStillbirthDesc(String VStillbirthDesc) {
        this.VStillbirthDesc = VStillbirthDesc;
    }

    public String getVDeathFoetus() {
        return this.VDeathFoetus;
    }
    
    public void setVDeathFoetus(String VDeathFoetus) {
        this.VDeathFoetus = VDeathFoetus;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}