package com.vone.medisafe.mapping;

import java.util.Date;


/**
 * TbTreatmentRoomReservation generated by MyEclipse - Hibernate Tools
 */

public class TbTreatmentRoomReservation  implements java.io.Serializable {


    // Fields    

     private Integer NTroomRsvId;
     private MsTreatmentRoom msTreatmentRoom;
     private TbMedicalRecord tbMedicalRecord;
     private Date DTreatmentSchedule;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public TbTreatmentRoomReservation() {
    }

	/** minimal constructor */
    public TbTreatmentRoomReservation(Integer NTroomRsvId, MsTreatmentRoom msTreatmentRoom, TbMedicalRecord tbMedicalRecord, Date DTreatmentSchedule, String VWhoCreate, Date DWhnCreate) {
        this.NTroomRsvId = NTroomRsvId;
        this.msTreatmentRoom = msTreatmentRoom;
        this.tbMedicalRecord = tbMedicalRecord;
        this.DTreatmentSchedule = DTreatmentSchedule;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
    }
    
    /** full constructor */
    public TbTreatmentRoomReservation(Integer NTroomRsvId, MsTreatmentRoom msTreatmentRoom, TbMedicalRecord tbMedicalRecord, Date DTreatmentSchedule, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NTroomRsvId = NTroomRsvId;
        this.msTreatmentRoom = msTreatmentRoom;
        this.tbMedicalRecord = tbMedicalRecord;
        this.DTreatmentSchedule = DTreatmentSchedule;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNTroomRsvId() {
        return this.NTroomRsvId;
    }
    
    public void setNTroomRsvId(Integer NTroomRsvId) {
        this.NTroomRsvId = NTroomRsvId;
    }

    public MsTreatmentRoom getMsTreatmentRoom() {
        return this.msTreatmentRoom;
    }
    
    public void setMsTreatmentRoom(MsTreatmentRoom msTreatmentRoom) {
        this.msTreatmentRoom = msTreatmentRoom;
    }

    public TbMedicalRecord getTbMedicalRecord() {
        return this.tbMedicalRecord;
    }
    
    public void setTbMedicalRecord(TbMedicalRecord tbMedicalRecord) {
        this.tbMedicalRecord = tbMedicalRecord;
    }

    public Date getDTreatmentSchedule() {
        return this.DTreatmentSchedule;
    }
    
    public void setDTreatmentSchedule(Date DTreatmentSchedule) {
        this.DTreatmentSchedule = DTreatmentSchedule;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}