package com.vone.medisafe.mapping;

import java.util.Date;

import com.vone.medisafe.mapping.pojo.item.TbBatchItem;


/**
 * TbTreatmentItemUsedTrx generated by MyEclipse - Hibernate Tools
 */

public class TbTreatmentItemUsedTrx  implements java.io.Serializable {


    // Fields    

     private Integer NTreatItemUsed;
     private TbBatchItem tbBatchItem;
     private TbTreatmentTrx tbTreatmentTrx;
     private short NQty;
     private String VWhoCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Date DWhnCreate;


    // Constructors

    /** default constructor */
    public TbTreatmentItemUsedTrx() {
    }

	/** minimal constructor */
    public TbTreatmentItemUsedTrx(Integer NTreatItemUsed) {
        this.NTreatItemUsed = NTreatItemUsed;
    }
    
    /** full constructor */
    public TbTreatmentItemUsedTrx(Integer NTreatItemUsed, TbBatchItem tbBatchItem, TbTreatmentTrx tbTreatmentTrx, short NQty, String VWhoCreate, String VWhoChange, Date DWhnChange, Date DWhnCreate) {
        this.NTreatItemUsed = NTreatItemUsed;
        this.tbBatchItem = tbBatchItem;
        this.tbTreatmentTrx = tbTreatmentTrx;
        this.NQty = NQty;
        this.VWhoCreate = VWhoCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.DWhnCreate = DWhnCreate;
    }

   
    // Property accessors

    public Integer getNTreatItemUsed() {
        return this.NTreatItemUsed;
    }
    
    public void setNTreatItemUsed(Integer NTreatItemUsed) {
        this.NTreatItemUsed = NTreatItemUsed;
    }

    public TbBatchItem getTbBatchItem() {
        return this.tbBatchItem;
    }
    
    public void setTbBatchItem(TbBatchItem tbBatchItem) {
        this.tbBatchItem = tbBatchItem;
    }

    public TbTreatmentTrx getTbTreatmentTrx() {
        return this.tbTreatmentTrx;
    }
    
    public void setTbTreatmentTrx(TbTreatmentTrx tbTreatmentTrx) {
        this.tbTreatmentTrx = tbTreatmentTrx;
    }

    public short getNQty() {
        return this.NQty;
    }
    
    public void setNQty(short NQty) {
        this.NQty = NQty;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }
   








}