package com.vone.medisafe.mapping;



/**
 * TbUserPrivilegeId generated by MyEclipse - Hibernate Tools
 */

public class TbUserPrivilegeId  implements java.io.Serializable {


    // Fields    

     private MsUser msUser;
     private MsScreen msScreen;


    // Constructors

    /** default constructor */
    public TbUserPrivilegeId() {
    }

    
    /** full constructor */
    public TbUserPrivilegeId(MsUser msUser, MsScreen msScreen) {
        this.msUser = msUser;
        this.msScreen = msScreen;
    }

   
    // Property accessors

    public MsUser getMsUser() {
        return this.msUser;
    }
    
    public void setMsUser(MsUser msUser) {
        this.msUser = msUser;
    }

    public MsScreen getMsScreen() {
        return this.msScreen;
    }
    
    public void setMsScreen(MsScreen msScreen) {
        this.msScreen = msScreen;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbUserPrivilegeId) ) return false;
		 TbUserPrivilegeId castOther = ( TbUserPrivilegeId ) other; 
         
		 return ( (this.getMsUser()==castOther.getMsUser()) || ( this.getMsUser()!=null && castOther.getMsUser()!=null && this.getMsUser().equals(castOther.getMsUser()) ) )
 && ( (this.getMsScreen()==castOther.getMsScreen()) || ( this.getMsScreen()!=null && castOther.getMsScreen()!=null && this.getMsScreen().equals(castOther.getMsScreen()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsUser() == null ? 0 : this.getMsUser().hashCode() );
         result = 37 * result + ( getMsScreen() == null ? 0 : this.getMsScreen().hashCode() );
         return result;
   }   





}