CREATE TABLE IF NOT EXISTS ad_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_number VARCHAR(40) NOT NULL UNIQUE,
    nik VARCHAR(40) NOT NULL UNIQUE,
    patient_name VARCHAR(150) NOT NULL,
    gender VARCHAR(5),
    birth_date VARCHAR(20),
    address VARCHAR(255),
    phone VARCHAR(40),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_outpatient_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(40) NOT NULL UNIQUE,
    mr_number VARCHAR(40) NOT NULL,
    patient_name VARCHAR(150) NOT NULL,
    nik VARCHAR(40) NOT NULL,
    unit_name VARCHAR(120) NOT NULL,
    doctor_name VARCHAR(120) NOT NULL,
    patient_type VARCHAR(50),
    ethnicity VARCHAR(80),
    language VARCHAR(80),
    status VARCHAR(20) NOT NULL,
    registered_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_inpatient_booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_number VARCHAR(40) NOT NULL UNIQUE,
    registration_number VARCHAR(40) NOT NULL UNIQUE,
    mr_number VARCHAR(40) NOT NULL,
    patient_name VARCHAR(150) NOT NULL,
    target_class VARCHAR(50) NOT NULL,
    hall_name VARCHAR(80) NOT NULL,
    bed_code VARCHAR(40) NOT NULL,
    main_doctor VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL,
    queued_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_inpatient_mutation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mutation_number VARCHAR(40) NOT NULL UNIQUE,
    registration_number VARCHAR(40) NOT NULL,
    mr_number VARCHAR(40) NOT NULL,
    patient_name VARCHAR(150) NOT NULL,
    from_bed VARCHAR(40) NOT NULL,
    to_bed VARCHAR(40) NOT NULL,
    mutated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    performed_by VARCHAR(80) NOT NULL,
    details VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ad_patient_mr ON ad_patient (mr_number);
CREATE INDEX IF NOT EXISTS idx_ad_patient_nik ON ad_patient (nik);
CREATE INDEX IF NOT EXISTS idx_ad_outpatient_status ON ad_outpatient_registration (status);
CREATE INDEX IF NOT EXISTS idx_ad_inpatient_booking_status ON ad_inpatient_booking (status);
CREATE INDEX IF NOT EXISTS idx_ad_inpatient_mutation_reg ON ad_inpatient_mutation (registration_number);
