package com.vone.medisafe.mapping.pojo;

import java.util.Date;

import com.vone.medisafe.mapping.MsTreatment;


/**
 * MsLabTestDetail generated by MyEclipse - Hibernate Tools
 */

public class MsLabTestDetail  implements java.io.Serializable {


    // Fields    

     private Integer NLabTestDetId;
     private MsTreatment msTreatment;
     private String VNrmlRangeGroup;
     private String VNrmlRange;
     private String VLabTestQuantify;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;


    // Constructors

    /** default constructor */
    public MsLabTestDetail() {
    }

	/** minimal constructor */
    public MsLabTestDetail(Integer NLabTestDetId, MsTreatment msTreatment, String VNrmlRangeGroup, String VNrmlRange, String VLabTestQuantify) {
        this.NLabTestDetId = NLabTestDetId;
        this.msTreatment = msTreatment;
        this.VNrmlRangeGroup = VNrmlRangeGroup;
        this.VNrmlRange = VNrmlRange;
        this.VLabTestQuantify = VLabTestQuantify;
    }
    
    /** full constructor */
    public MsLabTestDetail(Integer NLabTestDetId, MsTreatment msTreatment, String VNrmlRangeGroup, String VNrmlRange, String VLabTestQuantify, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange) {
        this.NLabTestDetId = NLabTestDetId;
        this.msTreatment = msTreatment;
        this.VNrmlRangeGroup = VNrmlRangeGroup;
        this.VNrmlRange = VNrmlRange;
        this.VLabTestQuantify = VLabTestQuantify;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
    }

   
    // Property accessors

    public Integer getNLabTestDetId() {
        return this.NLabTestDetId;
    }
    
    public void setNLabTestDetId(Integer NLabTestDetId) {
        this.NLabTestDetId = NLabTestDetId;
    }

    public MsTreatment getMsTreatment() {
        return this.msTreatment;
    }
    
    public void setMsTreatment(MsTreatment msTreatment) {
        this.msTreatment = msTreatment;
    }

    public String getVNrmlRangeGroup() {
        return this.VNrmlRangeGroup;
    }
    
    public void setVNrmlRangeGroup(String VNrmlRangeGroup) {
        this.VNrmlRangeGroup = VNrmlRangeGroup;
    }

    public String getVNrmlRange() {
        return this.VNrmlRange;
    }
    
    public void setVNrmlRange(String VNrmlRange) {
        this.VNrmlRange = VNrmlRange;
    }

    public String getVLabTestQuantify() {
        return this.VLabTestQuantify;
    }
    
    public void setVLabTestQuantify(String VLabTestQuantify) {
        this.VLabTestQuantify = VLabTestQuantify;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }
   








}