package com.vone.medisafe.mapping.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vone.medisafe.mapping.MsCoa;
import com.vone.medisafe.mapping.MsPatientType;


/**
 * MsMiscFee generated by MyEclipse - Hibernate Tools
 */

public class MsMiscFee  implements java.io.Serializable {


    // Fields    

     private Integer NMfeeId;
     private MsCoa msCoa;
     private MsPatientType msPatientType;
     private String VMfeeCode;
     private String VMfeeName;
     private String VMfeeDesc;
     private double NMfeePrice;
     private String VWhoCreate;
     private Date DWhnCreate;
     private String VWhoChange;
     private Date DWhnChange;
     private Set tbPatientBillDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public MsMiscFee() {
    }

	/** minimal constructor */
    public MsMiscFee(Integer NMfeeId, MsPatientType msPatientType) {
        this.NMfeeId = NMfeeId;
        this.msPatientType = msPatientType;
    }
    
    /** full constructor */
    public MsMiscFee(Integer NMfeeId, MsCoa msCoa, MsPatientType msPatientType, String VMfeeCode, String VMfeeName, String VMfeeDesc, double NMfeePrice, String VWhoCreate, Date DWhnCreate, String VWhoChange, Date DWhnChange, Set tbPatientBillDetails) {
        this.NMfeeId = NMfeeId;
        this.msCoa = msCoa;
        this.msPatientType = msPatientType;
        this.VMfeeCode = VMfeeCode;
        this.VMfeeName = VMfeeName;
        this.VMfeeDesc = VMfeeDesc;
        this.NMfeePrice = NMfeePrice;
        this.VWhoCreate = VWhoCreate;
        this.DWhnCreate = DWhnCreate;
        this.VWhoChange = VWhoChange;
        this.DWhnChange = DWhnChange;
        this.tbPatientBillDetails = tbPatientBillDetails;
    }

   
    // Property accessors

    public Integer getNMfeeId() {
        return this.NMfeeId;
    }
    
    public void setNMfeeId(Integer NMfeeId) {
        this.NMfeeId = NMfeeId;
    }

    public MsCoa getMsCoa() {
        return this.msCoa;
    }
    
    public void setMsCoa(MsCoa msCoa) {
        this.msCoa = msCoa;
    }

    public MsPatientType getMsPatientType() {
        return this.msPatientType;
    }
    
    public void setMsPatientType(MsPatientType msPatientType) {
        this.msPatientType = msPatientType;
    }

    public String getVMfeeCode() {
        return this.VMfeeCode;
    }
    
    public void setVMfeeCode(String VMfeeCode) {
        this.VMfeeCode = VMfeeCode;
    }

    public String getVMfeeName() {
        return this.VMfeeName;
    }
    
    public void setVMfeeName(String VMfeeName) {
        this.VMfeeName = VMfeeName;
    }

    public String getVMfeeDesc() {
        return this.VMfeeDesc;
    }
    
    public void setVMfeeDesc(String VMfeeDesc) {
        this.VMfeeDesc = VMfeeDesc;
    }

    public double getNMfeePrice() {
        return this.NMfeePrice;
    }
    
    public void setNMfeePrice(double NMfeePrice) {
        this.NMfeePrice = NMfeePrice;
    }

    public String getVWhoCreate() {
        return this.VWhoCreate;
    }
    
    public void setVWhoCreate(String VWhoCreate) {
        this.VWhoCreate = VWhoCreate;
    }

    public Date getDWhnCreate() {
        return this.DWhnCreate;
    }
    
    public void setDWhnCreate(Date DWhnCreate) {
        this.DWhnCreate = DWhnCreate;
    }

    public String getVWhoChange() {
        return this.VWhoChange;
    }
    
    public void setVWhoChange(String VWhoChange) {
        this.VWhoChange = VWhoChange;
    }

    public Date getDWhnChange() {
        return this.DWhnChange;
    }
    
    public void setDWhnChange(Date DWhnChange) {
        this.DWhnChange = DWhnChange;
    }

    public Set getTbPatientBillDetails() {
        return this.tbPatientBillDetails;
    }
    
    public void setTbPatientBillDetails(Set tbPatientBillDetails) {
        this.tbPatientBillDetails = tbPatientBillDetails;
    }
   








}